export const eosClerkAppearance = {
  variables: {
    colorPrimary: "#6a37d4",
    colorPrimaryForeground: "#ffffff",
    colorForeground: "#2c2f30",
    colorMuted: "#eff1f2",
    colorMutedForeground: "#595c5d",
    colorBackground: "#ffffff",
    colorInput: "#eff1f2",
    colorInputForeground: "#2c2f30",
    colorNeutral: "#595c5d",
    colorRing: "#6a37d4",
    colorShadow: "rgba(106, 55, 212, 0.18)",
    colorBorder: "rgba(171, 173, 174, 0.18)",
    fontFamily: "system-ui, sans-serif",
    fontFamilyButtons: "system-ui, sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full max-w-[400px]",
    cardBox: "w-full shadow-none",
    card: "w-full border-0 shadow-[0_16px_48px_rgba(106,55,212,0.10)]",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    formButtonPrimary: "bg-[#6a37d4] hover:bg-[#5a2dc0] shadow-none",
    formFieldInput: "border-0 bg-[#eff1f2] shadow-none focus:ring-2 focus:ring-[#6a37d4]/20",
    socialButtonsBlockButton: "border-0 bg-[#eff1f2] shadow-none hover:bg-[#e7e9eb]",
    footer: "bg-white",
  },
} as const;
