import { companyPackageSchema } from "@shared/company-compilation";
import type { CompanySourceBinding } from "@shared/company-source-adapter";
import { createNotionSourceBinding } from "../company-compilation/notion-source-adapter";
import { declarativeCompanyPackageMaterializer, type DeclarativeRuntimeBindings } from "../company-compilation/declarative-materializer";

export const AFM_REFERENCE_PACKAGE = {
  key: "afm-company-package",
  version: "2026-08-22",
  organizationKey: "ORG-AFM",
  canonicalName: "AFM",
  sources: {
    registry: "https://app.notion.com/p/3c3da8b96e4f81bead18e7ed1f288a82",
    runtime: "https://app.notion.com/p/3a8da8b96e4f81029d2cd7204f8cfcdf",
    accountabilityChart: "https://app.notion.com/p/3b1da8b96e4f816bbbc1e5ba2e580294",
    contentLifecycle: "https://app.notion.com/p/3bcda8b96e4f81d6bec3ea5f06f31617",
    scorecards: "https://app.notion.com/p/3bcda8b96e4f81eca42ee338ee39a438",
    brandChannel: "https://app.notion.com/p/3bcda8b96e4f815d8a91f7876fa87dd0",
    empyreanServiceSop: "https://app.notion.com/p/3bcda8b96e4f810ea182d97175492862",
  },
  activationBlockers: [
    "Verify AFM's exact legal entity and account-holder identity.",
    "Bind exact publication-channel accounts and final-publisher authority.",
    "Run one real source moment through the full governed content lifecycle.",
    "Publish only after likeness, voice, factual, rights, Brand and founder review.",
    "Capture channel receipts, measurement, asset lineage and learning disposition.",
    "Qualify the AFM-to-Empyrean shared-service request and acceptance boundary.",
  ],
} as const;

const EFFECTIVE_AT = "2026-08-21T00:00:00.000Z";

function artifact<T>(stableId: string, artifactType: string, sourceRef: string, value: T) {
  return {
    metadata: {
      stableId,
      orgKey: AFM_REFERENCE_PACKAGE.organizationKey,
      artifactType,
      schemaVersion: "eos.company-compilation.v1",
      artifactVersion: AFM_REFERENCE_PACKAGE.version,
      status: "approved" as const,
      activationState: "blocked" as const,
      ownershipClass: "owned" as const,
      authorityClass: "reference" as const,
      privacyClass: "internal" as const,
      ownerRole: "Founder / Chief Executive Officer & Principal Creator",
      sourceRef,
      sourceRevision: AFM_REFERENCE_PACKAGE.version,
      effectiveAt: EFFECTIVE_AT,
      expiresAt: null,
      supersedes: [],
      confidence: "supported" as const,
      evidenceRefs: [], dependencyRefs: [], approvalRefs: [],
    },
    value,
  };
}

const capabilities = ([
  ["executive-assistance", "Executive Assistance", [8]],
  ["creator-operations", "Creator Operations", [10, 14]],
  ["content-strategy", "Content Strategy", [11, 14]],
  ["brand-intelligence", "Brand Intelligence", [14]],
  ["content-production", "Content Production", [6, 14]],
  ["post-production", "Post-production", [6, 14]],
  ["distribution-publication", "Distribution and Publication", [14]],
  ["rights-confidentiality", "Rights, Release and Confidentiality Control", [13, 14]],
  ["audience-performance-learning", "Audience and Performance Learning", [7, 11, 14]],
  ["brand-monetization", "Brand Deals, Sponsorships and Affiliate Monetization", [2, 3, 14]],
  ["shared-service-procurement", "Governed Shared-service Procurement", [10, 12]],
] satisfies Array<[string, string, number[]]>).map(([key, name, moduleIds]) => ({
  key, name, moduleIds, state: "required" as const,
  activationGateRefs: AFM_REFERENCE_PACKAGE.activationBlockers,
}));

export const AFM_COMPANY_PACKAGE = companyPackageSchema.parse({
  metadata: artifact(AFM_REFERENCE_PACKAGE.key, "company_package", AFM_REFERENCE_PACKAGE.sources.registry, null).metadata,
  packageKey: AFM_REFERENCE_PACKAGE.key,
  packageVersion: AFM_REFERENCE_PACKAGE.version,
  materializerKey: "declarative-company-package-v1",
  targetCompanyAliases: ["AFM", "Antony F. Munoz", "Personal Brand — Antony (AFM)", "Antony F Munoz"],
  universalCompanyTemplateRef: artifact(
    "eos-universal-company-template-v1", "universal_company_template_ref",
    "https://app.notion.com/p/3b0da8b96e4f81e5bb28eee117838b5e",
    { key: "eos-universal-company-template", version: "1.0", sourceRef: "https://app.notion.com/p/3b0da8b96e4f81e5bb28eee117838b5e", sourceRevision: "2026-08-06" },
  ),
  domainPackRefs: [
    artifact("domain-pack-media-brand-v1", "domain_pack_ref", AFM_REFERENCE_PACKAGE.sources.runtime,
      { key: "media-brand", version: "1.0", sourceRef: AFM_REFERENCE_PACKAGE.sources.runtime, sourceRevision: AFM_REFERENCE_PACKAGE.version }),
    artifact("domain-pack-content-distribution-v1", "domain_pack_ref", AFM_REFERENCE_PACKAGE.sources.contentLifecycle,
      { key: "content-distribution", version: "1.0", sourceRef: AFM_REFERENCE_PACKAGE.sources.contentLifecycle, sourceRevision: AFM_REFERENCE_PACKAGE.version }),
  ],
  companyManifest: artifact("afm-company-manifest", "company_manifest", AFM_REFERENCE_PACKAGE.sources.registry, {
    legalName: "AFM",
    operatingName: "AFM",
    orgKey: "ORG-AFM",
    ownershipClass: "owned",
    visibility: "public",
    mission: "Operate the founder-led media, public trust, distribution and Brand-monetization company around Antony F. Munoz while ensuring every claim inherits proof.",
    offerKeys: ["brand-deals", "sponsorships", "affiliate-offers", "media"],
    idealCustomerProfile: "Relevant audiences, aligned commercial partners, talent and portfolio stakeholders reached through truthful proof-led media.",
    lifecycleStage: "validation",
    clientAuthorityReference: null,
  }),
  capabilityManifest: artifact("afm-capability-manifest", "capability_manifest", AFM_REFERENCE_PACKAGE.sources.runtime, capabilities),
  lifecycleActivationMap: artifact("afm-lifecycle-activation-map", "lifecycle_activation_map", AFM_REFERENCE_PACKAGE.sources.registry, {
    requestedState: "blocked",
    activationGates: AFM_REFERENCE_PACKAGE.activationBlockers,
    dependencies: ["Exact channel authority", "Real source moment", "Rights and Brand review", "Provider receipts", "Measured outcome"],
    rolloutSequence: ["Compile isolated dry-run company", "Bind exact sources and channels", "Run first governed content cycle", "Record measurement and exceptions", "Issue explicit founder activation decision"],
    stopLaws: [
      "Do not claim AFM sells a community offer.",
      "Do not publish uncited facts, unapproved synthetic likeness or voice output, or private incubations as publicly available.",
      "Do not merge ORG-AFM, BRAND-AFM, Antony the person, Empyrean Studios or Lyfe Institute.",
      "Do not let a shared-service relationship create a cross-company agent-parent edge.",
      "Do not infer publication, measurement, revenue or field qualification from a compiled record.",
    ],
    rollbackConditions: ["Wrong account or Brand publication", "Rights, confidentiality, factual or likeness review failure", "Provider identity or receipt mismatch", "Cross-company authority breach"],
  }),
  orgRoleAgentGraph: artifact("afm-org-role-agent-graph", "org_role_agent_graph", AFM_REFERENCE_PACKAGE.sources.accountabilityChart, [
    { key: "founder", title: "Founder / Portfolio Principal", kind: "founder", reportsToSeatKey: null, agentName: "Executive Assistant", occupancyMode: "human_with_agent_assistant", mandate: "Retain portfolio owner authority while communicating with each company through its CEO layer.", separationOfDutyRefs: ["Founder final-publication and high-consequence approval policy"] },
    { key: "company-ceo", title: "Founder / Chief Executive Officer & Principal Creator", kind: "company_ceo", reportsToSeatKey: "founder", agentName: "AFM CEO Agent", occupancyMode: "human_with_agent_assistant", mandate: "Own AFM results, final publication and the company-agent hierarchy while operating BRAND-AFM as a distinct Brand asset.", separationOfDutyRefs: ["Publication remains human-controlled"] },
    { key: "executive-assistant-i", title: "Executive Assistant I", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Executive Assistant I Agent", occupancyMode: "agent", mandate: "Keep founder commitments, approvals, meetings and decision follow-through current without taking unauthorized external decisions.", separationOfDutyRefs: ["No unauthorized external decisions"] },
    { key: "creator-operations-coordinator-i", title: "Creator Operations Coordinator I", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Creator Operations Coordinator I Agent", occupancyMode: "agent", mandate: "Keep content states, owners, deadlines, dependencies and evidence visible across the canonical lifecycle.", separationOfDutyRefs: ["Cannot approve founder publication"] },
    { key: "content-strategist-i", title: "Content Strategist I", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Content Strategist I Agent", occupancyMode: "human_with_agent_assistant", mandate: "Turn real operating and life signals into truthful content briefs, with Brand Intelligence nested as a specialist rather than a peer role.", separationOfDutyRefs: ["Unsupported or fabricated claims prohibited"] },
    { key: "associate-content-producer", title: "Associate Content Producer", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Associate Content Producer Role Agent", occupancyMode: "agent", mandate: "Maintain AFM accountability and liaison memory for provider-led production while preserving rights, assets and acceptance evidence.", separationOfDutyRefs: ["Provider work does not transfer AFM authority"] },
    { key: "assistant-video-editor", title: "Assistant Video Editor", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Assistant Video Editor Role Agent", occupancyMode: "agent", mandate: "Maintain workflow and version memory for provider-led editing while preserving Brand, technical and review standards.", separationOfDutyRefs: ["Cannot publish"] },
    { key: "social-media-coordinator-i", title: "Social Media Coordinator I", kind: "individual_contributor", reportsToSeatKey: "company-ceo", agentName: "AFM Social Media Coordinator I Agent", occupancyMode: "agent", mandate: "Prepare correct-account publication and measurement state while keeping publication human-controlled.", separationOfDutyRefs: ["Wrong-account publication is a high-severity incident", "Publication remains human-controlled"] },
  ]),
  authorityPolicySet: artifact("afm-authority-policy-set", "authority_policy_set", AFM_REFERENCE_PACKAGE.sources.accountabilityChart, [
    { key: "founder-owner", subjectSeatKey: "founder", authorityClasses: ["owner", "approve", "decide", "verify"], dataClasses: ["public", "internal", "confidential", "restricted"], transactionLimit: "No live commercial or publication effect without exact account and policy authority.", disclosureLimit: "Portfolio scope subject to company and Brand classification boundaries." },
    { key: "afm-ceo", subjectSeatKey: "company-ceo", authorityClasses: ["recommend", "decide", "approve", "execute", "verify"], dataClasses: ["public", "internal", "confidential", "restricted"], transactionLimit: "Founder retains final publication and material commercial authority during Phase 1.", disclosureLimit: "ORG-AFM and BRAND-AFM scope; shared-service disclosure requires an explicit Work Packet." },
  ]),
  workflowArtifactMap: artifact("afm-workflow-artifact-map", "workflow_artifact_map", AFM_REFERENCE_PACKAGE.sources.contentLifecycle, [{
    key: "afm-content-lifecycle", name: "AFM canonical Phase-1 content lifecycle", stateMachineRef: "eos.afm.content-lifecycle.v1",
    workPacketKeys: ["select-real-source-moment", "approve-content-brief", "produce-review-and-revise", "founder-approve-and-publish", "capture-measurement-and-learning"],
    artifactRequirements: ["Source record", "Approved brief", "Rights and confidentiality review", "Versioned publication asset", "Publication receipt", "Measurement record", "Learning disposition"],
    evidenceRequirements: ["Source lineage", "Attributable review and approval", "Correct account and Brand identity", "Provider publication URL or object ID", "Defined-window measurement without invented attribution"],
    exceptionPath: "Stop publication, preserve the asset and state, assign one exception owner, escalate to the AFM CEO Agent and founder, and record correction, takedown or recovery evidence.",
  }]),
  providerBindingDeclarations: artifact("afm-provider-bindings", "provider_binding_declarations", AFM_REFERENCE_PACKAGE.sources.runtime, [
    ["notion", "Notion", "notion_public_oauth", "Current AFM Notion workspace pages and databases"],
    ["google-drive", "Google Drive", "google_workspace_oauth", "AFM brand, content and historical Drive artifacts"],
    ["creatoros", "CreatorOS", "signed_https", "Authorized content packaging and evidence exchange"],
    ["publication-channels", "Publication Channels", "provider_oauth", "Exact AFM social and media accounts pending binding"],
    ["empyrean-shared-services", "Empyrean Studios Shared Services", "manual", "Governed ORG-AFM to ORG-EMPYREAN-STUDIOS Work Packets"],
  ].map(([key, provider, adapterClass, accountScope]) => ({
    key, provider, adapterClass, accountScope, credentialReference: null, authorityState: "selected", healthState: "unknown",
    substitutionRule: "EOS remains standalone-safe; no provider success is inferred and cutover requires exact-account parity evidence.",
    manualFallback: "Route to the accountable human or provider through a governed Work Packet and attach the resulting evidence manually.",
  }))),
  economicsMetricContracts: artifact("afm-economics-metrics", "economics_metric_contracts", AFM_REFERENCE_PACKAGE.sources.scorecards, [
    { key: "publishing-reliability", name: "Publishing Reliability", definition: "Approved planned publications published inside the agreed window divided by approved planned publications.", target: "Establish a real Phase-1 baseline.", guardrail: "Do not count drafts or scheduled items as published.", attributionRule: "Require exact asset, account, URL or object ID and timestamp.", decisionGate: "Do not scale cadence until the lifecycle is reliable and rights complete." },
    { key: "rights-metadata-completeness", name: "Rights and Metadata Completeness", definition: "Published assets with complete provenance, rights, Brand, channel and version metadata divided by published assets.", target: "100%", guardrail: "Wrong-account or unauthorized publication target is zero.", attributionRule: "Measure from the canonical asset and publication records.", decisionGate: "Any material gap blocks reuse and triggers review." },
    { key: "qualified-audience-signal", name: "Qualified Audience Signal Rate", definition: "Defined high-intent or relevant responses per eligible reach or content item.", target: "Establish source-specific baselines before setting targets.", guardrail: "Vanity reach is not qualified demand and unavailable attribution remains unavailable.", attributionRule: "Bind signals to the exact content, channel and review window.", decisionGate: "Commercial changes require repeatable qualified signal, not one viral result." },
  ]),
  dataEvidenceContracts: artifact("afm-data-evidence-contracts", "data_evidence_contracts", AFM_REFERENCE_PACKAGE.sources.runtime, [
    { key: "claims-inherit-proof", dataClass: "internal", authoritativeSource: "Current AFM Notion canon plus exact source and publication evidence.", retentionRule: "Retain the minimum source, rights, versions, approvals, receipts and measurement needed for audit and reuse.", lineageRequirement: "Every public claim traces to the source and proof level: learning, one-time done, repeatedly proven or organizationally reproducible.", qualificationRule: "Compiled, drafted or planned state is not publication or outcome proof.", promotionRule: "Promote only reviewed reusable learning without private portfolio truth." },
    { key: "brand-company-separation", dataClass: "confidential", authoritativeSource: "ORG-AFM company records and BRAND-AFM asset/channel records remain distinct.", retentionRule: "Preserve company, person, Brand, provider and beneficiary identity in every material record.", lineageRequirement: "Provider work retains provider attribution; AFM retains beneficiary, authority, asset, economic and outcome attribution.", qualificationRule: "A shared service never creates a cross-company reporting or agent-parent edge.", promotionRule: "Promote the reusable service pattern, not company-private content." },
  ]),
  failureRecoveryMap: artifact("afm-failure-recovery-map", "failure_recovery_map", AFM_REFERENCE_PACKAGE.sources.contentLifecycle, [
    { key: "publication-incident", failureClass: "Wrong-account, unauthorized, factually unsupported, rights-uncertain or confidentiality-risk publication.", incidentOwnerSeatKey: "social-media-coordinator-i", fallback: "Stop or suspend publication and escalate immediately.", recovery: "Correct or take down through the authoritative channel, preserve receipts and complete founder review.", continuity: "Continue only non-consequential preparation in EOS.", learningPromotionRule: "Update the reviewed control or SOP after root-cause evidence exists." },
    { key: "provider-handoff-failure", failureClass: "Provider production or shared-service handoff is incomplete, mis-scoped or lacks acceptance evidence.", incidentOwnerSeatKey: "creator-operations-coordinator-i", fallback: "Reject the handoff without reconstructing it silently.", recovery: "Return an explicit defect list, preserve versions and accept only against the Work Packet criteria.", continuity: "Keep AFM's queue and accountability state local and visible.", learningPromotionRule: "Promote only a verified, non-company-private handoff improvement." },
  ]),
  sourceAuthorityManifest: artifact("afm-source-authority-manifest", "source_authority_manifest", AFM_REFERENCE_PACKAGE.sources.registry, {
    sources: [
      ["registry", AFM_REFERENCE_PACKAGE.sources.registry, 1, "canonical"],
      ["runtime", AFM_REFERENCE_PACKAGE.sources.runtime, 2, "canonical"],
      ["accountability-chart", AFM_REFERENCE_PACKAGE.sources.accountabilityChart, 3, "canonical"],
      ["content-lifecycle", AFM_REFERENCE_PACKAGE.sources.contentLifecycle, 4, "canonical"],
      ["scorecards", AFM_REFERENCE_PACKAGE.sources.scorecards, 5, "supporting"],
      ["brand-channel", AFM_REFERENCE_PACKAGE.sources.brandChannel, 6, "canonical"],
      ["empyrean-service-sop", AFM_REFERENCE_PACKAGE.sources.empyreanServiceSop, 7, "canonical"],
    ].map(([key, sourceRef, precedence, status]) => ({ key, sourceRef, sourceRevision: AFM_REFERENCE_PACKAGE.version, precedence, status })),
    unresolvedConflicts: [],
    freshnessRule: "Latest explicit owner decision wins, followed by current AFM Notion canon, compatible AFM Drive artifacts, measured platform evidence and then labeled inference.",
    supersessionRule: "The fuller named-seat Phase-1 chart supersedes the historical minimal chart; historical blocks remain lineage only and cannot silently compile.",
  }),
});

export const AFM_RUNTIME_BINDINGS: DeclarativeRuntimeBindings = {
  processes: [
    {
      processKey: "afm-content-lifecycle",
      name: "AFM canonical Phase-1 content lifecycle",
      capabilityKey: "content-production",
      accountableSeatKey: "creator-operations-coordinator-i",
      workflowKey: "afm-content-lifecycle",
      purpose: "Turn one real source moment into a governed AFM publication and attributable learning record.",
      intendedOutcome: "A correctly branded, rights-complete, founder-approved publication with receipts, measurement and reusable learning disposition.",
      triggerCondition: "A real source moment is selected and its source lineage can be preserved.",
      procedureSteps: [
        "Select and record the real source moment.",
        "Draft and approve a content brief with proof, rights and confidentiality constraints.",
        "Produce, review and revise a versioned asset.",
        "Obtain founder approval and publish only through the exact authorized BRAND-AFM account.",
        "Capture the provider receipt, measurement window and learning disposition.",
      ],
      requiredInputs: ["Real source record", "Brand rules", "Rights and confidentiality context", "Exact channel authority"],
      requiredOutputs: ["Approved brief", "Versioned asset", "Publication receipt", "Measurement record", "Learning disposition"],
      approvalGates: ["Brief approval", "Rights and confidentiality review", "Founder final-publication approval"],
      prohibitedActions: ["Invent a claim", "Publish through an unverified account", "Use unapproved likeness or voice", "Infer outcome from a draft or schedule"],
      evidenceRequirements: ["Source lineage", "Attributable approvals", "Exact account and asset identity", "Provider receipt", "Defined-window measurement"],
      qualityCriteria: ["Truthful", "Brand-aligned", "Rights-complete", "Technically correct", "Attributable"],
      failurePaths: ["Stop or suspend publication", "Preserve versions and receipts", "Assign one exception owner", "Escalate to the AFM CEO Agent and founder"],
      terminalCriteria: ["Publication and receipt recorded, or explicit rejection/takedown recorded", "Measurement and learning disposition recorded when applicable"],
      acceptanceTests: ["Wrong-account attempt is denied", "Missing rights evidence blocks publication", "No actual metric value exists without source evidence"],
      sourceRef: AFM_REFERENCE_PACKAGE.sources.contentLifecycle,
    },
    {
      processKey: "afm-empyrean-production-service",
      name: "AFM to Empyrean production request and acceptance",
      capabilityKey: "shared-service-procurement",
      accountableSeatKey: "company-ceo",
      workflowKey: "afm-empyrean-production-service",
      purpose: "Request and accept bounded production work from Empyrean without creating a cross-company reporting line.",
      intendedOutcome: "A scoped deliverable returns with evidence and is explicitly accepted, rejected or sent through bounded rework by AFM.",
      triggerCondition: "AFM identifies production work suitable for the governed Empyrean shared-service boundary.",
      procedureSteps: [
        "AFM creates a service Work Packet with scope, beneficiary, inputs, acceptance criteria, due date and capacity assumptions.",
        "AFM authority approves the request.",
        "Empyrean independently accepts, rejects or requests clarification inside its own company context.",
        "Empyrean executes within its own authority and returns the deliverable and evidence.",
        "AFM accepts, rejects or requests bounded rework against the original criteria.",
        "AFM records capacity, cost and outcome attribution without changing either company's hierarchy.",
      ],
      requiredInputs: ["Approved AFM service request", "Production inputs", "Acceptance criteria", "Due date", "Cost and capacity assumptions"],
      requiredOutputs: ["Empyrean response", "Versioned deliverable", "Production evidence", "AFM acceptance disposition", "Cost and capacity record"],
      approvalGates: ["AFM request approval", "Empyrean independent acceptance", "AFM delivery acceptance"],
      prohibitedActions: ["Directly command an Empyrean agent", "Create a cross-company supervisor edge", "Infer acceptance from delivery", "Silently reconstruct missing evidence"],
      evidenceRequirements: ["Approved request", "Provider acceptance or rejection", "Deliverable lineage", "AFM acceptance or bounded rework decision"],
      qualityCriteria: ["Bounded scope", "Independent provider authority", "Explicit acceptance", "Preserved company attribution"],
      failurePaths: ["Reject incomplete handoff", "Return an explicit defect list", "Preserve versions", "Keep AFM queue state local"],
      terminalCriteria: ["Accepted, rejected or explicitly cancelled with evidence", "No unresolved cross-company authority ambiguity"],
      acceptanceTests: ["A direct cross-company command is denied", "A missing provider acceptance blocks execution", "AFM can reject against the original criteria"],
      sourceRef: AFM_REFERENCE_PACKAGE.sources.empyreanServiceSop,
    },
  ],
  assets: [{
    assetKey: "BRAND-AFM",
    name: "AFM Brand",
    assetType: "brand_asset",
    lifecycleState: "active",
    custodianSeatKey: "company-ceo",
    ownerOrganizationKey: "ORG-AFM",
    operatorOrganizationKey: "ORG-AFM",
    dataClassification: "internal",
    rightsUsageLicense: "AFM-owned Brand identity; use remains subject to founder, rights, likeness, voice and publication authority.",
    replacementPortabilityNotes: "The Brand asset persists independently of any channel or provider; channel accounts remain separate bindings.",
    sourceRef: AFM_REFERENCE_PACKAGE.sources.brandChannel,
  }],
  stakeholders: [
    { stakeholderKey: "ORG-AFM", name: "AFM", partyType: "organization", state: "active", ownerSeatKey: "company-ceo", identityReference: "eos-org:ORG-AFM", relationshipRole: "service beneficiary and Brand owner" },
    { stakeholderKey: "ORG-EMPYREAN-STUDIOS", name: "Empyrean Studios", partyType: "vendor_provider", state: "active", ownerSeatKey: "company-ceo", identityReference: "eos-org:ORG-EMPYREAN-STUDIOS", relationshipRole: "governed shared-service provider" },
  ],
  relationships: [{
    relationshipKey: "afm-empyrean-shared-service",
    stakeholderKey: "ORG-EMPYREAN-STUDIOS",
    relationshipType: "vendor_provider",
    title: "AFM to Empyrean governed production service",
    state: "active",
    ownerSeatKey: "company-ceo",
    needConstraint: "Production capacity is requested only through an approved AFM service Work Packet; provider acceptance remains independent.",
    fitHypothesis: "Empyrean can provide production services while AFM retains beneficiary, Brand, publication and outcome authority.",
    nextBestAction: "Run one controlled AFM to Empyrean request, acceptance, delivery and AFM disposition cycle.",
  }],
  additionalWorkPackets: [{
    key: "request-empyrean-production-service",
    title: "Request Empyrean production service",
    accountableSeatKey: "company-ceo",
    capabilityKey: "shared-service-procurement",
    processKey: "afm-empyrean-production-service",
    objective: "Create and approve a bounded AFM service request that Empyrean may independently accept, reject or clarify.",
    evidenceRequirements: ["AFM approval", "Explicit Empyrean response", "Versioned deliverable and evidence", "AFM acceptance, rejection or bounded rework disposition"],
    expectedOutput: "A governed service request and evidence-bearing disposition without a cross-company reporting edge.",
    acceptanceCriteria: "Scope, beneficiary, priority, inputs, acceptance criteria, due date and cost/capacity are explicit; both company decisions are attributable.",
    constraintsPolicies: "No direct agent command, hidden reconstruction, inferred acceptance or transfer of AFM Brand/publication authority.",
    failureEscalationCompensation: "Reject or clarify the handoff, preserve state and return an explicit defect list to the accountable company authorities.",
    sourceLineage: AFM_REFERENCE_PACKAGE.sources.empyreanServiceSop,
    outputArtifactKeys: ["service-request", "provider-response", "deliverable", "acceptance-disposition", "capacity-cost-record"],
  }],
};

export const AFM_SOURCE_BINDINGS: CompanySourceBinding[] = [
  createNotionSourceBinding({ sourceKey: "registry", orgKey: "ORG-AFM", pageClass: "registry", sourceRef: AFM_REFERENCE_PACKAGE.sources.registry, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 1, maxAgeDays: 45, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "runtime", orgKey: "ORG-AFM", pageClass: "runtime", sourceRef: AFM_REFERENCE_PACKAGE.sources.runtime, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 2, maxAgeDays: 45, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "accountability-chart", orgKey: "ORG-AFM", pageClass: "accountability_chart", sourceRef: AFM_REFERENCE_PACKAGE.sources.accountabilityChart, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 3, maxAgeDays: 60, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "content-lifecycle", orgKey: "ORG-AFM", pageClass: "workflow", sourceRef: AFM_REFERENCE_PACKAGE.sources.contentLifecycle, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 4, maxAgeDays: 60, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "scorecards", orgKey: "ORG-AFM", pageClass: "scorecard", sourceRef: AFM_REFERENCE_PACKAGE.sources.scorecards, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 5, maxAgeDays: 60, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "brand-channel", orgKey: "ORG-AFM", pageClass: "supporting", sourceRef: AFM_REFERENCE_PACKAGE.sources.brandChannel, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 6, maxAgeDays: 60, classification: "internal", importAuthority: "reference_only" }),
  createNotionSourceBinding({ sourceKey: "empyrean-service-sop", orgKey: "ORG-AFM", pageClass: "workflow", sourceRef: AFM_REFERENCE_PACKAGE.sources.empyreanServiceSop, expectedRevision: AFM_REFERENCE_PACKAGE.version, precedence: 7, maxAgeDays: 60, classification: "internal", importAuthority: "reference_only" }),
];

export const compileAfmReferenceInstance = declarativeCompanyPackageMaterializer(AFM_COMPANY_PACKAGE, AFM_RUNTIME_BINDINGS);
