# Secret references only. Create the EntrepreneurOS/Production item in 1Password
# before public promotion; never replace these references with plaintext values.
DATABASE_URL=op://EntrepreneurOS/Production/DATABASE_URL
MIGRATION_DATABASE_URL=op://EntrepreneurOS/Production/MIGRATION_DATABASE_URL
SESSION_SECRET=op://EntrepreneurOS/Production/SESSION_SECRET
ANTHROPIC_API_KEY=op://EntrepreneurOS/Production/ANTHROPIC_API_KEY
VITE_CLERK_PUBLISHABLE_KEY=op://EntrepreneurOS/Production/VITE_CLERK_PUBLISHABLE_KEY
CLERK_PUBLISHABLE_KEY=op://EntrepreneurOS/Production/CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY=op://EntrepreneurOS/Production/CLERK_SECRET_KEY
EOS_CREDENTIAL_ENCRYPTION_KEY=op://EntrepreneurOS/Production/EOS_CREDENTIAL_ENCRYPTION_KEY
VITE_POSTHOG_API_KEY=op://EntrepreneurOS/Production/VITE_POSTHOG_API_KEY
POSTHOG_API_KEY=op://EntrepreneurOS/Production/VITE_POSTHOG_API_KEY
GOOGLE_CLIENT_ID=op://EntrepreneurOS/Production/GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=op://EntrepreneurOS/Production/GOOGLE_CLIENT_SECRET
GOOGLE_REDIRECT_URI=https://entrepreneuros.net/api/auth/google/callback
NOTION_CLIENT_ID=op://EntrepreneurOS/Production/NOTION_CLIENT_ID
NOTION_CLIENT_SECRET=op://EntrepreneurOS/Production/NOTION_CLIENT_SECRET
NOTION_REDIRECT_URI=https://entrepreneuros.net/api/auth/notion/callback
EOS_PUBLIC_ORIGIN=https://entrepreneuros.net
EOS_PRODUCTION_ENVIRONMENT_SUBJECT=environment:entrepreneuros-production
EOS_PRODUCTION_RELEASE_BRANCH=feature/company-system
EOS_GITHUB_REPOSITORY=antonyfmunoz/EntrepreneurOS
# A fresh Clerk session JWT is requested through a concealed prompt immediately
# before authenticated smoke. For noninteractive runs only, inject it into the
# current process; never store the short-lived token in 1Password or this file.
EOS_PRODUCTION_COMPANY_ID=op://EntrepreneurOS/Production/EOS_PRODUCTION_COMPANY_ID
EOS_PRODUCTION_FORBIDDEN_COMPANY_ID=op://EntrepreneurOS/Production/EOS_PRODUCTION_FORBIDDEN_COMPANY_ID
# Local secret-free JSON receipt pack; never stage this path into Fly.
EOS_PRODUCTION_PROMOTION_EVIDENCE_PATH=.tmp/eos-production-promotion-evidence.json
EOS_ALERT_WEBHOOK_URL=op://EntrepreneurOS/Production/EOS_ALERT_WEBHOOK_URL
EOS_ALERT_WEBHOOK_SECRET=op://EntrepreneurOS/Production/EOS_ALERT_WEBHOOK_SECRET
EOS_RECOVERY_PROVIDER_WEBHOOK_SECRETS=op://EntrepreneurOS/Production/EOS_RECOVERY_PROVIDER_WEBHOOK_SECRETS
# Keep disabled until the exact merchant, credentials, prices, and receipts are
# verified and live execution is explicitly approved after the account cutover.
EOS_RECOVERY_PROVIDER_EFFECTS_ENABLED=false
EOS_INTEGRATION_PROVIDER_EFFECTS_ENABLED=false
EOS_PROVIDER_INGRESS_WORKER_INTERVAL_MS=60000
EOS_INTEGRATION_DISPATCH_RECOVERY_AFTER_MS=300000
EOS_INTEGRATION_DISPATCH_RECOVERY_INTERVAL_MS=60000
EOS_RECOVERY_PROVIDER_EXECUTION_CREDENTIALS=op://EntrepreneurOS/Production/EOS_RECOVERY_PROVIDER_EXECUTION_CREDENTIALS
EOS_PLATFORM_ADMIN_USER_IDS=op://EntrepreneurOS/Production/EOS_PLATFORM_ADMIN_USER_IDS
EOS_DATABASE_VENDOR_NAME=op://EntrepreneurOS/Production/EOS_DATABASE_VENDOR_NAME
EOS_DNS_VENDOR_NAME=op://EntrepreneurOS/Production/EOS_DNS_VENDOR_NAME
EOS_SECRET_VAULT_VENDOR_NAME=op://EntrepreneurOS/Production/EOS_SECRET_VAULT_VENDOR_NAME
EOS_ARTIFACT_STORAGE_PROVIDER=s3
EOS_ARTIFACT_S3_BUCKET=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_BUCKET
EOS_ARTIFACT_S3_REGION=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_REGION
EOS_ARTIFACT_S3_ENDPOINT=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_ENDPOINT
EOS_ARTIFACT_S3_FORCE_PATH_STYLE=false
EOS_ARTIFACT_S3_PREFIX=native-esign
EOS_ARTIFACT_S3_SSE_CUSTOMER_KEY=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_SSE_CUSTOMER_KEY
EOS_ARTIFACT_S3_ACCESS_KEY_ID=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_ACCESS_KEY_ID
EOS_ARTIFACT_S3_SECRET_ACCESS_KEY=op://EntrepreneurOS/Production/EOS_ARTIFACT_S3_SECRET_ACCESS_KEY
EOS_ARTIFACT_BACKUP_STORAGE_PROVIDER=s3
EOS_ARTIFACT_BACKUP_S3_BUCKET=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_BUCKET
EOS_ARTIFACT_BACKUP_S3_REGION=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_REGION
EOS_ARTIFACT_BACKUP_S3_ENDPOINT=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_ENDPOINT
EOS_ARTIFACT_BACKUP_S3_FORCE_PATH_STYLE=false
EOS_ARTIFACT_BACKUP_S3_PREFIX=native-esign
EOS_ARTIFACT_BACKUP_S3_SSE_CUSTOMER_KEY=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_SSE_CUSTOMER_KEY
EOS_ARTIFACT_BACKUP_S3_ACCESS_KEY_ID=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_ACCESS_KEY_ID
EOS_ARTIFACT_BACKUP_S3_SECRET_ACCESS_KEY=op://EntrepreneurOS/Production/EOS_ARTIFACT_BACKUP_S3_SECRET_ACCESS_KEY
# Trusted-source mode blocks new binary uploads and leaves the bundled scanner
# dormant at the existing 512 MB allocation. Re-enable only after qualification.
EOS_UNTRUSTED_UPLOADS_ENABLED=false
EOS_CANDIDATE_STT_ENABLED=false
EOS_CANDIDATE_STT_MODEL=gpt-4o-mini-transcribe
# When EOS_CANDIDATE_STT_ENABLED=true, add:
# OPENAI_API_KEY=op://EntrepreneurOS/Production/OPENAI_API_KEY
EOS_ACCOUNT_DELETION_ENABLED=true
EOS_LEGAL_ENFORCEMENT=true
EOS_PUBLIC_PAID_SAAS=false
