import { hkdfSync, randomBytes, webcrypto } from "node:crypto";
import { storage } from "../storage";
import { credentialEncryptionConfigured, decryptCredential, encryptCredential } from "../security/credential-encryption";

const TOKEN_URL = "https://services.leadconnectorhq.com/oauth/token";
const API_BASE = "https://services.leadconnectorhq.com";
const API_VERSION = "2021-07-28";
const REQUIRED_SCOPES = ["contacts.readonly", "contacts.write", "opportunities.readonly", "opportunities.write"] as const;

type OAuthState = { userId: string; expiresAt: number; nonce: string; returnTo: string };
type TokenResponse = { access_token?: string; refresh_token?: string; token_type?: string; expires_in?: number; scope?: string; userType?: string; user_type?: string; companyId?: string; company_id?: string; locationId?: string; location_id?: string; userId?: string; user_id?: string };
type Metadata = { locationId?: string; companyId?: string; userId?: string; userType?: string; grantedScopes?: string[] };

function safeReturnTo(value?: string) { return value && (/^\/company\/[1-9]\d*(?:#systems)?$/.test(value) || /^\/portfolios(?:\/[1-9]\d*)?$/.test(value)) ? value : "/portfolios"; }
function stateSecret() { const value = process.env.SESSION_SECRET?.trim(); if (!value || value.length < 32) throw new Error("SESSION_SECRET must be at least 32 characters for GoHighLevel OAuth state signing."); return value; }
async function stateSigningKey(): Promise<CryptoKey> { const material = Buffer.from(hkdfSync("sha256", stateSecret(), "entrepreneuros/gohighlevel-oauth-state/v1", "authorization-response-integrity", 32)); return webcrypto.subtle.importKey("raw", material, { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]); }
function stateMessage(payload: string) { return new TextEncoder().encode(`gohighlevel:${payload}`); }
async function signState(payload: string) { return Buffer.from(await webcrypto.subtle.sign("HMAC", await stateSigningKey(), stateMessage(payload))).toString("base64url"); }
function configuration() {
  const clientId = process.env.GOHIGHLEVEL_CLIENT_ID?.trim();
  const clientSecret = process.env.GOHIGHLEVEL_CLIENT_SECRET?.trim();
  const installationUrl = process.env.GOHIGHLEVEL_INSTALLATION_URL?.trim();
  const redirectUri = process.env.GOHIGHLEVEL_REDIRECT_URI?.trim() || "http://localhost:5000/api/auth/gohighlevel/callback";
  if (!clientId || !clientSecret || !installationUrl) throw new Error("GoHighLevel OAuth credentials or installation URL are not configured.");
  let parsed: URL; try { parsed = new URL(installationUrl); } catch { throw new Error("GOHIGHLEVEL_INSTALLATION_URL must be a valid HTTPS URL."); }
  if (parsed.protocol !== "https:") throw new Error("GOHIGHLEVEL_INSTALLATION_URL must use HTTPS.");
  return { clientId, clientSecret, installationUrl: parsed, redirectUri } as const;
}
function expiry(seconds?: number) { return typeof seconds === "number" && Number.isFinite(seconds) ? new Date(Date.now() + Math.max(1, seconds) * 1000) : undefined; }
function scopes(value?: string) { return [...new Set((value || "").split(/[\s,]+/).map((item) => item.trim()).filter(Boolean))]; }
function metadata(value: unknown): Metadata { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; const input = value as Record<string, unknown>; return { locationId: typeof input.locationId === "string" ? input.locationId : undefined, companyId: typeof input.companyId === "string" ? input.companyId : undefined, userId: typeof input.userId === "string" ? input.userId : undefined, userType: typeof input.userType === "string" ? input.userType : undefined, grantedScopes: Array.isArray(input.grantedScopes) ? input.grantedScopes.filter((item): item is string => typeof item === "string") : [] }; }
function nextMetadata(result: TokenResponse): Metadata { return { locationId: result.locationId || result.location_id, companyId: result.companyId || result.company_id, userId: result.userId || result.user_id, userType: result.userType || result.user_type, grantedScopes: scopes(result.scope) }; }

async function tokenRequest(body: Record<string, string>): Promise<TokenResponse> {
  const { clientId, clientSecret, redirectUri } = configuration(); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10_000);
  try { const response = await fetch(TOKEN_URL, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ client_id: clientId, client_secret: clientSecret, redirect_uri: redirectUri, ...body }), signal: controller.signal }); if (!response.ok) throw new Error(`GoHighLevel authorization failed with ${response.status}.`); const result = await response.json() as TokenResponse; if (!result.access_token) throw new Error("GoHighLevel authorization returned no access token."); return result; } finally { clearTimeout(timeout); }
}

export const GOHIGHLEVEL_TOOLS = ["gohighlevel.location.verify", "gohighlevel.contact.lookup", "gohighlevel.contact.upsert", "gohighlevel.opportunity.search", "gohighlevel.opportunity.create"] as const;
export const GOHIGHLEVEL_REQUIRED_SCOPES = REQUIRED_SCOPES;
export async function createOAuthState(userId: string, now = Date.now(), returnTo = "/portfolios") { const payload = Buffer.from(JSON.stringify({ userId, expiresAt: now + 10 * 60_000, nonce: randomBytes(16).toString("base64url"), returnTo: safeReturnTo(returnTo) })).toString("base64url"); return `${payload}.${await signState(payload)}`; }
export async function readOAuthState(state: string, userId: string, now = Date.now()): Promise<OAuthState | null> { try { const [payload, signature] = state.split("."); if (!payload || !signature || !(await webcrypto.subtle.verify("HMAC", await stateSigningKey(), Buffer.from(signature, "base64url"), stateMessage(payload)))) return null; const decoded = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as Partial<OAuthState>; if (decoded.userId !== userId || typeof decoded.expiresAt !== "number" || decoded.expiresAt < now) return null; return { userId, expiresAt: decoded.expiresAt, nonce: typeof decoded.nonce === "string" ? decoded.nonce : "", returnTo: safeReturnTo(decoded.returnTo) }; } catch { return null; } }
export function isConfigured() { try { stateSecret(); configuration(); return credentialEncryptionConfigured(); } catch { return false; } }
export async function getAuthUrl(userId: string, returnTo?: string) { const { installationUrl, redirectUri } = configuration(); const url = new URL(installationUrl); url.searchParams.set("redirect_uri", redirectUri); url.searchParams.set("state", await createOAuthState(userId, Date.now(), returnTo)); return url.toString(); }
export async function exchangeCode(code: string) { if (!code.trim() || code.length > 10_000) throw new Error("GoHighLevel authorization returned an invalid authorization code."); const result = await tokenRequest({ grant_type: "authorization_code", code, user_type: "Location" }); const next = nextMetadata(result); if (!next.locationId) throw new Error("GoHighLevel did not return a location identifier. Install the private app into the intended sub-account."); return { accessToken: result.access_token!, refreshToken: result.refresh_token, tokenType: result.token_type || "Bearer", expiresAt: expiry(result.expires_in), scope: result.scope || "", metadata: next }; }
async function refreshAccessToken(userId: string) { const token = await storage.getOauthToken(userId, "gohighlevel"); if (!token?.refreshToken) throw new Error("GoHighLevel authorization expired. Reconnect the company location in Systems."); const result = await tokenRequest({ grant_type: "refresh_token", refresh_token: decryptCredential(token.refreshToken), user_type: "Location" }); const next = { ...metadata(token.metadata), ...nextMetadata(result), grantedScopes: scopes(result.scope || token.scope || "") }; await storage.upsertOauthToken({ userId, provider: "gohighlevel", accessToken: encryptCredential(result.access_token!), refreshToken: result.refresh_token ? encryptCredential(result.refresh_token) : token.refreshToken, tokenType: result.token_type || token.tokenType || "Bearer", expiresAt: expiry(result.expires_in), scope: result.scope || token.scope || "", metadata: next }); return result.access_token!; }
async function accessToken(userId: string) { const token = await storage.getOauthToken(userId, "gohighlevel"); if (!token) throw new Error("GoHighLevel is not connected. Connect the CRM location first."); if (token.expiresAt && new Date(token.expiresAt) <= new Date()) return refreshAccessToken(userId); return decryptCredential(token.accessToken); }
async function request(userId: string, path: string, init: RequestInit = {}) { const call = async (token: string) => { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10_000); try { return await fetch(`${API_BASE}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, Accept: "application/json", Version: API_VERSION, ...(init.body ? { "Content-Type": "application/json" } : {}), ...(init.headers || {}) }, signal: controller.signal }); } finally { clearTimeout(timeout); } }; const first = await call(await accessToken(userId)); return first.status === 401 ? call(await refreshAccessToken(userId)) : first; }
export async function connectionSummary(userId: string) { if (!isConfigured()) return { configured: false, connected: false, location: null, grantedScopes: [] as string[] }; const token = await storage.getOauthToken(userId, "gohighlevel"); if (!token) return { configured: true, connected: false, location: null, grantedScopes: [] as string[] }; try { decryptCredential(token.accessToken); const current = metadata(token.metadata); return { configured: true, connected: Boolean(current.locationId), location: current.locationId ? current : null, grantedScopes: current.grantedScopes || scopes(token.scope || "") }; } catch { return { configured: true, connected: false, location: null, grantedScopes: [] as string[] }; } }
export async function verifyConnection(userId: string) { const summary = await connectionSummary(userId); if (!summary.connected || !summary.location?.locationId) return { ...summary, healthy: false }; try { const response = await request(userId, `/opportunities/search?locationId=${encodeURIComponent(summary.location.locationId)}&status=all&limit=1`); if (!response.ok) return { ...summary, healthy: false }; return { ...summary, healthy: true }; } catch { return { ...summary, healthy: false }; } }
function ensureLocation(result: Awaited<ReturnType<typeof verifyConnection>>) { if (!result.healthy || !result.location?.locationId) throw new Error("GoHighLevel location authorization is unavailable or unhealthy."); return result.location.locationId; }
export async function lookupContact(userId: string, input: { email?: string; phone?: string; limit?: number }) { const locationId = ensureLocation(await verifyConnection(userId)); const key = input.email ? "email" : "phone"; const value = input.email || input.phone; if (!value) throw new Error("Provide one contact email or phone number."); const response = await request(userId, `/contacts/lookup?locationId=${encodeURIComponent(locationId)}&${key}=${encodeURIComponent(value)}&limit=${Math.min(20, Math.max(1, Math.trunc(input.limit || 10)))}`); if (!response.ok) throw new Error(`GoHighLevel contact lookup failed with ${response.status}.`); const body = await response.json() as { contacts?: Array<Record<string, unknown>> }; return { locationId, contacts: (body.contacts || []).map(contactProjection) }; }
function contactProjection(value: Record<string, unknown>) { return { id: typeof value.id === "string" ? value.id : "", name: typeof value.name === "string" ? value.name : null, firstName: typeof value.firstName === "string" ? value.firstName : null, lastName: typeof value.lastName === "string" ? value.lastName : null, email: typeof value.email === "string" ? value.email : null, phone: typeof value.phone === "string" ? value.phone : null, locationId: typeof value.locationId === "string" ? value.locationId : null }; }
export async function upsertContact(userId: string, input: { email?: string; phone?: string; firstName?: string; lastName?: string; name?: string; source?: string; tags?: string[] }) { const locationId = ensureLocation(await verifyConnection(userId)); const response = await request(userId, "/contacts/upsert", { method: "POST", body: JSON.stringify({ locationId, email: input.email, phone: input.phone, firstName: input.firstName, lastName: input.lastName, name: input.name, source: input.source, tags: input.tags }) }); if (!response.ok) throw new Error(`GoHighLevel contact upsert failed with ${response.status}.`); const body = await response.json() as { contact?: Record<string, unknown> }; if (!body.contact?.id) throw new Error("GoHighLevel contact upsert returned no durable contact reference."); return { locationId, contact: contactProjection(body.contact) }; }
export async function searchOpportunities(userId: string, input: { query?: string; pipelineId?: string; pipelineStageId?: string; status?: string; limit?: number }) { const locationId = ensureLocation(await verifyConnection(userId)); const params = new URLSearchParams({ locationId, status: input.status || "all", limit: String(Math.min(100, Math.max(1, Math.trunc(input.limit || 25)))) }); if (input.query) params.set("q", input.query); if (input.pipelineId) params.set("pipelineId", input.pipelineId); if (input.pipelineStageId) params.set("pipelineStageId", input.pipelineStageId); const response = await request(userId, `/opportunities/search?${params}`); if (!response.ok) throw new Error(`GoHighLevel opportunity search failed with ${response.status}.`); const body = await response.json() as { opportunities?: Array<Record<string, unknown>> }; return { locationId, opportunities: (body.opportunities || []).map(opportunityProjection) }; }
function opportunityProjection(value: Record<string, unknown>) { return { id: typeof value.id === "string" ? value.id : "", name: typeof value.name === "string" ? value.name : null, status: typeof value.status === "string" ? value.status : null, pipelineId: typeof value.pipelineId === "string" ? value.pipelineId : null, pipelineStageId: typeof value.pipelineStageId === "string" ? value.pipelineStageId : null, contactId: typeof value.contactId === "string" ? value.contactId : null, monetaryValue: typeof value.monetaryValue === "number" ? value.monetaryValue : null }; }
export async function createOpportunity(userId: string, input: { pipelineId: string; pipelineStageId?: string; contactId: string; name: string; status: "open" | "won" | "lost" | "abandoned"; monetaryValue?: number; assignedTo?: string }) { const locationId = ensureLocation(await verifyConnection(userId)); const response = await request(userId, "/opportunities/", { method: "POST", body: JSON.stringify({ locationId, ...input }) }); if (!response.ok) throw new Error(`GoHighLevel opportunity creation failed with ${response.status}.`); const body = await response.json() as { opportunity?: Record<string, unknown> }; if (!body.opportunity?.id) throw new Error("GoHighLevel opportunity creation returned no durable opportunity reference."); return { locationId, opportunity: opportunityProjection(body.opportunity) }; }
export async function disconnect(userId: string) { await storage.deleteOauthToken(userId, "gohighlevel"); return { success: true, providerRevoked: false }; }
