CREATE TABLE IF NOT EXISTS "eos_objectives" (
  "id" text PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,
  "portfolio_id" integer REFERENCES "portfolios"("id") ON DELETE SET NULL,
  "objective_key" text NOT NULL,
  "record_type" text NOT NULL,
  "title" text NOT NULL,
  "statement" text NOT NULL,
  "state" text DEFAULT 'proposed' NOT NULL,
  "priority" text DEFAULT 'medium' NOT NULL,
  "owner_seat_id" text NOT NULL REFERENCES "eos_seats"("id") ON DELETE RESTRICT,
  "parent_objective_id" text REFERENCES "eos_objectives"("id") ON DELETE SET NULL,
  "scope_boundary" text DEFAULT '' NOT NULL,
  "rationale_theory" text DEFAULT '' NOT NULL,
  "success_exit_criteria" text DEFAULT '' NOT NULL,
  "time_horizon" text DEFAULT '' NOT NULL,
  "work_packet_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "metric_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "evidence_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "decision_policy_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "source_authority" text DEFAULT 'native_eos' NOT NULL,
  "classification" text DEFAULT 'internal' NOT NULL,
  "schema_version" text DEFAULT 'objective-constraint-v1.0' NOT NULL,
  "target_review_at" timestamptz,
  "valid_from" timestamptz DEFAULT now() NOT NULL,
  "recorded_by_user_id" text NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT "eos_objectives_type_check" CHECK ("record_type" IN ('objective', 'constraint', 'mandate', 'hypothesis', 'success_condition', 'guardrail')),
  CONSTRAINT "eos_objectives_state_check" CHECK ("state" IN ('proposed', 'active', 'at_risk', 'blocked', 'achieved', 'failed', 'superseded', 'archived')),
  CONSTRAINT "eos_objectives_priority_check" CHECK ("priority" IN ('critical', 'high', 'medium', 'low')),
  CONSTRAINT "eos_objectives_classification_check" CHECK ("classification" IN ('public', 'internal', 'confidential', 'restricted')),
  CONSTRAINT "eos_objectives_source_authority_check" CHECK ("source_authority" IN ('native_eos', 'notion_runtime', 'external_authoritative', 'reconciled'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "eos_objectives_company_key_idx" ON "eos_objectives" ("company_id", "objective_key");
CREATE INDEX IF NOT EXISTS "eos_objectives_company_state_priority_idx" ON "eos_objectives" ("company_id", "state", "priority");
CREATE INDEX IF NOT EXISTS "eos_objectives_owner_state_idx" ON "eos_objectives" ("owner_seat_id", "state");

CREATE TABLE IF NOT EXISTS "eos_metrics_outcomes" (
  "id" text PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,
  "portfolio_id" integer REFERENCES "portfolios"("id") ON DELETE SET NULL,
  "metric_key" text NOT NULL,
  "record_type" text NOT NULL,
  "title" text NOT NULL,
  "state" text DEFAULT 'proposed' NOT NULL,
  "owner_seat_id" text NOT NULL REFERENCES "eos_seats"("id") ON DELETE RESTRICT,
  "objective_id" text REFERENCES "eos_objectives"("id") ON DELETE SET NULL,
  "subject_type" text DEFAULT 'organization' NOT NULL,
  "subject_key" text DEFAULT '' NOT NULL,
  "definition_formula" text DEFAULT '' NOT NULL,
  "unit_currency" text DEFAULT '' NOT NULL,
  "threshold_direction" text DEFAULT '' NOT NULL,
  "target_value" numeric(24,6),
  "actual_value" numeric(24,6),
  "forecast_value" numeric(24,6),
  "time_grain_period" text DEFAULT '' NOT NULL,
  "verifier_confidence" text DEFAULT '' NOT NULL,
  "attribution_limitations" text DEFAULT '' NOT NULL,
  "evidence_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "source_authority" text DEFAULT 'native_eos' NOT NULL,
  "classification" text DEFAULT 'internal' NOT NULL,
  "schema_version" text DEFAULT 'metric-outcome-v1.0' NOT NULL,
  "as_of" timestamptz,
  "valid_from" timestamptz DEFAULT now() NOT NULL,
  "valid_until" timestamptz,
  "recorded_by_user_id" text NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT "eos_metrics_outcomes_type_check" CHECK ("record_type" IN ('metric_definition', 'measurement', 'target', 'forecast', 'benchmark', 'outcome', 'impact')),
  CONSTRAINT "eos_metrics_outcomes_state_check" CHECK ("state" IN ('proposed', 'defined', 'active', 'under_review', 'verified', 'contested', 'superseded', 'retired')),
  CONSTRAINT "eos_metrics_outcomes_classification_check" CHECK ("classification" IN ('public', 'internal', 'confidential', 'restricted')),
  CONSTRAINT "eos_metrics_outcomes_valid_window_check" CHECK ("valid_until" IS NULL OR "valid_until" > "valid_from"),
  CONSTRAINT "eos_metrics_outcomes_source_authority_check" CHECK ("source_authority" IN ('native_eos', 'notion_runtime', 'external_authoritative', 'reconciled'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "eos_metrics_outcomes_company_key_idx" ON "eos_metrics_outcomes" ("company_id", "metric_key");
CREATE INDEX IF NOT EXISTS "eos_metrics_outcomes_company_state_idx" ON "eos_metrics_outcomes" ("company_id", "state");
CREATE INDEX IF NOT EXISTS "eos_metrics_outcomes_owner_state_idx" ON "eos_metrics_outcomes" ("owner_seat_id", "state");

CREATE TABLE IF NOT EXISTS "eos_risks_controls" (
  "id" text PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,
  "portfolio_id" integer REFERENCES "portfolios"("id") ON DELETE SET NULL,
  "risk_control_key" text NOT NULL,
  "record_type" text NOT NULL,
  "title" text NOT NULL,
  "state" text DEFAULT 'identified' NOT NULL,
  "owner_seat_id" text NOT NULL REFERENCES "eos_seats"("id") ON DELETE RESTRICT,
  "capability_process_asset_key" text DEFAULT '' NOT NULL,
  "description_cause_event_impact" text NOT NULL,
  "inherent_assessment" text DEFAULT '' NOT NULL,
  "residual_assessment" text DEFAULT '' NOT NULL,
  "appetite_tolerance_materiality" text DEFAULT '' NOT NULL,
  "treatment_control" text DEFAULT '' NOT NULL,
  "source_requirement" text DEFAULT '' NOT NULL,
  "jurisdiction_regime" text DEFAULT '' NOT NULL,
  "evidence_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "policy_decision_work_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "exception_incident_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "insurance_transfer" text DEFAULT '' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "source_authority" text DEFAULT 'native_eos' NOT NULL,
  "classification" text DEFAULT 'internal' NOT NULL,
  "schema_version" text DEFAULT 'risk-obligation-control-v1.0' NOT NULL,
  "due_review_at" timestamptz,
  "valid_from" timestamptz DEFAULT now() NOT NULL,
  "valid_until" timestamptz,
  "recorded_by_user_id" text NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT "eos_risks_controls_type_check" CHECK ("record_type" IN ('risk', 'obligation', 'control', 'incident', 'finding', 'remediation', 'insurance_transfer')),
  CONSTRAINT "eos_risks_controls_state_check" CHECK ("state" IN ('identified', 'under_assessment', 'applicable_active', 'assigned', 'treating_in_progress', 'monitoring', 'accepted', 'overdue_breached', 'remediating', 'satisfied_closed', 'superseded')),
  CONSTRAINT "eos_risks_controls_classification_check" CHECK ("classification" IN ('public', 'internal', 'confidential', 'restricted')),
  CONSTRAINT "eos_risks_controls_valid_window_check" CHECK ("valid_until" IS NULL OR "valid_until" > "valid_from"),
  CONSTRAINT "eos_risks_controls_source_authority_check" CHECK ("source_authority" IN ('native_eos', 'notion_runtime', 'external_authoritative', 'reconciled'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "eos_risks_controls_company_key_idx" ON "eos_risks_controls" ("company_id", "risk_control_key");
CREATE INDEX IF NOT EXISTS "eos_risks_controls_company_state_idx" ON "eos_risks_controls" ("company_id", "state");
CREATE INDEX IF NOT EXISTS "eos_risks_controls_owner_state_idx" ON "eos_risks_controls" ("owner_seat_id", "state");
