import { useMemo, useState } from "react";
import { Link, useParams } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowRight, ArrowUp, BriefcaseBusiness, CircleDot, GitFork, Network, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, Workflow } from "lucide-react";
import UniversalLayout, { type UniversalLayoutLeftRailItem } from "@/components/layout/universal-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest } from "@/lib/queryClient";

type Json = Record<string, any>;
type Step = { id: string; title: string; instructions: string; completionCriteria: string };
type Draft = { name: string; capabilityId: string; purpose: string; outcome: string; trigger: string; steps: Step[]; inputs: string; tools: string; outputs: string; evidence: string; approvals: string; recovery: string; terminal: string; tests: string };
const newStep = (): Step => ({ id: crypto.randomUUID(), title: "", instructions: "", completionCriteria: "" });
const blank = (): Draft => ({ name: "", capabilityId: "", purpose: "", outcome: "", trigger: "", steps: [newStep()], inputs: "", tools: "", outputs: "", evidence: "", approvals: "", recovery: "", terminal: "", tests: "" });
const lines = (v: string) => v.split("\n").map((x) => x.trim()).filter(Boolean);
const text = (v: unknown) => Array.isArray(v) ? v.join("\n") : "";
const key = (v: string) => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "process";
const clean = (v: unknown) => String(v || "").replaceAll("_", " ");
const tone = (v: string) => ["active", "released", "field_qualified"].includes(v) ? "bg-emerald-50 text-emerald-700" : v === "blocked" ? "bg-red-50 text-red-700" : "bg-violet-50 text-violet-700";
const fromProcess = (p: Json): Draft => ({ name: p.name || "", capabilityId: p.capabilityInstanceId || "", purpose: p.purpose || "", outcome: p.intendedOutcome || "", trigger: p.triggerCondition || "", steps: p.procedureSteps?.length ? p.procedureSteps.map((s: Step) => ({ ...s })) : [newStep()], inputs: text(p.requiredInputs), tools: text(p.toolSystemBoundaries), outputs: text(p.requiredOutputs), evidence: text(p.evidenceRequirements), approvals: text(p.approvalGates), recovery: text(p.failurePaths), terminal: text(p.terminalCriteria), tests: text(p.acceptanceTests) });
async function request<T>(method: "GET" | "POST" | "PATCH", url: string, body?: unknown): Promise<T> { const target = new URL(url, window.location.origin); const seat = new URLSearchParams(window.location.search).get("seat"); if (seat) target.searchParams.set("seatId", seat); return (await apiRequest(method, target.pathname + target.search, body)).json(); }

export default function OperationsStudioPage() {
  const { companyId = "" } = useParams<{ companyId: string }>(); const root = `/api/eos/companies/${encodeURIComponent(companyId)}`; const cache = useQueryClient();
  const [showCapability, setShowCapability] = useState(false); const [showBuilder, setShowBuilder] = useState(false); const [capabilityName, setCapabilityName] = useState(""); const [capabilityTrigger, setCapabilityTrigger] = useState(""); const [draft, setDraft] = useState<Draft>(blank()); const [editing, setEditing] = useState<Json | null>(null);
  const context = useQuery<Json>({ queryKey: [root, "context"], queryFn: () => request("GET", `${root}/context`) });
  const state = useQuery<Json>({ queryKey: [root, "operations-state"], queryFn: () => request("GET", `${root}/operations-state`) });
  const refresh = async () => { await Promise.all([cache.invalidateQueries({ queryKey: [root, "context"] }), cache.invalidateQueries({ queryKey: [root, "operations-state"] })]); };
  const capabilities = state.data?.capabilities || []; const processes = state.data?.processes || []; const allowed = (context.data?.principalContext?.allowedSurfaces || []).includes("operations");
  const navigation: UniversalLayoutLeftRailItem[] = [{ icon: BriefcaseBusiness, label: "Workspace", href: `/company/${companyId}` }, { icon: Workflow, label: "Process Studio", href: `/company/${companyId}/operations`, active: true }, { icon: Network, label: "Org Studio", href: `/company/${companyId}/org-studio` }];
  const close = () => { setShowBuilder(false); setEditing(null); setDraft(blank()); };
  const payload = () => ({ capabilityInstanceId: draft.capabilityId, name: draft.name.trim(), workflowKey: `workflow:${key(draft.name)}`, purpose: draft.purpose.trim(), intendedOutcome: draft.outcome.trim(), triggerCondition: draft.trigger.trim(), templateAncestry: "native-eos-process-studio-v2", procedureSteps: draft.steps.map((s) => ({ id: s.id, title: s.title.trim(), instructions: s.instructions.trim(), completionCriteria: s.completionCriteria.trim() })), requiredInputs: lines(draft.inputs), toolSystemBoundaries: lines(draft.tools), requiredOutputs: lines(draft.outputs), evidenceRequirements: lines(draft.evidence), approvalGates: lines(draft.approvals), failurePaths: lines(draft.recovery), terminalCriteria: lines(draft.terminal), acceptanceTests: lines(draft.tests), sourceAuthority: "native_eos" });
  const createCapability = useMutation({ mutationFn: () => request<Json>("POST", `${root}/capabilities`, { name: capabilityName.trim(), capabilityKey: key(capabilityName), activationTrigger: capabilityTrigger.trim(), maturity: "defined", sourceAuthority: "native_eos" }), onSuccess: async (r) => { setCapabilityName(""); setCapabilityTrigger(""); setDraft((d) => ({ ...d, capabilityId: r.id })); setShowCapability(false); await refresh(); } });
  const createProcess = useMutation({ mutationFn: () => request<Json>("POST", `${root}/processes`, payload()), onSuccess: async () => { close(); await refresh(); } });
  const saveProcess = useMutation({ mutationFn: () => { if (!editing) throw new Error("Choose a draft process."); const { capabilityInstanceId, sourceAuthority, ...update } = payload(); return request<Json>("PATCH", `${root}/processes/${editing.id}`, update); }, onSuccess: async () => { close(); await refresh(); } });
  const version = useMutation({ mutationFn: (p: Json) => request<Json>("POST", `${root}/processes/${p.id}/versions`, { reason: `Create a governed revision of ${p.name}.` }), onSuccess: async (p) => { setEditing(p); setDraft(fromProcess(p)); setShowBuilder(true); await refresh(); } });
  const transition = useMutation({ mutationFn: ({ id, qualificationState, releaseState }: Json) => request("PATCH", `${root}/processes/${id}`, { ...(qualificationState ? { qualificationState } : {}), ...(releaseState ? { releaseState } : {}) }), onSuccess: refresh });
  const capabilityTransition = useMutation({ mutationFn: ({ id, state }: Json) => request("PATCH", `${root}/capabilities/${id}`, { state }), onSuccess: refresh });
  const valid = Boolean(draft.capabilityId && draft.name.trim().length > 1 && draft.purpose.trim().length > 2 && draft.outcome.trim().length > 2 && draft.trigger.trim().length > 2 && draft.steps.every((s) => s.title.trim() && s.instructions.trim() && s.completionCriteria.trim()));
  const processCounts = useMemo(() => new Map<string, number>(capabilities.map((c: Json): [string, number] => [String(c.id), processes.filter((p: Json) => p.capabilityInstanceId === c.id).length])), [capabilities, processes]);
  const setStep = (i: number, field: keyof Step, value: string) => setDraft((d) => ({ ...d, steps: d.steps.map((s, n) => n === i ? { ...s, [field]: value } : s) }));
  const move = (i: number, direction: -1 | 1) => setDraft((d) => { const steps = [...d.steps], to = i + direction; if (to < 0 || to >= steps.length) return d; [steps[i], steps[to]] = [steps[to], steps[i]]; return { ...d, steps }; });
  if (context.isLoading || state.isLoading) return <UniversalLayout title="Process Studio" leftRailItems={navigation} floatingPanel={false}><p className="p-6 text-sm text-muted-foreground">Loading the company process graph…</p></UniversalLayout>;
  if (context.isError || state.isError) return <UniversalLayout title="Process Studio" leftRailItems={navigation} floatingPanel={false}><div className="m-6 rounded-xl border p-5"><p className="font-medium">The process graph could not be loaded.</p><Button className="mt-3" onClick={refresh}>Retry</Button></div></UniversalLayout>;
  if (!allowed) return <UniversalLayout title="Process Studio" leftRailItems={navigation} floatingPanel={false}><div className="m-6 rounded-xl border p-5"><p className="font-medium">This role does not have access to Process Studio.</p><Button className="mt-4" asChild><Link href={`/company/${companyId}`}>Return to my workspace</Link></Button></div></UniversalLayout>;
  return <UniversalLayout title="Process Studio" companyName={context.data?.company?.name} companyHref={`/company/${companyId}`} portfolioName={context.data?.portfolio?.name} portfolioHref={context.data?.portfolio?.id ? `/portfolios/${context.data.portfolio.id}` : "/portfolios"} roleName={context.data?.principalContext?.seat} leftRailItems={navigation} floatingPanel={false}><section className="space-y-6">
    <header className="flex flex-col gap-4 border-b pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eos-label">Native operating system</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Process Studio</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Build the governed operating contracts that make this company run. Providers can support a step, but the process, authority, evidence, and recovery path are native to EOS.</p></div><div className="flex gap-2"><Button variant="outline" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button><Button onClick={() => { setEditing(null); setDraft({ ...blank(), capabilityId: capabilities[0]?.id || "" }); setShowBuilder(true); }}><Plus className="mr-2 h-4 w-4" />New process</Button></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Capabilities" value={String(capabilities.length)} hint={`${state.data?.counts?.activeCapabilities || 0} active`} /><Fact label="Processes" value={String(processes.length)} hint={`${state.data?.counts?.releasedProcesses || 0} released`} /><Fact label="Field qualified" value={String(state.data?.counts?.fieldQualifiedProcesses || 0)} hint="Observed in operation" /><Fact label="Native first" value="Yes" hint="Providers are optional" /></section>
    <section className="rounded-2xl border border-primary/20 bg-primary/[0.03] p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="eos-label">Business-in-a-box assembly</p><h2 className="mt-1 text-xl font-semibold">A capability owns a result. A process makes it runnable.</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Compose triggers, ordered work, tools, approvals, evidence, recovery, and acceptance checks. Released contracts remain immutable, so every operating change is a visible governed revision.</p></div><Button variant="outline" onClick={() => setShowCapability(true)}><Plus className="mr-2 h-4 w-4" />Add capability</Button></div></section>
    {showCapability && <section className="rounded-2xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Capability name"><Input value={capabilityName} onChange={(e) => setCapabilityName(e.target.value)} placeholder="Lead qualification" /></Field><Field label="Activation trigger"><Input value={capabilityTrigger} onChange={(e) => setCapabilityTrigger(e.target.value)} placeholder="A qualified inquiry is received" /></Field></div><div className="mt-4 flex gap-2"><Button disabled={capabilityName.trim().length < 2 || createCapability.isPending} onClick={() => createCapability.mutate()}>Create capability</Button><Button variant="ghost" onClick={() => setShowCapability(false)}>Cancel</Button></div></section>}
    {showBuilder && <section className="rounded-2xl border border-primary/25 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3 border-b pb-5"><div><p className="eos-label">{editing ? `Version ${editing.version} draft` : "Compose executable process"}</p><h2 className="mt-1 text-xl font-semibold">{editing ? "Edit governed revision" : "No-code workflow builder"}</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Each step carries its instruction and observable completion condition. This defines what people and role agents may run; it does not silently automate external effects.</p></div><Button variant="ghost" size="sm" onClick={close}>Close</Button></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Process name"><Input value={draft.name} onChange={(e) => setDraft((d) => ({ ...d, name: e.target.value }))} placeholder="Inbound lead qualification" /></Field><Field label="Capability"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={draft.capabilityId} disabled={Boolean(editing)} onChange={(e) => setDraft((d) => ({ ...d, capabilityId: e.target.value }))}><option value="">Choose a capability</option>{capabilities.map((c: Json) => <option key={c.id} value={c.id}>{c.name}</option>)}</select>{editing && <p className="mt-1 text-xs text-muted-foreground">A revision preserves the released process's capability binding. Create a new process for a different capability.</p>}</Field><Field label="Purpose"><Textarea value={draft.purpose} onChange={(e) => setDraft((d) => ({ ...d, purpose: e.target.value }))} /></Field><Field label="Intended outcome"><Textarea value={draft.outcome} onChange={(e) => setDraft((d) => ({ ...d, outcome: e.target.value }))} /></Field><Field label="Trigger"><Input value={draft.trigger} onChange={(e) => setDraft((d) => ({ ...d, trigger: e.target.value }))} placeholder="A qualified inquiry arrives" /></Field><List label="Native tools and allowed systems" value={draft.tools} onChange={(tools) => setDraft((d) => ({ ...d, tools }))} placeholder={"CRM\nCalendar\nEmail · approved provider binding only"} /></div>
      <section className="mt-6 rounded-2xl border bg-muted/20 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="eos-label">Workflow canvas</p><h3 className="mt-1 font-semibold">Ordered steps</h3></div><Button size="sm" variant="outline" onClick={() => setDraft((d) => ({ ...d, steps: [...d.steps, newStep()] }))}><Plus className="mr-2 h-4 w-4" />Add step</Button></div><div className="mt-4 space-y-3">{draft.steps.map((s, i) => <article key={s.id} className="rounded-xl border bg-white p-4"><div className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{i + 1}</div><div className="min-w-0 flex-1 space-y-3"><Input aria-label={`Step ${i + 1} title`} value={s.title} onChange={(e) => setStep(i, "title", e.target.value)} placeholder="Step title" /><Textarea aria-label={`Step ${i + 1} instructions`} value={s.instructions} onChange={(e) => setStep(i, "instructions", e.target.value)} placeholder="What the responsible role or agent must do" /><Input aria-label={`Step ${i + 1} completion`} value={s.completionCriteria} onChange={(e) => setStep(i, "completionCriteria", e.target.value)} placeholder="Observable completion condition" /></div><div className="flex shrink-0 flex-col gap-1"><Button size="icon" variant="ghost" disabled={!i} onClick={() => move(i, -1)}><ArrowUp className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={i === draft.steps.length - 1} onClick={() => move(i, 1)}><ArrowDown className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={draft.steps.length === 1} onClick={() => setDraft((d) => ({ ...d, steps: d.steps.filter((_, n) => n !== i) }))}><Trash2 className="h-4 w-4" /></Button></div></div></article>)}</div></section>
      <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><List label="Required inputs" value={draft.inputs} onChange={(inputs) => setDraft((d) => ({ ...d, inputs }))} placeholder={"Qualified lead record\nConsent reference"} /><List label="Required outputs" value={draft.outputs} onChange={(outputs) => setDraft((d) => ({ ...d, outputs }))} placeholder={"Qualified or declined outcome\nOwner handoff"} /><List label="Approval gates" value={draft.approvals} onChange={(approvals) => setDraft((d) => ({ ...d, approvals }))} placeholder="Founder approval before commitment" /><List label="Evidence required" value={draft.evidence} onChange={(evidence) => setDraft((d) => ({ ...d, evidence }))} placeholder={"Verified consent\nDelivery receipt"} /><List label="Failure and recovery" value={draft.recovery} onChange={(recovery) => setDraft((d) => ({ ...d, recovery }))} placeholder={"Pause and assign owner\nEscalate missing authority"} /><List label="Acceptance checks" value={draft.tests} onChange={(tests) => setDraft((d) => ({ ...d, tests }))} placeholder={"Denied authority cannot execute\nCompletion retains evidence"} /><List label="Terminal criteria" value={draft.terminal} onChange={(terminal) => setDraft((d) => ({ ...d, terminal }))} placeholder="Outcome, owner, and evidence recorded" /></section>
      <div className="mt-6 flex gap-2"><Button disabled={!valid || createProcess.isPending || saveProcess.isPending} onClick={() => editing ? saveProcess.mutate() : createProcess.mutate()}>{editing ? "Save governed revision" : "Create governed draft"}</Button><Button variant="ghost" onClick={close}>Cancel</Button></div>
    </section>}
    <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl border bg-white p-5"><div className="flex items-end justify-between"><div><p className="eos-label">Capability map</p><h2 className="mt-1 text-xl font-semibold">What the company can do</h2></div><Button size="sm" variant="outline" onClick={() => setShowCapability(true)}>Add</Button></div><div className="mt-5 space-y-3">{capabilities.map((c: Json) => <article key={c.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{c.name}</p><p className="mt-1 text-xs text-muted-foreground">{processCounts.get(String(c.id)) || 0} processes · {clean(c.maturity)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${tone(c.state)}`}>{clean(c.state)}</span></div>{c.state === "planned" && <Button className="mt-3" size="sm" variant="outline" onClick={() => capabilityTransition.mutate({ id: c.id, state: "activating" })}>Begin activation</Button>}{c.state === "activating" && <Button className="mt-3" size="sm" variant="outline" onClick={() => capabilityTransition.mutate({ id: c.id, state: "active" })}>Mark active</Button>}</article>)}</div></div>
      <div className="rounded-2xl border bg-white p-5"><div className="flex items-end justify-between"><div><p className="eos-label">Process graph</p><h2 className="mt-1 text-xl font-semibold">How each result gets produced</h2></div><Button size="sm" variant="outline" onClick={() => { setEditing(null); setDraft({ ...blank(), capabilityId: capabilities[0]?.id || "" }); setShowBuilder(true); }}>Add</Button></div><div className="mt-5 space-y-3">{processes.map((p: Json) => { const cap = capabilities.find((c: Json) => c.id === p.capabilityInstanceId); return <article key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{p.name}</p><p className="mt-1 text-xs text-muted-foreground">{cap?.name || "Capability"} · v{p.version} · {p.procedureSteps?.length || 0} steps</p></div><div className="flex gap-2"><span className={`rounded-full px-2.5 py-1 text-xs ${tone(p.qualificationState)}`}>{clean(p.qualificationState)}</span><span className={`rounded-full px-2.5 py-1 text-xs ${tone(p.releaseState)}`}>{clean(p.releaseState)}</span></div></div><p className="mt-3 text-sm text-muted-foreground">{p.intendedOutcome}</p><div className="mt-3 space-y-1">{(p.procedureSteps || []).slice(0, 4).map((s: Step, i: number) => <div key={s.id} className="flex items-center gap-2 text-xs text-muted-foreground"><CircleDot className="h-3.5 w-3.5 text-primary" />{i + 1}. {s.title}</div>)}</div><div className="mt-4 flex flex-wrap gap-2">{p.releaseState === "draft" ? <Button size="sm" variant="outline" onClick={() => { setEditing(p); setDraft(fromProcess(p)); setShowBuilder(true); }}><Pencil className="mr-2 h-3.5 w-3.5" />Edit draft</Button> : <Button size="sm" variant="outline" onClick={() => version.mutate(p)}><GitFork className="mr-2 h-3.5 w-3.5" />Create next version</Button>}{p.qualificationState === "mapped" && <Button size="sm" variant="outline" onClick={() => transition.mutate({ id: p.id, qualificationState: "artifact_complete" })}>Complete artifact</Button>}{p.qualificationState === "artifact_complete" && <Button size="sm" variant="outline" onClick={() => transition.mutate({ id: p.id, qualificationState: "implemented" })}>Mark implemented</Button>}{p.releaseState === "draft" && <Button size="sm" variant="outline" onClick={() => transition.mutate({ id: p.id, releaseState: "review" })}>Submit review <ShieldCheck className="ml-2 h-3.5 w-3.5" /></Button>}{p.releaseState === "review" && <Button size="sm" variant="outline" onClick={() => transition.mutate({ id: p.id, releaseState: "released" })}>Release version <ArrowRight className="ml-2 h-3.5 w-3.5" /></Button>}</div></article>; })}</div></div></section>
  </section></UniversalLayout>;
}
function Fact({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="rounded-2xl border bg-white p-4"><p className="eos-label">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <Label className="block"><span className="eos-label">{label}</span><span className="mt-2 block">{children}</span></Label>; }
function List({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder: string }) { return <Field label={label}><Textarea value={value} onChange={(e) => onChange(e.target.value)} className="min-h-28" placeholder={placeholder} /></Field>; }
