import { useEffect, useState } from "react";
import { Building2, CalendarClock, Loader2, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type PortalView = {
  companyName: string; recipientLabel: string; expiresAt: string;
  portal: { name: string; portalType: string; visibleSections: string[] };
  publications: Array<{ id: string; section: string; title: string; body: string; dataProjection: Record<string, unknown>; publishedAt: string }>;
};

export default function StakeholderPortalPage() {
  const token = decodeURIComponent(window.location.pathname.split("/").pop() || "");
  const [view, setView] = useState<PortalView | null>(null); const [error, setError] = useState("");
  useEffect(() => { let live = true; fetch(`/api/public/stakeholder-portals/${encodeURIComponent(token)}`, { headers: { Accept: "application/json" }, cache: "no-store" }).then(async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "This stakeholder workspace is unavailable."); if (live) setView(body); }).catch((reason) => live && setError(reason instanceof Error ? reason.message : "This stakeholder workspace is unavailable.")); return () => { live = false; }; }, [token]);
  if (error) return <main className="min-h-screen bg-surface px-5 py-12"><Card className="mx-auto max-w-xl border-0 shadow-sm"><CardHeader><div className="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-destructive/10 text-destructive"><ShieldCheck className="h-5 w-5" /></div><CardTitle>Workspace unavailable</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{error}</CardContent></Card></main>;
  if (!view) return <main className="grid min-h-screen place-items-center bg-surface"><div className="flex items-center gap-3 text-sm text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />Opening your private workspace</div></main>;
  const grouped = view.portal.visibleSections.map((section) => ({ section, items: view.publications.filter((item) => item.section === section) })).filter((group) => group.items.length);
  return <main className="min-h-screen bg-surface px-4 py-8 sm:px-8 sm:py-12"><div className="mx-auto max-w-4xl space-y-6"><header className="rounded-3xl bg-white p-6 shadow-sm sm:p-9"><div className="mb-6 flex items-start justify-between gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Building2 className="h-6 w-6" /></div><Badge variant="secondary" className="capitalize">{view.portal.portalType}</Badge></div><p className="eos-label mb-2">{view.companyName}</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{view.portal.name}</h1><p className="mt-3 text-sm text-muted-foreground">Private workspace for {view.recipientLabel}. Only explicitly published, evidence-backed updates appear here.</p><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><CalendarClock className="h-4 w-4" />Access expires {new Date(view.expiresAt).toLocaleString()}</div></header>{grouped.map((group) => <section key={group.section} className="space-y-3"><p className="eos-label px-1 capitalize">{group.section.replaceAll("_", " ")}</p>{group.items.map((item) => <Card key={item.id} className="border-0 shadow-sm"><CardHeader><CardTitle className="text-xl">{item.title}</CardTitle><p className="text-xs text-muted-foreground">Published {new Date(item.publishedAt).toLocaleString()}</p></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-6 text-foreground/85">{item.body}</p>{Object.keys(item.dataProjection || {}).length > 0 && <dl className="mt-5 grid gap-3 rounded-2xl bg-muted/50 p-4 sm:grid-cols-2">{Object.entries(item.dataProjection).map(([key, value]) => <div key={key}><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{key.replaceAll("_", " ")}</dt><dd className="mt-1 text-sm">{typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>)}</dl>}</CardContent></Card>)}</section>)}</div></main>;
}
