import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { Express, Request, Response } from "express";
import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { ZodError } from "zod";
import {
  companies, eosAgentEventOutbox, eosAuditRecords, eosEvidence, eosInstrumentObjects, eosProcessDefinitions, eosSeats, eosStakeholders, eosStakeholderPortalAccessGrants, eosWorkPackets,
  eosStakeholderPortalPublications, eosStakeholderPortals,
} from "@shared/schema";
import {
  stakeholderAccessGrantSchema, stakeholderPortalCreateSchema, stakeholderPortalTransitionSchema,
  stakeholderPublicationCreateSchema, stakeholderPublicationTransitionSchema, stakeholderPortalIntakeFormCreateSchema,
  stakeholderPortalIntakeFormTransitionSchema, stakeholderPortalIntakeSubmissionSchema,
  stakeholderPortalIntakeReviewHandoffSchema, stakeholderPortalIntakeReviewSchema,
} from "@shared/stakeholder-portal";
import { db } from "../db";
import { fixedWindowRateLimit } from "../middleware/rate-limit";
import { EosRouteError, authorizeAction, companyAccess, mayAccessClassification, visibleSeatIds } from "./eos-runtime";
import { nativeContractContentSha256 } from "../esign/template-generation";
import { dispatchAgentEventOutboxEvent } from "../agents/scheduler";

const tokenDigest = (value: string) => createHash("sha256").update(value).digest("hex");
const identityDigest = (value: string) => createHash("sha256").update(value.trim().toLowerCase()).digest("hex");
const publicPortalRateLimit = fixedWindowRateLimit({ limit: 90, windowMs: 60_000, namespace: "stakeholder-portal-public" });
const publicPortalIntakeRateLimit = fixedWindowRateLimit({ limit: 20, windowMs: 60_000, namespace: "stakeholder-portal-intake" });
function route(handler: (req: Request, res: Response) => Promise<void>) { return async (req: Request, res: Response, next: (error?: unknown) => void) => { try { await handler(req, res); } catch (error) { if (error instanceof EosRouteError) return res.status(error.status).json({ code: error.code, message: error.message }); if (error instanceof ZodError) return res.status(400).json({ code: "stakeholder_portal_input_invalid", message: error.issues[0]?.message || "Stakeholder portal input is invalid." }); next(error); } }; }

async function portalAccess(req: Request, actionKey: string, view = false, targetSeatId?: string) {
  const access = await companyAccess(req);
  const policy = await authorizeAction(req, access, { authorityClass: view ? "view" : "decide", resource: "stakeholder_portal", actionKey, purpose: view ? "inspect_stakeholder_portals" : "govern_external_disclosure", classification: "restricted", consequence: view ? "routine" : "material", targetSeatId: targetSeatId || access.seat.id });
  return { access, policy };
}

async function evidenceFor(companyId: number, ids: string[], verified = false) {
  if (new Set(ids).size !== ids.length) throw new EosRouteError(409, "portal_evidence_duplicate", "Evidence references must be unique.");
  if (!ids.length) return [];
  const rows = await db.select().from(eosEvidence).where(and(eq(eosEvidence.companyId, companyId), inArray(eosEvidence.id, ids)));
  if (rows.length !== ids.length || (verified && rows.some((item) => item.verificationState !== "verified"))) throw new EosRouteError(409, "portal_evidence_invalid", verified ? "External disclosure requires verified Evidence from the same company." : "Evidence must resolve inside this company.");
  return rows;
}

function recordValue(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function intakeDefinition(form: typeof eosInstrumentObjects.$inferSelect) {
  const data = recordValue(form.data);
  const parsed = stakeholderPortalIntakeFormCreateSchema.safeParse({ formKey: data.formKey, title: form.title, summary: form.summary, questions: data.questions, confirmationMessage: data.confirmationMessage });
  if (!parsed.success || data.clientPortalIntake !== true || typeof data.stakeholderPortalId !== "string") return null;
  return { ...parsed.data, portalId: data.stakeholderPortalId };
}
function publicHeaders(res: Response) { res.setHeader("Cache-Control", "no-store, private, max-age=0"); res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin"); res.setHeader("X-Robots-Tag", "noindex, nofollow, noarchive"); }

export function registerPublicStakeholderPortalRoutes(app: Express): void {
  app.use("/api/public/stakeholder-portals", publicPortalRateLimit);
  app.get("/api/public/stakeholder-portals/:token", route(async (req, res) => {
    const tokenHash = tokenDigest(req.params.token || ""); const now = new Date();
    const [grant] = await db.select().from(eosStakeholderPortalAccessGrants).where(eq(eosStakeholderPortalAccessGrants.tokenHash, tokenHash)).limit(1);
    if (!grant || ["revoked", "expired"].includes(grant.state) || grant.expiresAt <= now) {
      if (grant && grant.expiresAt <= now && grant.state !== "expired") await db.update(eosStakeholderPortalAccessGrants).set({ state: "expired" }).where(eq(eosStakeholderPortalAccessGrants.id, grant.id));
      throw new EosRouteError(404, "stakeholder_portal_unavailable", "This stakeholder workspace is unavailable.");
    }
    const [portal] = await db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, grant.portalId), eq(eosStakeholderPortals.state, "active"))).limit(1);
    if (!portal) throw new EosRouteError(404, "stakeholder_portal_unavailable", "This stakeholder workspace is unavailable.");
    const [company, publications, candidateForms] = await Promise.all([
      db.select({ name: companies.name }).from(companies).where(eq(companies.id, portal.companyId)).limit(1).then((rows) => rows[0]),
      db.select().from(eosStakeholderPortalPublications).where(and(eq(eosStakeholderPortalPublications.portalId, portal.id), eq(eosStakeholderPortalPublications.state, "published"))).orderBy(desc(eosStakeholderPortalPublications.publishedAt)),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, portal.companyId), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"), eq(eosInstrumentObjects.state, "active"))),
    ]);
    const intakeForms = candidateForms.map((form) => ({ form, definition: intakeDefinition(form) })).filter((item): item is { form: typeof eosInstrumentObjects.$inferSelect; definition: NonNullable<ReturnType<typeof intakeDefinition>> } => Boolean(item.definition && item.definition.portalId === portal.id));
    const formIds = intakeForms.map((item) => item.form.id);
    const submissions = formIds.length ? await db.select({ parentObjectId: eosInstrumentObjects.parentObjectId }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, portal.companyId), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "submission"), inArray(eosInstrumentObjects.parentObjectId, formIds), sql`${eosInstrumentObjects.data}->>'accessGrantId' = ${grant.id}`)) : [];
    const submittedFormIds = new Set(submissions.map((item) => item.parentObjectId));
    await db.update(eosStakeholderPortalAccessGrants).set({ state: "accessed", lastAccessedAt: now, accessCount: grant.accessCount + 1 }).where(eq(eosStakeholderPortalAccessGrants.id, grant.id));
    publicHeaders(res);
    res.json({ schemaVersion: "eos.stakeholder-portal-public.v2", companyName: company?.name || "Organization", portal: { name: portal.name, portalType: portal.portalType, visibleSections: portal.visibleSections }, recipientLabel: grant.recipientLabel, expiresAt: grant.expiresAt, publications: publications.map(({ recordedByUserId: _recordedByUserId, publishedByUserId: _publishedByUserId, companyId: _companyId, ...item }) => item), intakeForms: intakeForms.map(({ form, definition }) => ({ id: form.id, title: form.title, summary: form.summary, questions: definition.questions, confirmationMessage: definition.confirmationMessage, submitted: submittedFormIds.has(form.id) })) });
  }));

  app.use("/api/public/stakeholder-portals/:token/intake-forms", publicPortalIntakeRateLimit);
  app.post("/api/public/stakeholder-portals/:token/intake-forms/:formId/submissions", route(async (req, res) => {
    const input = stakeholderPortalIntakeSubmissionSchema.parse(req.body); const tokenHash = tokenDigest(req.params.token || ""); const now = new Date();
    if (input.website.trim()) { publicHeaders(res); res.status(202).json({ schemaVersion: "eos.stakeholder-portal-intake-submission.v1", accepted: true }); return; }
    const [grant] = await db.select().from(eosStakeholderPortalAccessGrants).where(eq(eosStakeholderPortalAccessGrants.tokenHash, tokenHash)).limit(1);
    if (!grant || ["revoked", "expired"].includes(grant.state) || grant.expiresAt <= now) throw new EosRouteError(404, "stakeholder_portal_unavailable", "This stakeholder workspace is unavailable.");
    const [portal, form] = await Promise.all([
      db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, grant.portalId), eq(eosStakeholderPortals.state, "active"))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.formId), eq(eosInstrumentObjects.companyId, grant.companyId), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"), eq(eosInstrumentObjects.state, "active"))).limit(1).then((rows) => rows[0]),
    ]);
    const definition = form ? intakeDefinition(form) : null;
    if (!portal || !form || !definition || definition.portalId !== portal.id) throw new EosRouteError(404, "stakeholder_portal_intake_unavailable", "This onboarding intake is unavailable.");
    const allowed = new Set(definition.questions.map((question) => question.id));
    for (const key of Object.keys(input.answers)) if (!allowed.has(key)) throw new EosRouteError(400, "stakeholder_portal_intake_answer_unknown", "The intake includes a field that is not available.");
    for (const question of definition.questions) { const value = input.answers[question.id]?.trim() || ""; if (question.required && !value) throw new EosRouteError(400, "stakeholder_portal_intake_answer_required", `${question.label} is required.`); if (question.type === "email" && value && !/^\S+@\S+\.\S+$/.test(value)) throw new EosRouteError(400, "stakeholder_portal_intake_email_invalid", "Enter a valid email address."); if (question.type === "select" && value && !question.options.includes(value)) throw new EosRouteError(400, "stakeholder_portal_intake_selection_invalid", `Choose a listed value for ${question.label}.`); }
    const objectKey = `stakeholder-portal-intake-submission:${grant.id}:${form.id}`;
    await db.transaction(async (tx) => {
      await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${`stakeholder-portal-intake:${grant.id}:${form.id}`}))`);
      const [existing] = await tx.select({ id: eosInstrumentObjects.id }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, grant.companyId), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectKey, objectKey))).limit(1);
      if (existing) throw new EosRouteError(409, "stakeholder_portal_intake_already_submitted", "This onboarding intake has already been submitted. Contact the team if something needs to change.");
      const submissionId = randomUUID(); const data = { clientPortalIntakeSubmission: true, stakeholderPortalId: portal.id, accessGrantId: grant.id, formObjectId: form.id, responses: input.answers, acknowledgement: true, submittedAt: now.toISOString(), externalActor: "authenticated_private_portal_recipient", verificationState: "unverified" };
      await tx.insert(eosInstrumentObjects).values({ id: submissionId, companyId: grant.companyId, instrumentKey: "forms", objectType: "submission", objectKey, title: `Client onboarding intake · ${form.title}`, summary: "Private client onboarding input submitted through a time-bounded EOS workspace link.", state: "active", classification: "confidential", visibility: "organization", ownerSeatId: portal.ownerSeatId, parentObjectId: form.id, data, sourceReference: { authority: "private_eos_client_portal", portalId: portal.id, accessGrantId: grant.id, externalActor: "authenticated_private_portal_recipient" }, evidenceIds: [], contentSha256: nativeContractContentSha256({ schemaVersion: "eos.stakeholder-portal-intake-submission.v1", companyId: grant.companyId, portalId: portal.id, grantId: grant.id, formId: form.id, data }), version: 1, recordedByUserId: form.recordedByUserId, createdAt: now, updatedAt: now, archivedAt: null });
      await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: grant.companyId, actorUserId: form.recordedByUserId, action: "stakeholder_portal.intake_submitted", targetType: "stakeholder_portal_intake", targetId: submissionId, traceId: `public:${grant.id}`, correlationId: submissionId, result: "received_unverified", details: { portalId: portal.id, formId: form.id, accessGrantId: grant.id, actorType: "authenticated_private_portal_recipient", verificationState: "unverified" }, createdAt: now });
    });
    publicHeaders(res); res.status(201).json({ schemaVersion: "eos.stakeholder-portal-intake-submission.v1", accepted: true, verificationState: "unverified", confirmationMessage: definition.confirmationMessage });
  }));
}

export function registerStakeholderPortalRoutes(app: Express): void {
  app.get("/api/eos/companies/:companyId/stakeholder-portals", route(async (req, res) => {
    const { access } = await portalAccess(req, "stakeholder_portal.read", true);
    const portals = await db.select().from(eosStakeholderPortals).where(eq(eosStakeholderPortals.companyId, access.company.id)).orderBy(desc(eosStakeholderPortals.updatedAt));
    const ids = portals.map((item) => item.id);
    const [publications, grants, forms] = ids.length ? await Promise.all([
      db.select().from(eosStakeholderPortalPublications).where(and(eq(eosStakeholderPortalPublications.companyId, access.company.id), inArray(eosStakeholderPortalPublications.portalId, ids))).orderBy(desc(eosStakeholderPortalPublications.updatedAt)),
      db.select({ id: eosStakeholderPortalAccessGrants.id, portalId: eosStakeholderPortalAccessGrants.portalId, recipientLabel: eosStakeholderPortalAccessGrants.recipientLabel, state: eosStakeholderPortalAccessGrants.state, expiresAt: eosStakeholderPortalAccessGrants.expiresAt, lastAccessedAt: eosStakeholderPortalAccessGrants.lastAccessedAt, accessCount: eosStakeholderPortalAccessGrants.accessCount, createdAt: eosStakeholderPortalAccessGrants.createdAt }).from(eosStakeholderPortalAccessGrants).where(and(eq(eosStakeholderPortalAccessGrants.companyId, access.company.id), inArray(eosStakeholderPortalAccessGrants.portalId, ids))).orderBy(desc(eosStakeholderPortalAccessGrants.createdAt)),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"))),
    ]) : [[], [], []];
    const intakeForms = forms.map((form) => ({ form, definition: intakeDefinition(form) })).filter((item): item is { form: typeof eosInstrumentObjects.$inferSelect; definition: NonNullable<ReturnType<typeof intakeDefinition>> } => Boolean(item.definition && ids.includes(item.definition.portalId)));
    const formIds = intakeForms.map((item) => item.form.id);
    const submissions = formIds.length ? await db.select({ parentObjectId: eosInstrumentObjects.parentObjectId }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "submission"), inArray(eosInstrumentObjects.parentObjectId, formIds))) : [];
    res.json({ schemaVersion: "eos.stakeholder-portal-registry.v2", portals: portals.map((portal) => ({ ...portal, publications: publications.filter((item) => item.portalId === portal.id), accessGrants: grants.filter((item) => item.portalId === portal.id), intakeForms: intakeForms.filter((item) => item.definition.portalId === portal.id).map(({ form, definition }) => ({ id: form.id, formKey: definition.formKey, title: form.title, summary: form.summary, state: form.state, version: form.version, questionCount: definition.questions.length, submissionCount: submissions.filter((submission) => submission.parentObjectId === form.id).length })) })), counts: { dormant: portals.filter((item) => item.state === "dormant").length, active: portals.filter((item) => item.state === "active").length, paused: portals.filter((item) => item.state === "paused").length } });
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals", route(async (req, res) => {
    const input = stakeholderPortalCreateSchema.parse(req.body); const { ownerSeatId: requestedOwnerSeatId, ...portalInput } = input; const { access, policy } = await portalAccess(req, "stakeholder_portal.create", false, requestedOwnerSeatId);
    if (input.stakeholderId) { const [stakeholder] = await db.select().from(eosStakeholders).where(and(eq(eosStakeholders.id, input.stakeholderId), eq(eosStakeholders.companyId, access.company.id))).limit(1); if (!stakeholder) throw new EosRouteError(409, "portal_stakeholder_invalid", "Stakeholder must belong to this company."); }
    const ownerSeatId = requestedOwnerSeatId || access.seat.id; const visible = await visibleSeatIds(access.company.id, access.seat.id, access.role);
    const [ownerSeat] = await db.select({ id: eosSeats.id }).from(eosSeats).where(and(eq(eosSeats.id, ownerSeatId), eq(eosSeats.companyId, access.company.id), eq(eosSeats.status, "active"))).limit(1);
    if (!ownerSeat || !visible.has(ownerSeatId)) throw new EosRouteError(403, "stakeholder_portal_owner_scope_denied", "The requested client-workspace owner is outside this role's visible hierarchy.");
    const now = new Date(); const record = { id: randomUUID(), companyId: access.company.id, ...portalInput, stakeholderId: input.stakeholderId || null, state: "dormant", activationEvidenceIds: [], ownerSeatId, activatedByUserId: null, activatedAt: null, version: 1, recordedByUserId: req.user.id, createdAt: now, updatedAt: now };
    await db.transaction(async (tx) => { await tx.insert(eosStakeholderPortals).values(record); await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.created", targetType: "stakeholder_portal", targetId: record.id, traceId: policy.traceId, correlationId: policy.correlationId, result: "dormant", details: { portalType: input.portalType, externallyAccessible: false, policyDecisionId: policy.decisionId }, createdAt: now }); });
    res.status(201).json(record);
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/intake-forms", route(async (req, res) => {
    const input = stakeholderPortalIntakeFormCreateSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.intake_form.create");
    const [portal] = await db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1);
    if (!portal || portal.portalType !== "client") throw new EosRouteError(409, "stakeholder_portal_client_intake_invalid", "Client onboarding intake is available only inside a client workspace.");
    if (["retired", "paused"].includes(portal.state)) throw new EosRouteError(409, "stakeholder_portal_intake_portal_inactive", "Configure onboarding intake only while the client workspace is dormant, configuring, or active.");
    const now = new Date(); const id = randomUUID(); const objectKey = `stakeholder-portal-intake:${portal.id}:${input.formKey}`;
    const data = { clientPortalIntake: true, stakeholderPortalId: portal.id, formKey: input.formKey, questions: input.questions, confirmationMessage: input.confirmationMessage };
    const record = { id, companyId: access.company.id, instrumentKey: "forms", objectType: "form", objectKey, title: input.title, summary: input.summary, state: "draft", classification: "confidential", visibility: "organization", ownerSeatId: portal.ownerSeatId, parentObjectId: null, data, sourceReference: { authority: "native_eos", capability: "client_onboarding_intake", stakeholderPortalId: portal.id }, evidenceIds: [], contentSha256: nativeContractContentSha256({ schemaVersion: "eos.stakeholder-portal-intake-form.v1", companyId: access.company.id, portalId: portal.id, title: input.title, summary: input.summary, data }), version: 1, recordedByUserId: req.user.id, createdAt: now, updatedAt: now, archivedAt: null } as const;
    await db.transaction(async (tx) => { await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${`stakeholder-portal-intake-form:${access.company.id}:${portal.id}:${input.formKey}`}))`); const [existing] = await tx.select({ id: eosInstrumentObjects.id }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectKey, objectKey))).limit(1); if (existing) throw new EosRouteError(409, "stakeholder_portal_intake_form_exists", "This client workspace already has an onboarding intake with that key."); await tx.insert(eosInstrumentObjects).values(record); await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.intake_form_created", targetType: "stakeholder_portal_intake_form", targetId: id, traceId: policy.traceId, correlationId: policy.correlationId, result: "draft", details: { portalId: portal.id, formKey: input.formKey, externallyAccessible: false, policyDecisionId: policy.decisionId }, createdAt: now }); });
    res.status(201).json(record);
  }));

  app.patch("/api/eos/companies/:companyId/stakeholder-portals/:portalId/intake-forms/:formId", route(async (req, res) => {
    const input = stakeholderPortalIntakeFormTransitionSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.intake_form.transition");
    const [portal, form] = await Promise.all([
      db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.formId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"))).limit(1).then((rows) => rows[0]),
    ]);
    const definition = form ? intakeDefinition(form) : null;
    if (!portal || !form || !definition || definition.portalId !== portal.id || portal.portalType !== "client") throw new EosRouteError(404, "stakeholder_portal_intake_form_not_found", "The requested client onboarding intake is unavailable.");
    if (form.version !== input.expectedVersion) throw new EosRouteError(409, "stakeholder_portal_intake_form_version_conflict", "The onboarding intake changed before this decision.");
    if (input.state === "active" && (portal.state !== "active" || form.state !== "draft")) throw new EosRouteError(409, "stakeholder_portal_intake_form_activation_invalid", "Activate intake only after its client workspace is active and while the intake remains a draft.");
    if (input.state === "archived" && !["draft", "active"].includes(form.state)) throw new EosRouteError(409, "stakeholder_portal_intake_form_archive_invalid", "Only a draft or active onboarding intake can be archived.");
    const now = new Date(); const [updated] = await db.update(eosInstrumentObjects).set({ state: input.state, version: form.version + 1, updatedAt: now }).where(and(eq(eosInstrumentObjects.id, form.id), eq(eosInstrumentObjects.version, form.version))).returning();
    if (!updated) throw new EosRouteError(409, "stakeholder_portal_intake_form_concurrent_change", "The onboarding intake changed before this decision.");
    await db.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.intake_form_transitioned", targetType: "stakeholder_portal_intake_form", targetId: form.id, traceId: policy.traceId, correlationId: policy.correlationId, result: input.state, details: { portalId: portal.id, from: form.state, rationale: input.rationale, externallyAccessible: input.state === "active", policyDecisionId: policy.decisionId }, createdAt: now });
    res.json(updated);
  }));

  app.get("/api/eos/companies/:companyId/stakeholder-portals/:portalId/intake-forms/:formId/submissions", route(async (req, res) => {
    const { access } = await portalAccess(req, "stakeholder_portal.intake_form.read", true);
    const [portal, form] = await Promise.all([
      db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.formId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"))).limit(1).then((rows) => rows[0]),
    ]);
    const definition = form ? intakeDefinition(form) : null;
    if (!portal || !form || !definition || definition.portalId !== portal.id || portal.portalType !== "client") throw new EosRouteError(404, "stakeholder_portal_intake_form_not_found", "The requested client onboarding intake is unavailable.");
    const submissions = await db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "submission"), eq(eosInstrumentObjects.parentObjectId, form.id))).orderBy(desc(eosInstrumentObjects.createdAt));
    const visibleSubmissions = submissions.filter((submission) => { const data = recordValue(submission.data); return data.clientPortalIntakeSubmission === true && data.stakeholderPortalId === portal.id && data.formObjectId === form.id; });
    const reviews = visibleSubmissions.length ? await db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "review"), inArray(eosInstrumentObjects.parentObjectId, visibleSubmissions.map((submission) => submission.id)))) : [];
    const reviewsBySubmission = new Map(reviews.filter((review) => { const data = recordValue(review.data); return data.clientPortalIntakeReview === true && data.stakeholderPortalId === portal.id && data.formObjectId === form.id && typeof data.submissionObjectId === "string"; }).map((review) => [String(recordValue(review.data).submissionObjectId), review]));
    const handoffs = reviews.length ? await db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "handoff"), inArray(eosInstrumentObjects.parentObjectId, reviews.map((review) => review.id)))) : [];
    const handoffByReview = new Map(handoffs.filter((handoff) => { const data = recordValue(handoff.data); return data.clientPortalIntakeHandoff === true && data.stakeholderPortalId === portal.id && typeof data.reviewObjectId === "string"; }).map((handoff) => [String(recordValue(handoff.data).reviewObjectId), handoff]));
    res.json({ schemaVersion: "eos.stakeholder-portal-intake-review.v3", portal: { id: portal.id, name: portal.name }, form: { id: form.id, title: form.title, questions: definition.questions.map((question) => ({ id: question.id, label: question.label })) }, submissions: visibleSubmissions.map((submission) => { const data = recordValue(submission.data); const review = reviewsBySubmission.get(submission.id); const reviewData = review ? recordValue(review.data) : null; const handoff = review ? handoffByReview.get(review.id) : null; const handoffData = handoff ? recordValue(handoff.data) : null; return { id: submission.id, submittedAt: data.submittedAt, verificationState: data.verificationState || "unverified", acknowledgement: data.acknowledgement === true, responses: recordValue(data.responses), review: reviewData ? { id: review!.id, disposition: reviewData.disposition, reviewerSummary: reviewData.reviewerSummary, nextAction: reviewData.nextAction, reviewedAt: reviewData.reviewedAt, handoff: handoffData ? { id: handoff!.id, workPacketId: handoffData.workPacketId, processDefinitionId: handoffData.processDefinitionId || null, title: handoffData.title, createdAt: handoffData.createdAt } : null } : null }; }) });
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/intake-forms/:formId/submissions/:submissionId/reviews", route(async (req, res) => {
    const input = stakeholderPortalIntakeReviewSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.intake_form.review");
    const [portal, form, submission] = await Promise.all([
      db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.formId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.submissionId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "submission"))).limit(1).then((rows) => rows[0]),
    ]);
    const definition = form ? intakeDefinition(form) : null; const submissionData = submission ? recordValue(submission.data) : {};
    if (!portal || !form || !submission || !definition || definition.portalId !== portal.id || portal.portalType !== "client" || submission.parentObjectId !== form.id || submissionData.clientPortalIntakeSubmission !== true || submissionData.stakeholderPortalId !== portal.id || submissionData.formObjectId !== form.id) throw new EosRouteError(404, "stakeholder_portal_intake_submission_not_found", "The requested private onboarding submission is unavailable.");
    const now = new Date(); const id = randomUUID(); const objectKey = `stakeholder-portal-intake-review:${submission.id}`;
    const data = { clientPortalIntakeReview: true, stakeholderPortalId: portal.id, formObjectId: form.id, submissionObjectId: submission.id, disposition: input.disposition, reviewerSummary: input.reviewerSummary, nextAction: input.nextAction, reviewedAt: now.toISOString(), reviewBoundary: "human_disposition_only_client_answers_remain_unverified" };
    const record = { id, companyId: access.company.id, instrumentKey: "forms", objectType: "review", objectKey, title: `Client onboarding review · ${form.title}`, summary: input.reviewerSummary, state: "completed", classification: "confidential", visibility: "organization", ownerSeatId: portal.ownerSeatId, parentObjectId: submission.id, data, sourceReference: { authority: "native_eos", capability: "client_onboarding_review", stakeholderPortalId: portal.id, submissionObjectId: submission.id }, evidenceIds: [], contentSha256: nativeContractContentSha256({ schemaVersion: "eos.stakeholder-portal-intake-review.v1", companyId: access.company.id, portalId: portal.id, formId: form.id, submissionId: submission.id, data }), version: 1, recordedByUserId: req.user.id, createdAt: now, updatedAt: now, archivedAt: null } as const;
    await db.transaction(async (tx) => { await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${`stakeholder-portal-intake-review:${submission.id}`}))`); const [existing] = await tx.select({ id: eosInstrumentObjects.id }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectKey, objectKey))).limit(1); if (existing) throw new EosRouteError(409, "stakeholder_portal_intake_already_reviewed", "This onboarding submission already has an accountable review. Preserve that decision or issue a new intake for changed client input."); await tx.insert(eosInstrumentObjects).values(record); await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.intake_reviewed", targetType: "stakeholder_portal_intake_review", targetId: id, traceId: policy.traceId, correlationId: policy.correlationId, result: input.disposition, details: { portalId: portal.id, formId: form.id, submissionId: submission.id, reviewBoundary: data.reviewBoundary, policyDecisionId: policy.decisionId }, createdAt: now }); });
    res.status(201).json({ id: record.id, disposition: input.disposition, reviewerSummary: input.reviewerSummary, nextAction: input.nextAction, reviewedAt: data.reviewedAt, boundary: "Client answers remain unverified unless separately supported by accountable Evidence." });
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/intake-forms/:formId/submissions/:submissionId/reviews/:reviewId/handoff", route(async (req, res) => {
    const input = stakeholderPortalIntakeReviewHandoffSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.intake_form.handoff");
    const [portal, form, submission, review] = await Promise.all([
      db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.formId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.submissionId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "submission"))).limit(1).then((rows) => rows[0]),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.id, req.params.reviewId), eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "review"))).limit(1).then((rows) => rows[0]),
    ]);
    const definition = form ? intakeDefinition(form) : null; const submissionData = submission ? recordValue(submission.data) : {}; const reviewData = review ? recordValue(review.data) : {};
    if (!portal || !form || !submission || !review || !definition || definition.portalId !== portal.id || portal.portalType !== "client" || submission.parentObjectId !== form.id || review.parentObjectId !== submission.id || submissionData.clientPortalIntakeSubmission !== true || submissionData.stakeholderPortalId !== portal.id || submissionData.formObjectId !== form.id || reviewData.clientPortalIntakeReview !== true || reviewData.stakeholderPortalId !== portal.id || reviewData.formObjectId !== form.id || reviewData.submissionObjectId !== submission.id) throw new EosRouteError(404, "stakeholder_portal_intake_review_not_found", "The requested accountable onboarding review is unavailable.");
    const workPolicy = await authorizeAction(req, access, { authorityClass: "execute", resource: "work_packet", actionKey: "work_packet.create", purpose: "create_governed_work", classification: "confidential", consequence: "routine", targetSeatId: portal.ownerSeatId });
    const visible = await visibleSeatIds(access.company.id, access.seat.id, access.role);
    const process = input.processDefinitionId ? (await db.select().from(eosProcessDefinitions).where(and(eq(eosProcessDefinitions.id, input.processDefinitionId), eq(eosProcessDefinitions.companyId, access.company.id))).limit(1))[0] : null;
    if (input.processDefinitionId && (!process || !visible.has(process.accountableSeatId) || process.accountableSeatId !== portal.ownerSeatId || process.releaseState !== "released" || !["implemented", "pre_live_qualified", "field_qualified"].includes(process.qualificationState) || !mayAccessClassification(access, process.classification))) throw new EosRouteError(409, "stakeholder_portal_handoff_process_invalid", "Attach only a released, qualified process owned by this client workspace's accountable role.");
    const now = new Date(); const handoffId = randomUUID(); const workPacketId = randomUUID(); const agentEventId = randomUUID(); const handoffKey = `stakeholder-portal-intake-handoff:${review.id}`; const sourceLineage = JSON.stringify({ schemaVersion: "eos.stakeholder-portal-intake-handoff.v1", stakeholderPortalId: portal.id, formObjectId: form.id, submissionObjectId: submission.id, reviewObjectId: review.id, processDefinitionId: process?.id || null, clientInputBoundary: "unverified_client_input_reviewed_by_accountable_role" });
    const packet = { id: workPacketId, companyId: access.company.id, createdByUserId: req.user.id, accountableUserId: req.user.id, accountableSeatId: portal.ownerSeatId, title: input.title, objective: String(reviewData.nextAction || "Complete the accountable onboarding next action."), status: "ready", priority: input.priority, source: "manual", visibility: "company", classification: "confidential", requiresApproval: false, toolPack: ["forms", "projects"], evidenceRequirements: ["Review the client-provided onboarding input and independently validate any claim before relying on it."], capabilityInstanceId: null, processDefinitionId: process?.id || null, resourceIds: [], expectedOutput: "A completed, attributable onboarding handoff with any required Evidence and customer-facing consequence explicitly governed.", acceptanceCriteria: "The accountable owner records the outcome, retained limits, and any required Evidence before closing the Work Packet.", constraintsPolicies: "Client-supplied onboarding input remains unverified. This Work Packet does not grant access, start provider work, amend an agreement, or send a communication.", failureEscalationCompensation: "Keep the Work Packet open or blocked, preserve the review lineage, and request clarification through an authorized client channel.", humanFallback: "A founder or accountable human role reviews unresolved scope, access, contractual, or safety constraints.", sourceLineage, outputArtifactKeys: [], traceId: policy.traceId, correlationId: policy.correlationId, dueAt: input.dueAt ? new Date(input.dueAt) : null, createdAt: now, updatedAt: now } as const;
    const data = { clientPortalIntakeHandoff: true, stakeholderPortalId: portal.id, formObjectId: form.id, submissionObjectId: submission.id, reviewObjectId: review.id, workPacketId, processDefinitionId: process?.id || null, title: input.title, createdAt: now.toISOString(), handoffBoundary: "native_work_packet_only_no_provider_or_customer_effect" };
    const handoff = { id: handoffId, companyId: access.company.id, instrumentKey: "forms", objectType: "handoff", objectKey: handoffKey, title: `Client onboarding handoff · ${input.title}`, summary: `Owned work created from accountable client onboarding review: ${input.title}`, state: "completed", classification: "confidential", visibility: "organization", ownerSeatId: portal.ownerSeatId, parentObjectId: review.id, data, sourceReference: { authority: "native_eos", capability: "client_onboarding_handoff", stakeholderPortalId: portal.id, reviewObjectId: review.id, workPacketId, processDefinitionId: process?.id || null }, evidenceIds: [], contentSha256: nativeContractContentSha256({ schemaVersion: "eos.stakeholder-portal-intake-handoff.v1", companyId: access.company.id, portalId: portal.id, formId: form.id, submissionId: submission.id, reviewId: review.id, workPacketId, data }), version: 1, recordedByUserId: req.user.id, createdAt: now, updatedAt: now, archivedAt: null } as const;
    const agentEventPayload = { schemaVersion: "eos.stakeholder-portal-intake-handoff-event.v1", stakeholderPortalId: portal.id, formObjectId: form.id, submissionObjectId: submission.id, reviewObjectId: review.id, workPacketId, targetSeatId: portal.ownerSeatId, targetProcessDefinitionId: process?.id, priority: input.priority, classification: "confidential", verificationState: "unverified", externalEffectsExecuted: false };
    await db.transaction(async (tx) => { await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${`stakeholder-portal-intake-handoff:${review.id}`}))`); const [existing] = await tx.select({ id: eosInstrumentObjects.id }).from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectKey, handoffKey))).limit(1); if (existing) throw new EosRouteError(409, "stakeholder_portal_intake_handoff_exists", "This onboarding review already created an owned Work Packet."); await tx.insert(eosWorkPackets).values(packet); await tx.insert(eosInstrumentObjects).values(handoff); await tx.insert(eosAgentEventOutbox).values({ id: agentEventId, companyId: access.company.id, eventType: "eos.stakeholder_portal.intake.handed_off.v1", aggregateType: "stakeholder_portal_intake_handoff", aggregateId: handoffId, payload: agentEventPayload, state: "pending", attempts: 0, dispatchedRunIds: [], lastError: "", occurredAt: now, dispatchedAt: null, createdAt: now, updatedAt: now }); await tx.insert(eosAuditRecords).values([{ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.intake_handed_off", targetType: "stakeholder_portal_intake_handoff", targetId: handoffId, traceId: policy.traceId, correlationId: policy.correlationId, result: "work_packet_ready", details: { portalId: portal.id, formId: form.id, submissionId: submission.id, reviewId: review.id, workPacketId, handoffBoundary: data.handoffBoundary, policyDecisionId: policy.decisionId, workPolicyDecisionId: workPolicy.decisionId }, createdAt: now }, { id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "work_packet.created_from_client_onboarding_review", targetType: "work_packet", targetId: workPacketId, traceId: workPolicy.traceId, correlationId: workPolicy.correlationId, result: "ready", details: { stakeholderPortalId: portal.id, reviewId: review.id, handoffId, policyDecisionId: workPolicy.decisionId }, createdAt: now }, { id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "agent_event.recorded_from_client_onboarding_handoff", targetType: "agent_event", targetId: agentEventId, traceId: policy.traceId, correlationId: policy.correlationId, result: "pending", details: { eventType: "eos.stakeholder_portal.intake.handed_off.v1", handoffId, workPacketId, targetSeatId: portal.ownerSeatId, externalEffectsExecuted: false }, createdAt: now }]); });
    const agentEvent = await dispatchAgentEventOutboxEvent(agentEventId);
    res.status(201).json({ handoff: { id: handoff.id, workPacketId, processDefinitionId: process?.id || null, title: input.title, createdAt: data.createdAt }, workPacket: packet, agentEvent: agentEvent ? { id: agentEvent.event.id, eventType: agentEvent.event.eventType, state: agentEvent.event.state, runIds: agentEvent.runIds, replayed: agentEvent.replayed } : null, boundary: "A native Work Packet is ready for the accountable seat. EOS may notify only the eligible schedule for the selected role and process; it did not perform a provider, access, agreement, communication, or other client-facing effect." });
  }));

  app.patch("/api/eos/companies/:companyId/stakeholder-portals/:portalId", route(async (req, res) => {
    const input = stakeholderPortalTransitionSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.transition");
    const [portal] = await db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1);
    if (!portal) throw new EosRouteError(404, "stakeholder_portal_not_found", "Stakeholder portal not found."); if (portal.version !== input.expectedVersion) throw new EosRouteError(409, "stakeholder_portal_version_conflict", "The portal changed before this decision.");
    const transitions: Record<string, string[]> = { dormant: ["configuring", "retired"], configuring: ["active", "retired"], active: ["paused", "retired"], paused: ["active", "retired"] };
    if (!transitions[portal.state]?.includes(input.state)) throw new EosRouteError(409, "stakeholder_portal_transition_invalid", `Portal cannot move from ${portal.state} to ${input.state}.`);
    const activating = input.state === "active"; await evidenceFor(access.company.id, input.evidenceIds, activating);
    if (activating && input.evidenceIds.length < (Array.isArray(portal.activationRequirements) ? portal.activationRequirements.length : 1)) throw new EosRouteError(409, "stakeholder_portal_activation_incomplete", "Activation requires verified Evidence for every named activation requirement.");
    const now = new Date(); const [updated] = await db.update(eosStakeholderPortals).set({ state: input.state, activationEvidenceIds: activating ? input.evidenceIds : portal.activationEvidenceIds, activatedByUserId: activating ? req.user.id : portal.activatedByUserId, activatedAt: activating ? now : portal.activatedAt, version: portal.version + 1, updatedAt: now }).where(and(eq(eosStakeholderPortals.id, portal.id), eq(eosStakeholderPortals.version, portal.version))).returning();
    if (!updated) throw new EosRouteError(409, "stakeholder_portal_concurrent_change", "The portal changed before this decision.");
    await db.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.transitioned", targetType: "stakeholder_portal", targetId: portal.id, traceId: policy.traceId, correlationId: policy.correlationId, result: input.state, details: { from: portal.state, rationale: input.rationale, evidenceIds: input.evidenceIds, externallyAccessible: activating, policyDecisionId: policy.decisionId }, createdAt: now });
    res.json(updated);
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/publications", route(async (req, res) => {
    const input = stakeholderPublicationCreateSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_publication.create");
    const [portal] = await db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1);
    if (!portal || !Array.isArray(portal.visibleSections) || !portal.visibleSections.includes(input.section)) throw new EosRouteError(409, "stakeholder_publication_section_invalid", "Publication must use a configured portal section.");
    await evidenceFor(access.company.id, input.evidenceIds); const now = new Date(); const record = { id: randomUUID(), portalId: portal.id, companyId: access.company.id, ...input, state: "draft", version: 1, publishedByUserId: null, publishedAt: null, recordedByUserId: req.user.id, createdAt: now, updatedAt: now };
    await db.transaction(async (tx) => { await tx.insert(eosStakeholderPortalPublications).values(record); await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_publication.created", targetType: "stakeholder_publication", targetId: record.id, traceId: policy.traceId, correlationId: policy.correlationId, result: "draft", details: { portalId: portal.id, section: input.section, externallyVisible: false, policyDecisionId: policy.decisionId }, createdAt: now }); }); res.status(201).json(record);
  }));

  app.patch("/api/eos/companies/:companyId/stakeholder-portals/:portalId/publications/:publicationId", route(async (req, res) => {
    const input = stakeholderPublicationTransitionSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_publication.transition");
    const [publication] = await db.select().from(eosStakeholderPortalPublications).where(and(eq(eosStakeholderPortalPublications.id, req.params.publicationId), eq(eosStakeholderPortalPublications.portalId, req.params.portalId), eq(eosStakeholderPortalPublications.companyId, access.company.id))).limit(1);
    if (!publication) throw new EosRouteError(404, "stakeholder_publication_not_found", "Publication not found."); if (publication.version !== input.expectedVersion) throw new EosRouteError(409, "stakeholder_publication_version_conflict", "The publication changed before this decision.");
    if ((publication.state === "draft" && input.state !== "published") || (publication.state === "published" && input.state !== "withdrawn") || publication.state === "withdrawn") throw new EosRouteError(409, "stakeholder_publication_transition_invalid", `Publication cannot move from ${publication.state} to ${input.state}.`);
    await evidenceFor(access.company.id, publication.evidenceIds as string[], input.state === "published"); const now = new Date(); const [updated] = await db.update(eosStakeholderPortalPublications).set({ state: input.state, version: publication.version + 1, publishedByUserId: input.state === "published" ? req.user.id : publication.publishedByUserId, publishedAt: input.state === "published" ? now : publication.publishedAt, updatedAt: now }).where(and(eq(eosStakeholderPortalPublications.id, publication.id), eq(eosStakeholderPortalPublications.version, publication.version))).returning();
    await db.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_publication.transitioned", targetType: "stakeholder_publication", targetId: publication.id, traceId: policy.traceId, correlationId: policy.correlationId, result: input.state, details: { portalId: publication.portalId, from: publication.state, rationale: input.rationale, externallyVisible: input.state === "published", policyDecisionId: policy.decisionId }, createdAt: now }); res.json(updated);
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/access-grants", route(async (req, res) => {
    const input = stakeholderAccessGrantSchema.parse(req.body); const { access, policy } = await portalAccess(req, "stakeholder_portal.issue_access");
    const [portal] = await db.select().from(eosStakeholderPortals).where(and(eq(eosStakeholderPortals.id, req.params.portalId), eq(eosStakeholderPortals.companyId, access.company.id))).limit(1);
    if (!portal || portal.state !== "active") throw new EosRouteError(409, "stakeholder_portal_not_active", "Access can be issued only while the portal is active.");
    const [published, activeForms] = await Promise.all([
      db.select({ id: eosStakeholderPortalPublications.id }).from(eosStakeholderPortalPublications).where(and(eq(eosStakeholderPortalPublications.portalId, portal.id), eq(eosStakeholderPortalPublications.state, "published"))).limit(1),
      db.select().from(eosInstrumentObjects).where(and(eq(eosInstrumentObjects.companyId, access.company.id), eq(eosInstrumentObjects.instrumentKey, "forms"), eq(eosInstrumentObjects.objectType, "form"), eq(eosInstrumentObjects.state, "active"))),
    ]);
    const hasActiveIntake = activeForms.some((form) => intakeDefinition(form)?.portalId === portal.id);
    if (!published.length && !hasActiveIntake) throw new EosRouteError(409, "stakeholder_portal_empty", "Issue access only after an Evidence-backed publication or an active client onboarding intake is available.");
    const token = randomBytes(32).toString("base64url"); const now = new Date(); const record = { id: randomUUID(), portalId: portal.id, companyId: access.company.id, recipientLabel: input.recipientLabel, recipientIdentityHash: identityDigest(input.recipientIdentity), tokenHash: tokenDigest(token), state: "issued", expiresAt: new Date(input.expiresAt), lastAccessedAt: null, accessCount: 0, revokedAt: null, issuedByUserId: req.user.id, createdAt: now };
    await db.transaction(async (tx) => { await tx.insert(eosStakeholderPortalAccessGrants).values(record); await tx.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.access_issued", targetType: "stakeholder_portal_access", targetId: record.id, traceId: policy.traceId, correlationId: policy.correlationId, result: "issued", details: { portalId: portal.id, expiresAt: record.expiresAt.toISOString(), recipientIdentityHash: record.recipientIdentityHash, rationale: input.rationale, tokenDisclosedOnce: true, policyDecisionId: policy.decisionId }, createdAt: now }); });
    res.status(201).json({ grant: { ...record, tokenHash: undefined, recipientIdentityHash: undefined }, token, portalUrl: `/stakeholder/${token}` });
  }));

  app.post("/api/eos/companies/:companyId/stakeholder-portals/:portalId/access-grants/:grantId/revoke", route(async (req, res) => {
    const { access, policy } = await portalAccess(req, "stakeholder_portal.revoke_access"); const rationale = typeof req.body?.rationale === "string" ? req.body.rationale.trim() : ""; if (rationale.length < 20) throw new EosRouteError(400, "stakeholder_portal_rationale_required", "Revocation requires a rationale.");
    const [grant] = await db.select().from(eosStakeholderPortalAccessGrants).where(and(eq(eosStakeholderPortalAccessGrants.id, req.params.grantId), eq(eosStakeholderPortalAccessGrants.portalId, req.params.portalId), eq(eosStakeholderPortalAccessGrants.companyId, access.company.id))).limit(1); if (!grant) throw new EosRouteError(404, "stakeholder_access_not_found", "Access grant not found.");
    const now = new Date(); const [updated] = await db.update(eosStakeholderPortalAccessGrants).set({ state: "revoked", revokedAt: now }).where(eq(eosStakeholderPortalAccessGrants.id, grant.id)).returning(); await db.insert(eosAuditRecords).values({ id: randomUUID(), companyId: access.company.id, actorUserId: req.user.id, action: "stakeholder_portal.access_revoked", targetType: "stakeholder_portal_access", targetId: grant.id, traceId: policy.traceId, correlationId: policy.correlationId, result: "revoked", details: { portalId: grant.portalId, rationale, policyDecisionId: policy.decisionId }, createdAt: now }); res.json(updated);
  }));
}
