// lib/orchestrator/phases/backend-adapter.ts
// Phase 4: backend
//
// Generates Express route handlers, storage methods, Drizzle table schemas,
// and migration SQL for every endpoint in the spec's BackendSpec layer. Each
// endpoint is one work unit.
//
// Per orchestrator scoping rules, this adapter does NOT touch server/, shared/,
// or scripts/. Generated code is written to .planning/output/backend/<file> as
// review artifacts. The user copy/pastes (or runs a follow-up script) to wire
// them into the actual backend. The output object lists every file written so
// the orchestrator status can surface them.

import fs from "node:fs";
import path from "node:path";
import {
  type ProjectConfig,
} from "../../../shared/design-schema.js";
import type { SpecOutput, BackendEndpointSpec } from "@shared/spec-schema.js";
import { and, eq } from "drizzle-orm";
import { pipelinePages } from "../../../shared/design-schema.js";
import type { PhaseImplementation, PageWorkUnit } from "../phase-runner.js";
import { getOrchestratorDb } from "../db.js";
import {
  generateRouteCode,
  generateStorageCode,
} from "../../backend-wirer/route-generator.js";
import {
  generateSchemaCode,
  generateMigrationSQL,
} from "../../backend-wirer/schema-generator.js";
import type { BackendBrownfieldInventory } from "../../backend-wirer/types.js";

interface BackendRunInput {
  endpoint: BackendEndpointSpec;
  endpointIndex: number;
  tableHints: string[];
  outputDir: string;
}

async function loadLatestSpec(projectId: string): Promise<SpecOutput> {
  const db = getOrchestratorDb();
  const rows = await db
    .select()
    .from(pipelinePages)
    .where(
      and(
        eq(pipelinePages.projectId, projectId),
        eq(pipelinePages.phase, "spec"),
        eq(pipelinePages.status, "complete"),
      ),
    )
    .limit(1);
  if (rows.length === 0 || !rows[0].output) {
    throw new Error(
      `Phase "backend": no completed spec output found for projectId=${projectId}.`,
    );
  }
  return JSON.parse(rows[0].output) as SpecOutput;
}

function safeFileName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, "_").replace(/_+/g, "_");
}

function endpointBasename(endpoint: BackendEndpointSpec): string {
  const method = endpoint.method.toLowerCase();
  const tail = safeFileName(endpoint.path.replace(/^\/+/, "").replace(/\//g, "_"));
  return `${method}_${tail || "root"}`;
}

// Empty inventory — generated code is reviewed by the user before being
// pasted into the real server/, so collision data isn't load-bearing here.
const EMPTY_INVENTORY: BackendBrownfieldInventory = {
  existingRoutePaths: [],
  existingStorageFunctions: [],
  existingTableNames: [],
  routesInsertionOffset: -1,
  storageInsertionOffset: -1,
  schemaInsertionOffset: -1,
};

export const backendPhaseImplementation: PhaseImplementation = {
  async prepare(config: ProjectConfig): Promise<PageWorkUnit[]> {
    const projectRoot = path.resolve(config.repoPath);
    const spec = await loadLatestSpec(config.projectId);

    const backendSpec = spec.backendSpec;
    if (!backendSpec || backendSpec.endpoints.length === 0) {
      throw new Error(
        `Phase "backend": spec.backendSpec is empty. Either the spec phase ` +
          `failed to derive endpoints or the input spec has no backend layer.`,
      );
    }

    const outputDir = path.join(projectRoot, config.outputPath, "backend");
    fs.mkdirSync(outputDir, { recursive: true });

    return backendSpec.endpoints.map((endpoint, idx) => ({
      pageName: `${endpoint.method} ${endpoint.path}`,
      pageIndex: idx,
      input: {
        endpoint,
        endpointIndex: idx,
        tableHints: backendSpec.drizzleTableHints,
        outputDir,
      } satisfies BackendRunInput,
    }));
  },

  async runPage(rawInput: unknown, _config: ProjectConfig): Promise<unknown> {
    const input = rawInput as BackendRunInput;
    const { endpoint, outputDir } = input;

    const routeBlock = generateRouteCode(endpoint, EMPTY_INVENTORY);
    const storageBlock = generateStorageCode(endpoint);

    // Derive a table name from the endpoint path: /api/widgets → widgets
    const tableName =
      endpoint.path.split("/").filter((s) => s && s !== "api")[0] ?? "items";
    const fields = endpoint.requestBody.length > 0 ? endpoint.requestBody : ["name"];
    const schemaBlock = generateSchemaCode(tableName, fields);
    const migrationSQL = generateMigrationSQL([schemaBlock]);

    const base = endpointBasename(endpoint);
    const routeFile = path.join(outputDir, `${base}.route.ts`);
    const storageFile = path.join(outputDir, `${base}.storage.ts`);
    const schemaFile = path.join(outputDir, `${base}.schema.ts`);
    const migrationFile = path.join(outputDir, `${base}.migration.sql`);

    const routeContent = [
      "// AUTO-GENERATED by orchestrator backend phase. Review and paste into server/routes.ts.",
      routeBlock.zodSchemaCode ?? "",
      routeBlock.code,
    ]
      .filter(Boolean)
      .join("\n\n");

    const storageContent = [
      "// AUTO-GENERATED by orchestrator backend phase. Review and paste into server/storage.ts.",
      storageBlock.code,
    ].join("\n\n");

    const schemaContent = [
      "// AUTO-GENERATED by orchestrator backend phase. Review and paste into shared/schema.ts.",
      schemaBlock.drizzleCode,
      schemaBlock.zodInsertCode,
      schemaBlock.typeExportCode,
    ].join("\n\n");

    fs.writeFileSync(routeFile, routeContent, "utf-8");
    fs.writeFileSync(storageFile, storageContent, "utf-8");
    fs.writeFileSync(schemaFile, schemaContent, "utf-8");
    fs.writeFileSync(migrationFile, migrationSQL, "utf-8");

    return {
      endpointPath: endpoint.path,
      method: endpoint.method,
      tableName,
      generatedFiles: [routeFile, storageFile, schemaFile, migrationFile],
      note: "Generated as review artifacts. Paste into server/ and shared/ manually, then run drizzle-kit migrate.",
    };
  },
};
