// lib/orchestrator/phases/integration-adapter.ts
// Phase 3: integration
//
// prepare(): pull every completed react-gen page output for the project, fetch
//   each HTML by URL (presigned, can expire — surface 403/410 cleanly), and
//   audit the brownfield once. Read-only. The fetched HTMLs are passed in the
//   work unit input so runPage doesn't redo network work on retry.
//
// runPage(): translate HTML→TSX with shadcn, install missing components,
//   write the page file, inject the route into App.tsx, inject the nav item.
//   Returns the list of files touched.

import fs from "node:fs";
import path from "node:path";
import pLimit from "p-limit";
import { and, asc, eq } from "drizzle-orm";
import {
  pipelinePages,
  type ProjectConfig,
} from "../../../shared/design-schema.js";
import type { SpecOutput, PageSpecFull } from "@shared/spec-schema.js";
import type { PhaseImplementation, PageWorkUnit } from "../phase-runner.js";
import { getOrchestratorDb } from "../db.js";
import { auditBrownfield } from "../../code-integrator/brownfield-audit.js";
import { translateHtmlToShadcn } from "../../code-integrator/html-to-shadcn.js";
import {
  writePage,
  ensureShadcnComponents,
  toKebabCase,
  checkFileConflict,
} from "../../code-integrator/page-writer.js";
import { injectRoute } from "../../code-integrator/route-injector.js";
import { injectNavItem } from "../../code-integrator/nav-injector.js";
import {
  planBrownfieldIntegration,
  renderIntegrationPlanMarkdown,
  type IntegrationMode,
  type IntegrationPlanEntry,
} from "../../code-integrator/brownfield-planner.js";
import {
  buildSharedComponents,
  SHARED_LAYOUT_COMPONENTS,
} from "../../code-integrator/shared-components-builder.js";
import { runPageAgent } from "../../code-integrator/page-agent.js";
import { loadBrandVoice } from "../../spec-parser/brand-voice-inferrer.js";

interface IntegrationRunInput {
  page: PageSpecFull;
  htmlContent: string;
  installedComponents: string[];
  projectRoot: string;
  appTsxPath: string;
  sidebarPath: string;
  planEntry: IntegrationPlanEntry;
  /** TSX content pre-generated by a page sub-agent during prepare().
   *  When set, runPage() uses this directly instead of calling
   *  translateHtmlToShadcn(). */
  precomputedTsxContent?: string;
  /** Cached sub-agent error from parallel batch. When set, runPage throws. */
  precomputedError?: string;
}

/** Max concurrent page sub-agents. Anthropic API has generous rate limits but
 *  5 is a safe ceiling that balances throughput against blast radius on
 *  retriable failures. */
const PAGE_AGENT_PARALLEL_LIMIT = 5;

async function loadLatestSpec(projectId: string): Promise<SpecOutput> {
  const db = getOrchestratorDb();
  const rows = await db
    .select()
    .from(pipelinePages)
    .where(
      and(
        eq(pipelinePages.projectId, projectId),
        eq(pipelinePages.phase, "spec"),
        eq(pipelinePages.status, "complete"),
      ),
    )
    .limit(1);
  if (rows.length === 0 || !rows[0].output) {
    throw new Error(
      `Phase "integration": no completed spec output found for projectId=${projectId}.`,
    );
  }
  return JSON.parse(rows[0].output) as SpecOutput;
}

interface UiGenOutput {
  htmlUrl: string;
  screenshotUrl: string;
  tokenVersion: number;
  approved: boolean;
}

async function loadUiGenOutputs(
  projectId: string,
): Promise<{ pageIndex: number; pageName: string; output: UiGenOutput }[]> {
  const db = getOrchestratorDb();
  const rows = await db
    .select()
    .from(pipelinePages)
    .where(
      and(
        eq(pipelinePages.projectId, projectId),
        eq(pipelinePages.phase, "react-gen"),
        eq(pipelinePages.status, "complete"),
      ),
    )
    .orderBy(asc(pipelinePages.pageIndex));
  return rows
    .filter((r) => r.output)
    .map((r) => ({
      pageIndex: r.pageIndex,
      pageName: r.pageName,
      output: JSON.parse(r.output!) as UiGenOutput,
    }));
}

/**
 * Resolve a react-gen row to its spec page by **pageName**, not pageIndex.
 *
 * Historically the adapter did `spec.pages[row.pageIndex]`, which broke the
 * moment the spec was reordered or had pages inserted/removed between runs —
 * every react-gen row after the shift would map to the wrong spec page (wrong
 * filename, wrong content, silent data corruption).
 *
 * Name-based matching is stable across spec edits. Also returns the page's
 * **current** index in the spec so downstream code can surface a consistent
 * ordering to the integration planner and the phase-runner.
 *
 * Returns `null` if the row references a page that no longer exists in the
 * spec (e.g. a page was removed). Those rows are orphaned — caller should
 * log and skip them rather than silently integrating stale HTML.
 */
export function resolveRowToSpecPage(
  row: { pageIndex: number; pageName: string; output?: UiGenOutput },
  spec: SpecOutput,
): { page: PageSpecFull; currentSpecIndex: number } | null {
  const currentSpecIndex = spec.pages.findIndex((p) => p.name === row.pageName);
  if (currentSpecIndex === -1) return null;
  return { page: spec.pages[currentSpecIndex], currentSpecIndex };
}

// Best-effort remixicon class selection from a page name. Defaults to a
// generic layout icon. Caller can override later by editing sidebar.tsx.
function selectIconClass(pageName: string): string {
  const lc = pageName.toLowerCase();
  if (/dashboard|home/.test(lc)) return "ri-dashboard-line";
  if (/report/.test(lc)) return "ri-file-chart-line";
  if (/analytic|chart|metric/.test(lc)) return "ri-line-chart-line";
  if (/setting/.test(lc)) return "ri-settings-3-line";
  if (/user|team|member/.test(lc)) return "ri-user-line";
  if (/billing|payment/.test(lc)) return "ri-bank-card-line";
  if (/document|file/.test(lc)) return "ri-file-list-3-line";
  if (/message|chat|inbox/.test(lc)) return "ri-chat-3-line";
  if (/calendar|schedule/.test(lc)) return "ri-calendar-line";
  if (/task/.test(lc)) return "ri-task-line";
  return "ri-layout-line";
}

/**
 * Load per-page integration mode overrides from
 * `<outputPath>/integration/OVERRIDES.json`.
 *
 * File format: `{ "PageName": "skip" | "create" | "replace" | "merge" | "supplement" }`
 *
 * Missing file → empty overrides. Malformed JSON or invalid mode → throw
 * with the offending key/value so the user can fix it quickly instead of
 * silently ignoring a typo that would re-block the integration run.
 */
function loadIntegrationOverrides(
  projectRoot: string,
  outputPath: string,
): Record<string, IntegrationMode> {
  const overridesPath = path.join(
    projectRoot,
    outputPath,
    "integration",
    "OVERRIDES.json",
  );
  if (!fs.existsSync(overridesPath)) return {};

  const raw = fs.readFileSync(overridesPath, "utf-8").trim();
  if (!raw) return {};

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(
      `Phase "integration": OVERRIDES.json is not valid JSON. ` +
        `Fix ${overridesPath} and re-run. (${(err as Error).message})`,
    );
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(
      `Phase "integration": OVERRIDES.json must be an object mapping ` +
        `pageName → integration mode. Got ${typeof parsed} in ${overridesPath}.`,
    );
  }

  const validModes: ReadonlySet<IntegrationMode> = new Set<IntegrationMode>([
    "create",
    "replace",
    "merge",
    "supplement",
    "skip",
  ]);
  const out: Record<string, IntegrationMode> = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (typeof value !== "string" || !validModes.has(value as IntegrationMode)) {
      throw new Error(
        `Phase "integration": OVERRIDES.json has invalid mode "${String(value)}" ` +
          `for "${key}". Must be one of: create, replace, merge, supplement, skip.`,
      );
    }
    out[key] = value as IntegrationMode;
  }
  return out;
}

// ─── Preview helpers (Phase C) ───────────────────────────────────────────────

/**
 * Build the brownfield plan WITHOUT making any LLM calls or network fetches,
 * so the orchestrator can render it inside the approval gate before the user
 * decides whether to authorize the destructive phase.
 */
async function buildIntegrationPreview(config: ProjectConfig): Promise<string> {
  const projectRoot = path.resolve(config.repoPath);
  const spec = await loadLatestSpec(config.projectId);
  const uiGenRows = await loadUiGenOutputs(config.projectId);
  if (uiGenRows.length === 0) {
    return "(no completed react-gen pages — preview unavailable)";
  }

  const inventory = await auditBrownfield(projectRoot);
  const pagesDir = path.join(projectRoot, config.clientSrcPath, "pages");
  const pageSources: Record<string, string> = {};
  for (const ep of inventory.existingPages) {
    try {
      pageSources[ep.fileName] = fs.readFileSync(path.join(pagesDir, ep.fileName), "utf-8");
    } catch {
      // best-effort
    }
  }

  const onlySpecPagesWithUiGen = uiGenRows
    .map((row) => resolveRowToSpecPage(row, spec)?.page)
    .filter((p): p is PageSpecFull => Boolean(p));

  const overrides = loadIntegrationOverrides(projectRoot, config.outputPath);

  const plan = planBrownfieldIntegration({
    specPages: onlySpecPagesWithUiGen,
    inventory,
    pageSources,
    overrides,
  });

  return renderIntegrationPlanMarkdown(plan);
}

export const integrationPhaseImplementation: PhaseImplementation = {
  async previewForApproval(config: ProjectConfig): Promise<string> {
    return buildIntegrationPreview(config);
  },

  async prepare(config: ProjectConfig, runId?: number): Promise<PageWorkUnit[]> {
    const projectRoot = path.resolve(config.repoPath);
    const spec = await loadLatestSpec(config.projectId);
    const uiGenRows = await loadUiGenOutputs(config.projectId);

    if (uiGenRows.length === 0) {
      throw new Error(
        `Phase "integration": no completed react-gen pages for projectId=${config.projectId}. ` +
          `Run the react-gen phase first.`,
      );
    }

    // Snapshot the current state of client/src once. Each page-level work unit
    // gets a copy so runPage is independent of in-loop mutation.
    const inventory = await auditBrownfield(projectRoot);
    const installed = [...inventory.installedShadcnComponents];

    const appTsxPath = path.join(projectRoot, config.clientSrcPath, "App.tsx");
    const sidebarPath = path.join(
      projectRoot,
      config.clientSrcPath,
      "components",
      "sidebar.tsx",
    );

    // ── Phase B: brownfield planner ────────────────────────────────────────
    // Read every existing page's source (best-effort) so the planner can
    // detect behavior worth preserving (Firebase auth, custom data fetching).
    const pagesDir = path.join(projectRoot, config.clientSrcPath, "pages");
    const pageSources: Record<string, string> = {};
    for (const ep of inventory.existingPages) {
      try {
        pageSources[ep.fileName] = fs.readFileSync(
          path.join(pagesDir, ep.fileName),
          "utf-8",
        );
      } catch {
        // Best-effort; non-fatal.
      }
    }

    // Resolve each react-gen row to its current spec page by NAME.
    // Orphaned rows (page removed from spec) are logged and dropped.
    const resolvedRows: Array<{
      row: (typeof uiGenRows)[number];
      page: PageSpecFull;
      currentSpecIndex: number;
    }> = [];
    for (const row of uiGenRows) {
      const match = resolveRowToSpecPage(row, spec);
      if (!match) {
        console.warn(
          `[integration] react-gen row "${row.pageName}" (stored pageIndex=${row.pageIndex}) ` +
            `no longer exists in the spec — skipping. Delete the row if this is intentional.`,
        );
        continue;
      }
      resolvedRows.push({ row, page: match.page, currentSpecIndex: match.currentSpecIndex });
    }

    const onlySpecPagesWithUiGen = resolvedRows.map((r) => r.page);

    const overrides = loadIntegrationOverrides(projectRoot, config.outputPath);

    const plan = planBrownfieldIntegration({
      specPages: onlySpecPagesWithUiGen,
      inventory,
      pageSources,
      overrides,
    });

    // Write PLAN.md so the user can audit decisions before/after the run.
    const planDir = path.join(projectRoot, config.outputPath, "integration");
    fs.mkdirSync(planDir, { recursive: true });
    const planFile = path.join(planDir, "PLAN.md");
    fs.writeFileSync(planFile, renderIntegrationPlanMarkdown(plan), "utf-8");

    // Refuse to proceed if any entry needs human merge review. The user has
    // to resolve those by hand (edit PLAN.md and rerun, or fix the spec).
    const blockers = plan.entries.filter((e) => e.needsReview);
    if (blockers.length > 0) {
      const list = blockers
        .map((b) => `  - ${b.pageName} (${b.route}): ${b.rationale}`)
        .join("\n");
      throw new Error(
        `Phase "integration": ${blockers.length} page(s) need human merge ` +
          `review before integration can proceed. See ${planFile}\n${list}`,
      );
    }

    // ── Build shared layout components first (blocking) ───────────────────
    // Page sub-agents depend on @/components/layout/* imports — so these
    // files must exist before any page agent runs.
    const designSystemPath = path.resolve(projectRoot, config.designSystemPath);
    const designSystem = fs.existsSync(designSystemPath)
      ? fs.readFileSync(designSystemPath, "utf-8")
      : "(design system file missing — sub-agents will use defaults)";
    const planningDir = path.resolve(projectRoot, ".planning");
    const brandVoice = loadBrandVoice(planningDir);

    await buildSharedComponents({
      projectRoot,
      clientSrcPath: config.clientSrcPath,
      designSystem,
      brandVoice,
    });

    // Which pages are already complete in this run? Skip re-generation for
    // those so the parallel batch only works on the remaining set.
    const completePageIndexes = new Set<number>();
    if (runId !== undefined) {
      const db = getOrchestratorDb();
      const existingRows = await db
        .select()
        .from(pipelinePages)
        .where(
          and(
            eq(pipelinePages.runId, runId),
            eq(pipelinePages.phase, "integration"),
            eq(pipelinePages.status, "complete"),
          ),
        );
      for (const r of existingRows) completePageIndexes.add(r.pageIndex);
    }

    // Index plan entries by page name for runPage lookup.
    const planByName = new Map(plan.entries.map((e) => [e.pageName, e]));
    const sharedComponentNames = SHARED_LAYOUT_COMPONENTS.map((c) => c.name);

    // Build base work unit inputs for every react-gen page. HTML is loaded from
    // the locally cached file (written by react-gen phase at generation time),
    // which is immune to URL expiry.
    //
    // Iterate over the name-resolved rows, NOT the raw uiGenRows — the raw
    // row's pageIndex may be stale relative to the current spec order, so we
    // use `currentSpecIndex` for all downstream indexing (plan lookup,
    // complete-page filter, work-unit pageIndex).
    const previewsDir = path.join(projectRoot, config.outputPath, "previews");
    const baseWork: Array<{ unit: PageWorkUnit; needsAgent: boolean }> = [];
    for (const { row, page, currentSpecIndex } of resolvedRows) {
      const planEntry = planByName.get(page.name);
      if (!planEntry) continue;

      const skipMode = planEntry.mode === "skip";
      const alreadyComplete = completePageIndexes.has(currentSpecIndex);

      let htmlContent = "";
      if (!skipMode) {
        const localHtmlPath = path.join(previewsDir, `${page.name}.html`);
        if (fs.existsSync(localHtmlPath)) {
          htmlContent = fs.readFileSync(localHtmlPath, "utf-8");
        } else if (row.output.htmlUrl && row.output.htmlUrl !== "expired") {
          // Fallback to presigned URL for older runs without local cache.
          try {
            const resp = await fetch(row.output.htmlUrl);
            if (resp.ok) htmlContent = await resp.text();
          } catch {
            // Presigned URL may be expired; leave htmlContent empty so the
            // sub-agent will fail loudly on this page (caught in batch below).
          }
        }
      }

      const input: IntegrationRunInput = {
        page,
        htmlContent,
        installedComponents: installed,
        projectRoot,
        appTsxPath,
        sidebarPath,
        planEntry,
      };

      baseWork.push({
        unit: {
          pageName: page.name,
          pageIndex: currentSpecIndex,
          input,
        },
        needsAgent: !skipMode && !alreadyComplete && htmlContent.length > 0,
      });
    }

    // ── Parallel page sub-agents ───────────────────────────────────────────
    // Spawn one agent per page (bounded by PAGE_AGENT_PARALLEL_LIMIT). Each
    // failure is captured on its work unit — the batch does not short-circuit.
    const pending = baseWork.filter((w) => w.needsAgent);
    if (pending.length > 0) {
      console.log(
        `[integration] Spawning ${pending.length} parallel page sub-agent(s), ` +
          `concurrency=${PAGE_AGENT_PARALLEL_LIMIT}`,
      );
      const limit = pLimit(PAGE_AGENT_PARALLEL_LIMIT);
      const results = await Promise.allSettled(
        pending.map((w) =>
          limit(async () => {
            const input = w.unit.input as IntegrationRunInput;
            const result = await runPageAgent({
              pageName: input.page.name,
              pageRoute: input.page.route,
              authLevel: input.page.authLevel,
              htmlContent: input.htmlContent,
              pageSpec: input.page,
              designSystem,
              brandVoice,
              sharedComponents: sharedComponentNames,
              installedComponents: input.installedComponents,
            });
            return { pageName: input.page.name, tsxContent: result.tsxContent };
          }),
        ),
      );

      let ok = 0;
      for (let i = 0; i < results.length; i++) {
        const target = pending[i].unit.input as IntegrationRunInput;
        const result = results[i];
        if (result.status === "fulfilled") {
          target.precomputedTsxContent = result.value.tsxContent;
          ok++;
          console.log(`[integration] Agent OK: ${result.value.pageName}`);
        } else {
          const msg = result.reason instanceof Error ? result.reason.message : String(result.reason);
          target.precomputedError = msg;
          console.error(`[integration] Agent FAILED: ${target.page.name} — ${msg}`);
        }
      }
      console.log(`[integration] Sub-agent batch complete: ${ok}/${results.length} ok`);
    }

    return baseWork.map((w) => w.unit);
  },

  async runPage(rawInput: unknown, _config: ProjectConfig): Promise<unknown> {
    const input = rawInput as IntegrationRunInput;
    const { page, htmlContent, installedComponents, projectRoot, appTsxPath, sidebarPath, planEntry } = input;

    // If the parallel sub-agent batch captured an error for this page,
    // surface it now so the phase runner marks the page failed.
    if (input.precomputedError) {
      throw new Error(input.precomputedError);
    }

    // ── Mode dispatch (Phase B) ────────────────────────────────────────────
    // The planner already decided what to do with this page. runPage is just
    // the executor — it never re-classifies and never silently skips on a
    // file conflict.

    if (planEntry.mode === "skip") {
      return {
        pageFile: planEntry.existingFile,
        mode: "skip",
        rationale: planEntry.rationale,
      };
    }

    // create / replace / supplement all need a translated TSX file. Only the
    // overwrite + delete-old-file behavior differs.
    if (planEntry.mode === "merge") {
      // Defensive: prepare() should already have blocked this. If we got
      // here, refuse to touch the page rather than guess.
      throw new Error(
        `integration: page "${page.name}" is mode=merge and requires human review`,
      );
    }

    // For replace mode, we sanity-check the existing file is actually present
    // (the inventory may be stale if a hand edit removed it between phases).
    const overwrite = planEntry.mode === "replace";
    if (overwrite && planEntry.existingFile) {
      // Note: we are about to overwrite — record the old path so the result
      // surfaces it for the audit log.
    }

    // For create mode, surface a hard error if the target file mysteriously
    // already exists (the planner thought it didn't). That's a real conflict
    // worth stopping for, not a silent skip.
    if (planEntry.mode === "create") {
      const conflict = await checkFileConflict({ projectRoot, pageName: page.name });
      if (conflict.exists) {
        throw new Error(
          `integration: planner said create for "${page.name}" but ` +
            `${conflict.existingPath} already exists. Stale inventory? Re-run ` +
            `the integration phase or change the spec page name.`,
        );
      }
    }

    // 1. HTML → TSX. Prefer the TSX pre-generated by the parallel sub-agent
    //    batch in prepare(); fall back to the single-call translator if no
    //    cache is present (legacy callers / per-page reruns).
    let translation: { tsxContent: string; extractedImports: string[] };
    if (input.precomputedTsxContent) {
      const tsx = input.precomputedTsxContent;
      const importRegex = /@\/components\/ui\/([\w-]+)/g;
      const extracted = new Set<string>();
      let m: RegExpExecArray | null;
      while ((m = importRegex.exec(tsx)) !== null) extracted.add(m[1]);
      translation = { tsxContent: tsx, extractedImports: Array.from(extracted) };
    } else {
      translation = await translateHtmlToShadcn({
        htmlContent,
        pageName: page.name,
        pageRoute: page.route,
        installedComponents,
        authLevel: page.authLevel,
      });
    }

    // 2. Install missing shadcn components
    const installed = await ensureShadcnComponents({
      projectRoot,
      extractedImports: translation.extractedImports,
      installedComponents,
    });

    // 3. Write the page file. Overwrite for replace mode; fresh write
    // otherwise. For supplement mode, the writer falls back to
    // `<name>-page-new.tsx` on filename collision and banners the file
    // for manual merge review.
    const pageFile = await writePage({
      projectRoot,
      pageName: page.name,
      tsxContent: translation.tsxContent,
      overwrite,
      mode: planEntry.mode,
    });

    // 4. Inject route (idempotent — Phase A). For replace mode, the existing
    // route entry stays in place if it already points at the same import
    // path; otherwise the injector adds the new route alongside.
    const componentName = page.name;
    const importPath = `@/pages/${toKebabCase(page.name)}-page`;
    const isStandalone = page.authLevel === "public";
    const routeResult = await injectRoute({
      appTsxPath,
      componentName,
      importPath,
      routePath: page.route,
      wrapCompanyGate: !isStandalone,
      isStandalone,
      pageFilePath: pageFile,
    });

    // 5. Inject nav item (only for authenticated, non-standalone pages)
    let navInjected = false;
    if (!isStandalone) {
      await injectNavItem({
        sidebarPath,
        label: page.name,
        href: page.route,
        iconClass: selectIconClass(page.name),
      });
      navInjected = true;
    }

    return {
      pageFile,
      mode: planEntry.mode,
      replacedFile: overwrite ? planEntry.existingFile : null,
      componentName: routeResult.componentName,
      renamedToAvoidCollision: routeResult.renamed,
      routeInjected: true,
      navInjected,
      installedShadcn: installed,
    };
  },
};
