$ErrorActionPreference = "Stop"

$required = @(
  "ANTHROPIC_API_KEY",
  "VITE_CLERK_PUBLISHABLE_KEY",
  "CLERK_PUBLISHABLE_KEY",
  "CLERK_SECRET_KEY",
  "DATABASE_URL",
  "SESSION_SECRET",
  "EOS_CREDENTIAL_ENCRYPTION_KEY",
  "EOS_PUBLIC_ORIGIN",
  "EOS_ALERT_WEBHOOK_URL",
  "EOS_ALERT_WEBHOOK_SECRET",
  "STRIPE_RESTRICTED_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "EOS_STRIPE_PLANS",
  "EOS_PLATFORM_ADMIN_USER_IDS",
  "EOS_ACCOUNT_DELETION_ENABLED",
  "EOS_LEGAL_ENFORCEMENT",
  "EOS_PUBLIC_PAID_SAAS",
  "VITE_POSTHOG_API_KEY",
  "POSTHOG_API_KEY",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GOOGLE_REDIRECT_URI",
  "NOTION_API_KEY"
)

foreach ($name in $required) {
  if (-not [Environment]::GetEnvironmentVariable($name)) {
    throw "Missing required release variable: $name"
  }
}

npm run release:verify
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

flyctl secrets set --app eos-app --stage `
  "ANTHROPIC_API_KEY=$env:ANTHROPIC_API_KEY" `
  "CLERK_PUBLISHABLE_KEY=$env:CLERK_PUBLISHABLE_KEY" `
  "CLERK_SECRET_KEY=$env:CLERK_SECRET_KEY" `
  "DATABASE_URL=$env:DATABASE_URL" `
  "SESSION_SECRET=$env:SESSION_SECRET" `
  "EOS_CREDENTIAL_ENCRYPTION_KEY=$env:EOS_CREDENTIAL_ENCRYPTION_KEY" `
  "EOS_PUBLIC_ORIGIN=$env:EOS_PUBLIC_ORIGIN" `
  "EOS_ALERT_WEBHOOK_URL=$env:EOS_ALERT_WEBHOOK_URL" `
  "EOS_ALERT_WEBHOOK_SECRET=$env:EOS_ALERT_WEBHOOK_SECRET" `
  "STRIPE_RESTRICTED_KEY=$env:STRIPE_RESTRICTED_KEY" `
  "STRIPE_WEBHOOK_SECRET=$env:STRIPE_WEBHOOK_SECRET" `
  "EOS_STRIPE_PLANS=$env:EOS_STRIPE_PLANS" `
  "EOS_PLATFORM_ADMIN_USER_IDS=$env:EOS_PLATFORM_ADMIN_USER_IDS" `
  "EOS_ACCOUNT_DELETION_ENABLED=$env:EOS_ACCOUNT_DELETION_ENABLED" `
  "EOS_LEGAL_ENFORCEMENT=$env:EOS_LEGAL_ENFORCEMENT" `
  "EOS_PUBLIC_PAID_SAAS=$env:EOS_PUBLIC_PAID_SAAS" `
  "POSTHOG_API_KEY=$env:POSTHOG_API_KEY" `
  "GOOGLE_CLIENT_ID=$env:GOOGLE_CLIENT_ID" `
  "GOOGLE_CLIENT_SECRET=$env:GOOGLE_CLIENT_SECRET" `
  "GOOGLE_REDIRECT_URI=$env:GOOGLE_REDIRECT_URI" `
  "NOTION_API_KEY=$env:NOTION_API_KEY"

if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

flyctl deploy --app eos-app `
  --build-arg "VITE_CLERK_PUBLISHABLE_KEY=$env:VITE_CLERK_PUBLISHABLE_KEY" `
  --build-arg "VITE_POSTHOG_API_KEY=$env:VITE_POSTHOG_API_KEY"

exit $LASTEXITCODE
