import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ClipboardCheck, PlayCircle, RefreshCw, Rocket, ShieldCheck } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { artifactClosureApplicability, artifactClosureMaturity } from "@shared/artifact-closure";
import type { EosActiveModule } from "@shared/eos-runtime";

type Row = Record<string, any>;
type Props = { root: string; module: EosActiveModule; canExecute: boolean; canDecide: boolean };
const field = "h-10 w-full rounded-md border border-input bg-background px-3 text-sm";
const humanize = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
function scopedUrl(url: string) { if (typeof window === "undefined") return url; const seat = new URLSearchParams(window.location.search).get("seat"); if (!seat) return url; const scoped = new URL(url, window.location.origin); scoped.searchParams.set("seatId", seat); return `${scoped.pathname}${scoped.search}`; }
async function json(method: "GET" | "POST" | "PATCH", url: string, body?: unknown) { return (await apiRequest(method, scopedUrl(url), body) as Response).json(); }

export function ArtifactClosureControlCenter({ root, module, canExecute, canDecide }: Props) {
  const endpoint = `${root}/artifact-closure`; const queryClient = useQueryClient(); const { toast } = useToast();
  const state = useQuery<Row>({ queryKey: [endpoint, module.id], queryFn: () => json("GET", `${endpoint}?moduleId=${module.id}`) });
  const qualification = useQuery<Row>({ queryKey: [endpoint, "qualification-runs"], queryFn: () => json("GET", `${endpoint}/qualification-runs`) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: [endpoint] });
  const [selectedCapability, setSelectedCapability] = useState("");
  const [customCapabilityKey, setCustomCapabilityKey] = useState(`module-${module.id}`);
  const [ownerSeatId, setOwnerSeatId] = useState("");
  const [selectedRecordId, setSelectedRecordId] = useState("");
  const [selectedRunId, setSelectedRunId] = useState("");
  const [runForm, setRunForm] = useState({ title: "Company pre-live qualification", objective: "Prove the selected operating modules through the mandatory synthetic success, denial, failure, recovery, rollback, isolation, and audit scenarios.", moduleIds: [module.id], ownerSeatId: "" });
  const [transitionRationale, setTransitionRationale] = useState("The accountable operator reviewed the current scope, closure gates, and evidence limitations before this transition.");
  const [scenarioForms, setScenarioForms] = useState<Record<string, { status: string; ownerSeatId: string; evidenceId: string; resultSummary: string; blocker: string }>>({});
  const [releaseForm, setReleaseForm] = useState({ decision: "released", evidenceId: "", rationale: "The founder reviewed the complete synthetic qualification record, independent artifact closure, remaining field boundaries, and authorizes the declared pre-live release scope." });
  const [form, setForm] = useState({ applicability: "missing", maturity: "doctrine", ownerSeatId: "", templateStack: "", evidenceId: "", blocker: "", nextAction: "", rationale: "", triggerCondition: "", classification: "confidential" });
  const records = state.data?.records || []; const groups = state.data?.groups || []; const selectedRecord = records.find((item: Row) => item.id === selectedRecordId);
  const mappedCapabilities = (state.data?.capabilities || []).filter((item: Row) => Array.isArray(item.moduleIds) && item.moduleIds.includes(module.id) && !["dormant", "deprecated"].includes(item.state));
  const selectedCapabilityRecord = (state.data?.capabilities || []).find((item: Row) => item.id === selectedCapability);
  const selectedGroupKey = selectedRecord ? `${selectedRecord.moduleId}:${selectedRecord.capabilityKey}` : "";
  const selectedGroup = groups.find((item: Row) => item.key === selectedGroupKey);
  const runs = qualification.data?.runs || []; const selectedRun = runs.find((item: Row) => item.id === selectedRunId) || runs[0];
  const groupRecords = useMemo(() => selectedRecord ? records.filter((item: Row) => item.capabilityKey === selectedRecord.capabilityKey) : [], [records, selectedRecord?.capabilityKey]);

  useEffect(() => { setCustomCapabilityKey(`module-${module.id}`); setSelectedCapability(""); setSelectedRecordId(""); setRunForm((value) => ({ ...value, moduleIds: [module.id] })); }, [module.id]);
  useEffect(() => { if (!ownerSeatId && state.data?.seats?.[0]?.id) setOwnerSeatId(state.data.seats[0].id); }, [state.data?.seats, ownerSeatId]);
  useEffect(() => { if (!runForm.ownerSeatId && state.data?.seats?.[0]?.id) setRunForm((value) => ({ ...value, ownerSeatId: state.data.seats[0].id })); }, [state.data?.seats, runForm.ownerSeatId]);
  useEffect(() => { if (!selectedRunId && runs[0]?.id) setSelectedRunId(runs[0].id); }, [runs, selectedRunId]);
  useEffect(() => {
    if (!selectedRecord) return;
    setForm({ applicability: selectedRecord.applicability, maturity: selectedRecord.maturity, ownerSeatId: selectedRecord.ownerSeatId, templateStack: (selectedRecord.templateStack || []).join(", "), evidenceId: selectedRecord.evidenceIds?.[0] || "", blocker: selectedRecord.blocker || "", nextAction: selectedRecord.nextAction || "", rationale: selectedRecord.rationale || "", triggerCondition: selectedRecord.triggerCondition || "", classification: selectedRecord.classification });
  }, [selectedRecord?.id, selectedRecord?.version]);

  const initialize = useMutation({ mutationFn: () => json("POST", `${endpoint}/initialize`, { moduleId: module.id, capabilityKey: selectedCapabilityRecord?.key || customCapabilityKey.trim(), capabilityInstanceId: selectedCapabilityRecord?.id || undefined, ownerSeatId, templateStack: [], classification: "confidential" }), onSuccess: async (value: Row) => { await refresh(); toast({ title: value.inserted ? "Artifact closure matrix initialized" : "Artifact closure matrix already complete", description: `${value.inserted} of ${value.totalRequired} required artifact rows were created without asserting readiness.` }); }, onError: (error) => toast({ title: "Matrix initialization failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const initializeMapped = useMutation({ mutationFn: () => json("POST", `${endpoint}/initialize-module`, { moduleId: module.id, classification: "confidential" }), onSuccess: async (value: Row) => { await refresh(); toast({ title: value.inserted ? "Mapped capability coverage initialized" : "Mapped capability coverage already complete", description: `${value.capabilityGroups} visible capability ${value.capabilityGroups === 1 ? "matrix" : "matrices"}; ${value.inserted} conservative artifact rows added.` }); }, onError: (error) => toast({ title: "Mapped capability initialization failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const initializeCompany = useMutation({ mutationFn: () => json("POST", `${endpoint}/initialize-company`, { classification: "confidential" }), onSuccess: async (value: Row) => { await refresh(); toast({ title: value.inserted ? "Company evidence coverage initialized" : "Company evidence coverage already complete", description: `${value.capabilityGroups} capability-module matrices across ${value.moduleIds.length} modules; ${value.inserted} conservative rows added.` }); }, onError: (error) => toast({ title: "Company initialization failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const createRun = useMutation({ mutationFn: () => json("POST", `${endpoint}/qualification-runs`, { ...runForm, classification: "confidential" }), onSuccess: async (value: Row) => { await refresh(); setSelectedRunId(value.id); toast({ title: "Qualification campaign created", description: "The exact module and capability scope was frozen as a draft without asserting readiness." }); }, onError: (error) => toast({ title: "Campaign creation failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const startRun = useMutation({ mutationFn: () => json("POST", `${endpoint}/qualification-runs/${selectedRun.id}/start`, { expectedVersion: selectedRun.version, rationale: transitionRationale }), onSuccess: async () => { await refresh(); toast({ title: "Mandatory rehearsal started", description: "Seven evidence-gated success, denial, failure, recovery, rollback, isolation, and audit scenarios are now active." }); }, onError: (error) => toast({ title: "Campaign start blocked", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const updateScenario = useMutation({ mutationFn: ({ scenario, form }: { scenario: Row; form: Row }) => json("PATCH", `${endpoint}/qualification-runs/${selectedRun.id}/scenarios/${scenario.id}`, { expectedVersion: scenario.version, status: form.status, ownerSeatId: form.ownerSeatId || scenario.ownerSeatId, evidenceIds: form.evidenceId ? [form.evidenceId] : [], resultSummary: form.resultSummary, blocker: form.blocker }), onSuccess: async () => { await refresh(); toast({ title: "Scenario receipt recorded", description: "The evidence-backed result, run state, immutable event, and audit receipt were updated together." }); }, onError: (error) => toast({ title: "Scenario result rejected", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const qualifyRun = useMutation({ mutationFn: () => json("POST", `${endpoint}/qualification-runs/${selectedRun.id}/qualify`, { expectedVersion: selectedRun.version, rationale: transitionRationale }), onSuccess: async () => { await refresh(); toast({ title: "Synthetic pre-live run qualified", description: "All seven mandatory scenarios passed. Independent artifact promotion is still required before founder release." }); }, onError: (error) => toast({ title: "Qualification gate blocked", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const releaseRun = useMutation({ mutationFn: () => json("POST", `${endpoint}/qualification-runs/${selectedRun.id}/release`, { expectedVersion: selectedRun.version, decision: releaseForm.decision, evidenceIds: releaseForm.evidenceId ? [releaseForm.evidenceId] : [], rationale: releaseForm.rationale }), onSuccess: async (value: Row) => { await refresh(); toast({ title: value.status === "released" ? "Pre-live release authorized" : "Pre-live release rejected", description: "The founder decision and evidence boundary are preserved in the immutable campaign history." }); }, onError: (error) => toast({ title: "Founder decision rejected", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });
  const update = useMutation({ mutationFn: () => json("PATCH", `${endpoint}/${selectedRecord.id}`, { expectedVersion: selectedRecord.version, ...form, templateStack: form.templateStack.split(",").map((item) => item.trim()).filter(Boolean), evidenceIds: form.evidenceId ? [form.evidenceId] : [] }), onSuccess: async () => { await refresh(); toast({ title: "Artifact closure decision recorded", description: "The current record, immutable change receipt, policy decision, and audit history were updated atomically." }); }, onError: (error) => toast({ title: "Artifact closure update failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }) });

  if (state.isLoading) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Loading artifact closure…</CardContent></Card>;
  if (state.isError) return <Alert variant="destructive"><AlertTriangle className="h-4 w-4"/><AlertTitle>Artifact closure unavailable</AlertTitle><AlertDescription>EOS will not infer implementation or qualification state while the governed ledger is unavailable.</AlertDescription></Alert>;

  return <div className="space-y-5" id="artifact-closure-control-center">
    <Card className="border-primary/15"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5"/>Artifact closure &amp; pre-live activation</CardTitle><CardDescription className="mt-1">Prove all 22 required artifact classes for each active capability in Module {module.id}. Missing, mapped, implemented, pre-live, field, and native are deliberately different states.</CardDescription></div><Button variant="outline" size="sm" onClick={() => refresh()} disabled={state.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${state.isFetching ? "animate-spin" : ""}`}/>Refresh</Button></div></CardHeader><CardContent className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Capability groups", state.data?.counts?.capabilityGroups], ["Open blockers", state.data?.counts?.blockers], ["Artifact complete", state.data?.counts?.artifactComplete], ["Pre-live qualified", state.data?.counts?.preLiveQualified], ["Native qualified", state.data?.counts?.nativeQualified]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-muted p-3"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value || 0}</p></div>)}</div>
      <Alert><ShieldCheck className="h-4 w-4"/><AlertTitle>Evidence boundary</AlertTitle><AlertDescription>{state.data?.boundary}</AlertDescription></Alert>
      {canExecute && <div className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium">Mapped capability coverage</p><p className="text-xs text-muted-foreground">{mappedCapabilities.length ? `${mappedCapabilities.length} visible non-dormant ${mappedCapabilities.length === 1 ? "capability is" : "capabilities are"} assigned to this module.` : "No visible capability is assigned to this module yet. Assign one in Operations before bulk initialization."}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={initializeCompany.isPending || initializeMapped.isPending || initialize.isPending} onClick={() => initializeCompany.mutate()}>{initializeCompany.isPending ? "Initializing company…" : "Initialize entire company"}</Button><Button variant="secondary" disabled={!mappedCapabilities.length || initializeCompany.isPending || initializeMapped.isPending || initialize.isPending} onClick={() => initializeMapped.mutate()}>{initializeMapped.isPending ? "Initializing…" : "Initialize this module"}</Button></div></div><div className="grid gap-2 md:grid-cols-4"><select aria-label="Existing capability instance" className={field} value={selectedCapability} onChange={(event) => { setSelectedCapability(event.target.value); const capability = state.data?.capabilities?.find((item: Row) => item.id === event.target.value); if (capability) setOwnerSeatId(capability.ownerSeatId); }}><option value="">Module-level or custom capability</option>{mappedCapabilities.map((item: Row) => <option key={item.id} value={item.id}>{item.name} · {item.state}</option>)}</select><Input aria-label="Capability key" disabled={Boolean(selectedCapability)} value={selectedCapabilityRecord?.key || customCapabilityKey} onChange={(event) => setCustomCapabilityKey(event.target.value)} placeholder="Canonical capability key"/><select aria-label="Artifact closure owner" className={field} value={ownerSeatId} onChange={(event) => setOwnerSeatId(event.target.value)}><option value="">Choose accountable seat</option>{(state.data?.seats || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Button disabled={!ownerSeatId || !(selectedCapabilityRecord?.key || customCapabilityKey.trim()) || initializeCompany.isPending || initializeMapped.isPending || initialize.isPending} onClick={() => initialize.mutate()}>Initialize custom matrix</Button></div></div>}
    </CardContent></Card>

    <Card className="border-primary/15" id="pre-live-qualification-campaign">
      <CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Rocket className="h-5 w-5"/>Pre-live qualification campaign</CardTitle><CardDescription className="mt-1">Operate one governed Client Zero rehearsal across selected modules. Seven mandatory scenarios, verified Evidence, an independent closure gate, and a founder release decision prevent narrative-only readiness.</CardDescription></div><Button variant="outline" size="sm" onClick={() => refresh()} disabled={qualification.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${qualification.isFetching ? "animate-spin" : ""}`}/>Refresh</Button></div></CardHeader>
      <CardContent className="space-y-5">
        <Alert><ShieldCheck className="h-4 w-4"/><AlertTitle>Qualification boundary</AlertTitle><AlertDescription>{qualification.data?.boundary || "Synthetic qualification, field qualification, and native qualification remain separate states."}</AlertDescription></Alert>
        {canExecute && <div className="space-y-3 rounded-xl border p-4"><div><p className="font-medium">Create a bounded campaign</p><p className="text-xs text-muted-foreground">Choose the exact modules. EOS freezes their visible active capability scope and current closure state; creation itself claims nothing.</p></div><div className="grid gap-2 md:grid-cols-2"><Input aria-label="Qualification campaign title" value={runForm.title} onChange={(event) => setRunForm((value) => ({ ...value, title: event.target.value }))}/><select aria-label="Qualification owner" className={field} value={runForm.ownerSeatId} onChange={(event) => setRunForm((value) => ({ ...value, ownerSeatId: event.target.value }))}><option value="">Choose accountable seat</option>{(state.data?.seats || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Textarea className="md:col-span-2" aria-label="Qualification objective" value={runForm.objective} onChange={(event) => setRunForm((value) => ({ ...value, objective: event.target.value }))}/></div><div><p className="mb-2 text-xs font-medium">Module scope</p><div className="flex flex-wrap gap-2">{Array.from({ length: 14 }, (_, index) => index + 1).map((moduleId) => <button type="button" key={moduleId} aria-pressed={runForm.moduleIds.includes(moduleId)} className={`h-9 min-w-9 rounded-lg border px-3 text-sm ${runForm.moduleIds.includes(moduleId) ? "border-primary bg-primary text-primary-foreground" : "hover:bg-muted"}`} onClick={() => setRunForm((value) => ({ ...value, moduleIds: value.moduleIds.includes(moduleId) ? value.moduleIds.filter((item) => item !== moduleId) : [...value.moduleIds, moduleId].sort((a, b) => a - b) }))}>{moduleId}</button>)}</div></div><Button disabled={createRun.isPending || runForm.title.trim().length < 5 || runForm.objective.trim().length < 20 || !runForm.ownerSeatId || !runForm.moduleIds.length} onClick={() => createRun.mutate()}>{createRun.isPending ? "Creating campaign…" : "Create qualification campaign"}</Button></div>}

        {qualification.isLoading ? <p className="text-sm text-muted-foreground">Loading qualification campaigns…</p> : qualification.isError ? <Alert variant="destructive"><AlertTriangle className="h-4 w-4"/><AlertTitle>Qualification campaigns unavailable</AlertTitle><AlertDescription>EOS will not infer pre-live readiness while its governed campaign ledger is unavailable.</AlertDescription></Alert> : runs.length ? <div className="space-y-4">
          <select aria-label="Qualification campaign" className={field} value={selectedRun?.id || ""} onChange={(event) => setSelectedRunId(event.target.value)}>{runs.map((run: Row) => <option key={run.id} value={run.id}>{run.title} · {humanize(run.status)} · v{run.version}</option>)}</select>
          {selectedRun && <div className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{selectedRun.title}</p><p className="text-xs text-muted-foreground">{selectedRun.runKey} · Modules {(selectedRun.moduleIds || []).join(", ")} · {(selectedRun.capabilityKeys || []).length} capabilities</p></div><Badge variant={selectedRun.status === "released" ? "default" : selectedRun.status === "blocked" || selectedRun.status === "rejected" ? "destructive" : "secondary"}>{humanize(selectedRun.status)}</Badge></div><p className="text-sm text-muted-foreground">{selectedRun.objective}</p>
            <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{[["Expected groups", selectedRun.closureSnapshot?.expectedGroups], ["Initialized", selectedRun.closureSnapshot?.initializedGroups], ["Implemented", selectedRun.closureSnapshot?.implementedGroups], ["Pre-live", selectedRun.closureSnapshot?.preLiveQualifiedGroups], ["Blockers", selectedRun.closureSnapshot?.openBlockers]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-muted p-3"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value ?? 0}</p></div>)}</div>
            {["draft", "blocked"].includes(selectedRun.status) && canExecute && <div className="space-y-2"><Textarea aria-label="Qualification transition rationale" value={transitionRationale} onChange={(event) => setTransitionRationale(event.target.value)}/><Button disabled={startRun.isPending || transitionRationale.trim().length < 20} onClick={() => startRun.mutate()}><PlayCircle className="mr-2 h-4 w-4"/>{selectedRun.status === "blocked" ? "Reopen when gates pass" : "Start seven-scenario rehearsal"}</Button></div>}
            {["in_progress", "blocked"].includes(selectedRun.status) && <div className="space-y-3"><div><p className="font-medium">Mandatory scenarios</p><p className="text-xs text-muted-foreground">A passing result requires visible verified Evidence. Failed or blocked results require an explicit blocker and move the entire campaign to blocked.</p></div>{(selectedRun.scenarios || []).map((scenario: Row) => { const form = scenarioForms[scenario.id] || { status: scenario.status === "planned" ? "passed" : scenario.status, ownerSeatId: scenario.ownerSeatId, evidenceId: scenario.evidenceIds?.[0] || "", resultSummary: scenario.resultSummary || "", blocker: scenario.blocker || "" }; return <div key={scenario.id} className="space-y-3 rounded-xl bg-muted/50 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-medium">{scenario.title}</p><p className="text-xs text-muted-foreground">{humanize(scenario.scenarioType)} · version {scenario.version}</p></div><Badge variant={scenario.status === "passed" ? "default" : scenario.status === "failed" || scenario.status === "blocked" ? "destructive" : "outline"}>{humanize(scenario.status)}</Badge></div><div className="grid gap-2 md:grid-cols-2"><select aria-label={`${scenario.title} result`} className={field} value={form.status} onChange={(event) => setScenarioForms((values) => ({ ...values, [scenario.id]: { ...form, status: event.target.value, blocker: event.target.value === "passed" ? "" : form.blocker } }))}>{["passed", "failed", "blocked"].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select><select aria-label={`${scenario.title} evidence`} className={field} value={form.evidenceId} onChange={(event) => setScenarioForms((values) => ({ ...values, [scenario.id]: { ...form, evidenceId: event.target.value } }))}><option value="">Choose verified Evidence</option>{(state.data?.evidence || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select><Textarea aria-label={`${scenario.title} result summary`} placeholder="What was executed, observed, and verified?" value={form.resultSummary} onChange={(event) => setScenarioForms((values) => ({ ...values, [scenario.id]: { ...form, resultSummary: event.target.value } }))}/><Textarea aria-label={`${scenario.title} blocker`} disabled={form.status === "passed"} placeholder="Named blocker for failed or blocked results" value={form.blocker} onChange={(event) => setScenarioForms((values) => ({ ...values, [scenario.id]: { ...form, blocker: event.target.value } }))}/></div><Button size="sm" disabled={!canDecide || updateScenario.isPending || !form.evidenceId || form.resultSummary.trim().length < 20 || (form.status !== "passed" && !form.blocker.trim())} onClick={() => updateScenario.mutate({ scenario, form })}>Record scenario result</Button></div>; })}
              <div className="space-y-2 border-t pt-3"><Textarea aria-label="Qualification decision rationale" value={transitionRationale} onChange={(event) => setTransitionRationale(event.target.value)}/><Button disabled={!canDecide || qualifyRun.isPending || transitionRationale.trim().length < 20 || (selectedRun.scenarios || []).length !== 7 || !(selectedRun.scenarios || []).every((scenario: Row) => scenario.status === "passed")} onClick={() => qualifyRun.mutate()}>Qualify synthetic campaign</Button></div>
            </div>}
            {selectedRun.status === "qualified" && <div className="space-y-3 rounded-xl border border-primary/20 p-4"><div><p className="font-medium">Founder release decision</p><p className="text-xs text-muted-foreground">Release is separately gated on every scoped artifact group reaching pre-live qualified. Rejection can preserve the record without asserting release.</p></div><div className="grid gap-2 md:grid-cols-2"><select aria-label="Founder release decision" className={field} value={releaseForm.decision} onChange={(event) => setReleaseForm((value) => ({ ...value, decision: event.target.value }))}><option value="released">Release</option><option value="rejected">Reject</option></select><select aria-label="Founder release evidence" className={field} value={releaseForm.evidenceId} onChange={(event) => setReleaseForm((value) => ({ ...value, evidenceId: event.target.value }))}><option value="">Choose verified decision Evidence</option>{(state.data?.evidence || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select><Textarea className="md:col-span-2" aria-label="Founder release rationale" value={releaseForm.rationale} onChange={(event) => setReleaseForm((value) => ({ ...value, rationale: event.target.value }))}/></div><Button disabled={!canDecide || releaseRun.isPending || !releaseForm.evidenceId || releaseForm.rationale.trim().length < 30} onClick={() => releaseRun.mutate()}>{releaseForm.decision === "released" ? "Authorize pre-live release" : "Reject pre-live release"}</Button></div>}
            {(selectedRun.events || []).length > 0 && <details><summary className="cursor-pointer text-sm font-medium">Immutable campaign history ({selectedRun.events.length})</summary><div className="mt-2 space-y-2">{selectedRun.events.map((event: Row) => <div key={event.id} className="rounded-lg bg-muted p-3 text-xs"><span className="font-medium">#{event.sequence} {humanize(event.action)}</span><span className="text-muted-foreground"> · {humanize(event.fromStatus)} → {humanize(event.toStatus)} · {new Date(event.recordedAt).toLocaleString()}</span></div>)}</div></details>}
          </div>}
        </div> : <div className="rounded-xl border border-dashed p-6 text-center"><Rocket className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-medium">No governed qualification campaign yet</p><p className="mt-1 text-sm text-muted-foreground">Create one after company evidence coverage exists. EOS will refuse to start it until every scoped group is implemented and blocker-free.</p></div>}
      </CardContent>
    </Card>

    {groups.length ? <div className="grid gap-4 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
      <Card><CardHeader><CardTitle>Capability matrices</CardTitle><CardDescription>Select an artifact row to inspect its proof, owner, blocker, and next action.</CardDescription></CardHeader><CardContent className="space-y-3">{groups.map((group: Row) => <div key={group.key} className="rounded-xl border p-3"><button className="w-full text-left" onClick={() => setSelectedRecordId(records.find((item: Row) => item.capabilityKey === group.capabilityKey)?.id || "")}><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{group.capabilityKey}</p><p className="text-xs text-muted-foreground">{group.rowCount}/22 classes · {group.openBlockers} blockers</p></div>{group.preLiveQualified ? <Badge><CheckCircle2 className="mr-1 h-3 w-3"/>pre-live qualified</Badge> : group.implemented ? <Badge variant="secondary">implemented</Badge> : group.artifactComplete ? <Badge variant="secondary">artifact complete</Badge> : <Badge variant="outline">open</Badge>}</div></button>{selectedGroupKey === group.key && <div className="mt-3 grid gap-1 border-t pt-3">{groupRecords.map((record: Row) => <button key={record.id} className={`flex items-center justify-between rounded-lg px-2 py-2 text-left text-xs ${record.id === selectedRecordId ? "bg-primary/10 text-primary" : "hover:bg-muted"}`} onClick={() => setSelectedRecordId(record.id)}><span>{humanize(record.artifactClass)}</span><span>{humanize(record.maturity)}</span></button>)}</div>}</div>)}</CardContent></Card>

      <Card><CardHeader><CardTitle>{selectedRecord ? humanize(selectedRecord.artifactClass) : "Choose an artifact class"}</CardTitle><CardDescription>{selectedRecord ? `${selectedRecord.capabilityKey} · version ${selectedRecord.version}` : "No readiness claim is made until an attributable operator records and evidences it."}</CardDescription></CardHeader><CardContent>{selectedRecord ? <div className="space-y-4">
        <div className="grid gap-2 md:grid-cols-2"><label className="space-y-1 text-xs font-medium">Applicability<select aria-label="Artifact applicability" className={field} value={form.applicability} onChange={(event) => setForm((value) => ({ ...value, applicability: event.target.value }))}>{artifactClosureApplicability.map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label><label className="space-y-1 text-xs font-medium">Maturity<select aria-label="Artifact maturity" className={field} value={form.maturity} onChange={(event) => setForm((value) => ({ ...value, maturity: event.target.value }))}>{artifactClosureMaturity.map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label><label className="space-y-1 text-xs font-medium">Accountable seat<select aria-label="Artifact accountable seat" className={field} value={form.ownerSeatId} onChange={(event) => setForm((value) => ({ ...value, ownerSeatId: event.target.value }))}>{(state.data?.seats || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="space-y-1 text-xs font-medium">Verified Evidence<select aria-label="Artifact qualification Evidence" className={field} value={form.evidenceId} onChange={(event) => setForm((value) => ({ ...value, evidenceId: event.target.value }))}><option value="">No Evidence selected</option>{(state.data?.evidence || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select></label><Input className="md:col-span-2" aria-label="Template stack" placeholder="Template ancestry and overlays, comma separated" value={form.templateStack} onChange={(event) => setForm((value) => ({ ...value, templateStack: event.target.value }))}/><Textarea className="md:col-span-2" aria-label="Artifact blocker" placeholder="Named blocker; required while missing" value={form.blocker} onChange={(event) => setForm((value) => ({ ...value, blocker: event.target.value }))}/><Textarea className="md:col-span-2" aria-label="Artifact next action" placeholder="Specific next action, owner handoff, and expected proof" value={form.nextAction} onChange={(event) => setForm((value) => ({ ...value, nextAction: event.target.value }))}/><Textarea className="md:col-span-2" aria-label="Artifact decision rationale" placeholder="Attributable rationale and evidence limits" value={form.rationale} onChange={(event) => setForm((value) => ({ ...value, rationale: event.target.value }))}/><Textarea className="md:col-span-2" aria-label="Artifact activation trigger" placeholder="Required for deferred or not-applicable classifications" value={form.triggerCondition} onChange={(event) => setForm((value) => ({ ...value, triggerCondition: event.target.value }))}/></div>
        <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Group gate: {selectedGroup?.preLiveQualified ? "pre-live qualified" : selectedGroup?.implemented ? "implemented" : selectedGroup?.artifactComplete ? "artifact complete" : `${selectedGroup?.openBlockers || 0} open blockers`}</p><Button disabled={!canDecide || update.isPending || !form.ownerSeatId || form.nextAction.trim().length < 10 || form.rationale.trim().length < 20} onClick={() => update.mutate()}>Record closure decision</Button></div>
      </div> : <p className="text-sm text-muted-foreground">Select a capability matrix, then choose one of its 22 required artifact classes.</p>}</CardContent></Card>
    </div> : <Card><CardContent className="py-10 text-center"><ClipboardCheck className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-medium">No artifact closure matrix exists for this module</p><p className="mt-1 text-sm text-muted-foreground">Initialize a canonical capability or module-level matrix to expose every missing artifact without claiming it is complete.</p></CardContent></Card>}
  </div>;
}
