import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, CheckCircle2, FileCheck2, HeartHandshake, Plus, RefreshCw, ShieldAlert, TriangleAlert } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

type Row = Record<string, any>;
type Props = { root: string; canExecute: boolean; canDecide: boolean };

function scopedUrl(url: string) {
  if (typeof window === "undefined") return url;
  const seat = new URLSearchParams(window.location.search).get("seat");
  if (!seat) return url;
  const scoped = new URL(url, window.location.origin); scoped.searchParams.set("seatId", seat); return `${scoped.pathname}${scoped.search}`;
}
async function json<T>(method: "GET" | "POST", url: string, body?: unknown): Promise<T> { const response = await apiRequest(method, scopedUrl(url), body) as Response; return response.json() as Promise<T>; }
const dateFromNow = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);
const field = "h-10 rounded-md border border-input bg-background px-3 text-sm";
function badge(state: string) { const variant = ["healthy", "achieved", "resolved", "approved", "delivery_recorded", "renewing"].includes(state) ? "default" : ["at_risk", "critical", "not_achieved", "nonrenewing"].includes(state) ? "destructive" : "secondary"; return <Badge variant={variant as any}>{state.replaceAll("_", " ")}</Badge>; }

export function CustomerSuccessControlCenter({ root, canExecute, canDecide }: Props) {
  const endpoint = `${root}/customer-success`; const queryClient = useQueryClient(); const { toast } = useToast();
  const state = useQuery<Row>({ queryKey: [endpoint], queryFn: () => json("GET", endpoint) });
  const [accountId, setAccountId] = useState("");
  const refresh = async () => queryClient.invalidateQueries({ queryKey: [endpoint] });
  const action = useMutation({
    mutationFn: (input: { url: string; body: unknown; success: string }) => json("POST", input.url, input.body),
    onSuccess: async (_value, input) => { await refresh(); toast({ title: input.success, description: "The current projection and immutable receipt history were updated together." }); },
    onError: (error) => toast({ title: "Customer-success action failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }),
  });
  const run = (url: string, body: unknown, success: string) => action.mutate({ url, body, success });

  const [account, setAccount] = useState({ relationshipId: "", ownerSeatId: "", reviewCadenceDays: 30, nextReviewAt: dateFromNow(30), renewalAt: "", successDefinition: "", classification: "confidential" });
  const [health, setHealth] = useState({ deliveryScore: 75, outcomeScore: 75, adoptionScore: 75, relationshipScore: 75, riskScore: 25, evidenceId: "", summary: "", nextActions: "", nextReviewAt: dateFromNow(30) });
  const [outcome, setOutcome] = useState({ outcomeKey: "", title: "", definition: "", baselineValue: "", targetValue: "", unit: "", dueAt: dateFromNow(90), attributionModel: "contributing", attributionRationale: "", ownerSeatId: "", classification: "confidential" });
  const [progress, setProgress] = useState({ outcomeId: "", state: "tracking", actualValue: "", evidenceId: "", note: "" });
  const [issue, setIssue] = useState({ issueKey: "", title: "", severity: "medium", summary: "", ownerSeatId: "", dueAt: dateFromNow(14), evidenceId: "", classification: "confidential" });
  const [resolution, setResolution] = useState({ issueId: "", resolution: "", evidenceId: "" });
  const [report, setReport] = useState({ reportKey: "", title: "", periodStart: dateFromNow(-30), periodEnd: dateFromNow(0), executiveSummary: "", evidenceId: "", proofConsent: "internal_only", consentEvidenceId: "", classification: "confidential" });
  const [approval, setApproval] = useState({ reportId: "", evidenceId: "", note: "" });
  const [delivery, setDelivery] = useState({ reportId: "", channel: "email", recipientScope: "", externalReference: "", receiptEvidenceId: "", deliveredAt: new Date().toISOString().slice(0, 16) });
  const [renewal, setRenewal] = useState({ intent: "defer", evidenceId: "", rationale: "", nextReviewAt: dateFromNow(30) });

  const selected = state.data?.accounts?.find((item: Row) => item.id === accountId);
  const eligible = state.data?.eligibleCustomers?.find((item: Row) => item.relationship.id === account.relationshipId);
  const accountOutcomes = useMemo(() => (state.data?.outcomes || []).filter((item: Row) => item.accountId === accountId), [state.data?.outcomes, accountId]);
  const accountIssues = useMemo(() => (state.data?.issues || []).filter((item: Row) => item.accountId === accountId), [state.data?.issues, accountId]);
  const accountReports = useMemo(() => (state.data?.reports || []).filter((item: Row) => item.accountId === accountId), [state.data?.reports, accountId]);
  const accountReviews = useMemo(() => (state.data?.healthReviews || []).filter((item: Row) => item.accountId === accountId), [state.data?.healthReviews, accountId]);
  const accountEvents = useMemo(() => (state.data?.events || []).filter((item: Row) => item.accountId === accountId), [state.data?.events, accountId]);
  const evidenceOptions = state.data?.evidence || [];

  if (state.isLoading) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Loading customer-success control state…</CardContent></Card>;
  if (state.isError) return <Alert variant="destructive"><ShieldAlert className="h-4 w-4"/><AlertTitle>Customer-success state unavailable</AlertTitle><AlertDescription>EOS will not infer health, attribution, delivery, or renewal readiness while the governed state is unavailable.</AlertDescription></Alert>;

  const evidenceSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose verified Evidence</option>{evidenceOptions.map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select>;
  const seatSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose accountable seat</option>{(state.data?.seats || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>;

  return <div className="space-y-6" id="customer-success-control-center">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Accounts", state.data?.counts?.accounts], ["Healthy", state.data?.counts?.healthy], ["At risk", state.data?.counts?.atRisk], ["Overdue reviews", state.data?.counts?.overdueReviews], ["Open issues", state.data?.counts?.openIssues], ["Renewal reviews", state.data?.counts?.renewalReviews]].map(([label, value]) => <Card key={String(label)}><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value || 0}</p></CardContent></Card>)}</div>
    <Alert><ShieldAlert className="h-4 w-4"/><AlertTitle>Evidence and external-effect boundary</AlertTitle><AlertDescription>{state.data?.boundary}</AlertDescription></Alert>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><HeartHandshake className="h-5 w-5"/>Customer success accounts</CardTitle><CardDescription>Attach success operations to one canonical customer relationship; do not create a duplicate contact record.</CardDescription></CardHeader><CardContent className="space-y-4">
      {canExecute && <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><select aria-label="Canonical customer relationship" className={field} value={account.relationshipId} onChange={(event) => setAccount((value) => ({ ...value, relationshipId: event.target.value }))}><option value="">Choose active customer relationship</option>{(state.data?.eligibleCustomers || []).map((item: Row) => <option key={item.relationship.id} value={item.relationship.id}>{item.stakeholder.name} · {item.relationship.title}</option>)}</select>{seatSelect("Customer success owner", account.ownerSeatId, (ownerSeatId) => setAccount((value) => ({ ...value, ownerSeatId })))}<label className="space-y-1 text-xs text-muted-foreground">Review cadence days<Input type="number" min={1} max={365} value={account.reviewCadenceDays} onChange={(event) => setAccount((value) => ({ ...value, reviewCadenceDays: Number(event.target.value) }))}/></label><label className="space-y-1 text-xs text-muted-foreground">Next review<Input type="date" value={account.nextReviewAt} onChange={(event) => setAccount((value) => ({ ...value, nextReviewAt: event.target.value }))}/></label><label className="space-y-1 text-xs text-muted-foreground">Renewal date, if known<Input type="date" value={account.renewalAt} onChange={(event) => setAccount((value) => ({ ...value, renewalAt: event.target.value }))}/></label><Textarea className="md:col-span-2" placeholder="Observable definition of customer success and explicit limits" value={account.successDefinition} onChange={(event) => setAccount((value) => ({ ...value, successDefinition: event.target.value }))}/><Button className="w-fit" disabled={action.isPending || !eligible || !account.ownerSeatId || account.successDefinition.trim().length < 20} onClick={() => run(`${endpoint}/accounts`, { ...account, stakeholderId: eligible.stakeholder.id }, "Customer-success account created")}><Plus className="mr-2 h-4 w-4"/>Create account</Button></div>}
      <div className="flex flex-col gap-2 md:flex-row"><select aria-label="Customer success account" className={`${field} flex-1`} value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Choose customer-success account</option>{(state.data?.accounts || []).map((item: Row) => <option key={item.id} value={item.id}>{item.customerName} · {item.healthState.replaceAll("_", " ")}</option>)}</select><Button variant="outline" onClick={() => refresh()} disabled={state.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${state.isFetching ? "animate-spin" : ""}`}/>Refresh</Button></div>
      {selected && <div className="rounded-xl border p-4"><div className="flex flex-wrap items-center gap-2">{badge(selected.healthState)}{badge(selected.lifecycleState)}<Badge variant="outline">v{selected.version}</Badge>{selected.reviewOverdue && <Badge variant="destructive">review overdue</Badge>}</div><p className="mt-3 text-sm">{selected.successDefinition}</p><p className="mt-2 text-xs text-muted-foreground">Health {selected.healthScore ?? "unscored"}/100 · next review {selected.nextReviewAt} · renewal {selected.renewalAt || "not recorded"}</p></div>}
    </CardContent></Card>

    {selected && <>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>Evidence-backed health review</CardTitle><CardDescription>EOS calculates health deterministically from delivery, outcome, adoption, relationship, and risk dimensions.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(["deliveryScore", "outcomeScore", "adoptionScore", "relationshipScore", "riskScore"] as const).map((key) => <label key={key} className="space-y-1 text-xs text-muted-foreground">{key.replace("Score", " score")}<Input type="number" min={0} max={100} value={health[key]} onChange={(event) => setHealth((value) => ({ ...value, [key]: Number(event.target.value) }))}/></label>)}</div><div className="grid gap-3 md:grid-cols-2">{evidenceSelect("Health review Evidence", health.evidenceId, (evidenceId) => setHealth((value) => ({ ...value, evidenceId })))}<label className="space-y-1 text-xs text-muted-foreground">Next review<Input type="date" value={health.nextReviewAt} onChange={(event) => setHealth((value) => ({ ...value, nextReviewAt: event.target.value }))}/></label><Textarea placeholder="Observed customer-health facts and limits" value={health.summary} onChange={(event) => setHealth((value) => ({ ...value, summary: event.target.value }))}/><Textarea placeholder="Accountable next actions" value={health.nextActions} onChange={(event) => setHealth((value) => ({ ...value, nextActions: event.target.value }))}/></div><Button disabled={!canExecute || action.isPending || !health.evidenceId || health.summary.trim().length < 20 || health.nextActions.trim().length < 10} onClick={() => run(`${endpoint}/accounts/${selected.id}/health-reviews`, { expectedVersion: selected.version, ...health, evidenceIds: [health.evidenceId], evidenceId: undefined }, "Health review recorded")}><CheckCircle2 className="mr-2 h-4 w-4"/>Record health review</Button>{accountReviews[0] && <div className="rounded-lg bg-muted p-3 text-sm"><span className="font-medium">Latest: {accountReviews[0].healthScore}/100 · {accountReviews[0].healthState.replaceAll("_", " ")}</span><p className="mt-1 text-muted-foreground">{accountReviews[0].summary}</p></div>}</CardContent></Card>

      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle>Outcomes and attribution</CardTitle><CardDescription>Track observable customer outcomes without converting correlation into unsupported causal claims.</CardDescription></CardHeader><CardContent className="space-y-4">{canExecute && <details><summary className="cursor-pointer text-sm font-medium">Define outcome</summary><div className="mt-3 grid gap-2 md:grid-cols-2"><Input placeholder="Outcome key" value={outcome.outcomeKey} onChange={(e) => setOutcome((v) => ({ ...v, outcomeKey: e.target.value }))}/><Input placeholder="Outcome title" value={outcome.title} onChange={(e) => setOutcome((v) => ({ ...v, title: e.target.value }))}/><Textarea placeholder="Observable outcome definition" value={outcome.definition} onChange={(e) => setOutcome((v) => ({ ...v, definition: e.target.value }))}/><Textarea placeholder="Attribution rationale and limitations" value={outcome.attributionRationale} onChange={(e) => setOutcome((v) => ({ ...v, attributionRationale: e.target.value }))}/><Input placeholder="Baseline" value={outcome.baselineValue} onChange={(e) => setOutcome((v) => ({ ...v, baselineValue: e.target.value }))}/><Input placeholder="Target" value={outcome.targetValue} onChange={(e) => setOutcome((v) => ({ ...v, targetValue: e.target.value }))}/><Input placeholder="Unit" value={outcome.unit} onChange={(e) => setOutcome((v) => ({ ...v, unit: e.target.value }))}/><Input type="date" value={outcome.dueAt} onChange={(e) => setOutcome((v) => ({ ...v, dueAt: e.target.value }))}/><select aria-label="Attribution model" className={field} value={outcome.attributionModel} onChange={(e) => setOutcome((v) => ({ ...v, attributionModel: e.target.value }))}>{["direct", "contributing", "correlated", "unknown"].map((value) => <option key={value}>{value}</option>)}</select>{seatSelect("Outcome owner", outcome.ownerSeatId, (ownerSeatId) => setOutcome((v) => ({ ...v, ownerSeatId })))}<Button className="w-fit" disabled={!outcome.ownerSeatId || outcome.definition.trim().length < 20 || outcome.attributionRationale.trim().length < 20} onClick={() => run(`${endpoint}/accounts/${selected.id}/outcomes`, { expectedAccountVersion: selected.version, ...outcome }, "Outcome defined")}>Define outcome</Button></div></details>}
          <div className="space-y-2">{accountOutcomes.map((item: Row) => <div key={item.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><p className="font-medium">{item.title}</p>{badge(item.state)}</div><p className="mt-1 text-xs text-muted-foreground">{item.baselineValue} → {item.targetValue} {item.unit}; actual {item.actualValue} · {item.attributionModel}</p>{canExecute && <Button className="mt-2" size="sm" variant="outline" onClick={() => setProgress((value) => ({ ...value, outcomeId: item.id }))}>Record progress</Button>}</div>)}</div>
          {progress.outcomeId && <div className="grid gap-2 rounded-lg bg-muted p-3"><select aria-label="Outcome state" className={field} value={progress.state} onChange={(e) => setProgress((v) => ({ ...v, state: e.target.value }))}>{["tracking", "achieved", "not_achieved", "abandoned"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><Input placeholder="Actual value" value={progress.actualValue} onChange={(e) => setProgress((v) => ({ ...v, actualValue: e.target.value }))}/>{evidenceSelect("Outcome progress Evidence", progress.evidenceId, (evidenceId) => setProgress((v) => ({ ...v, evidenceId })))}<Textarea placeholder="Observed progress and attribution limits" value={progress.note} onChange={(e) => setProgress((v) => ({ ...v, note: e.target.value }))}/><Button disabled={!progress.evidenceId || progress.note.trim().length < 20 || (["achieved", "not_achieved", "abandoned"].includes(progress.state) && !canDecide)} onClick={() => { const item = accountOutcomes.find((candidate: Row) => candidate.id === progress.outcomeId); run(`${endpoint}/accounts/${selected.id}/outcomes/${item.id}/progress`, { expectedAccountVersion: selected.version, expectedVersion: item.version, state: progress.state, actualValue: progress.actualValue, evidenceIds: [progress.evidenceId], note: progress.note }, "Outcome progress recorded"); }}>Record progress</Button></div>}
        </CardContent></Card>

        <Card><CardHeader><CardTitle>Customer issues</CardTitle><CardDescription>Keep issue severity, ownership, due date, resolution, and Evidence separate from the health opinion.</CardDescription></CardHeader><CardContent className="space-y-4">{canExecute && <details><summary className="cursor-pointer text-sm font-medium">Open issue</summary><div className="mt-3 grid gap-2 md:grid-cols-2"><Input placeholder="Issue key" value={issue.issueKey} onChange={(e) => setIssue((v) => ({ ...v, issueKey: e.target.value }))}/><Input placeholder="Issue title" value={issue.title} onChange={(e) => setIssue((v) => ({ ...v, title: e.target.value }))}/><select aria-label="Issue severity" className={field} value={issue.severity} onChange={(e) => setIssue((v) => ({ ...v, severity: e.target.value }))}>{["low", "medium", "high", "critical"].map((value) => <option key={value}>{value}</option>)}</select><Input type="date" value={issue.dueAt} onChange={(e) => setIssue((v) => ({ ...v, dueAt: e.target.value }))}/>{seatSelect("Issue owner", issue.ownerSeatId, (ownerSeatId) => setIssue((v) => ({ ...v, ownerSeatId })))}{evidenceSelect("Issue Evidence", issue.evidenceId, (evidenceId) => setIssue((v) => ({ ...v, evidenceId })))}<Textarea className="md:col-span-2" placeholder="Observed issue, impact, and scope" value={issue.summary} onChange={(e) => setIssue((v) => ({ ...v, summary: e.target.value }))}/><Button className="w-fit" disabled={!issue.ownerSeatId || issue.summary.trim().length < 20} onClick={() => run(`${endpoint}/accounts/${selected.id}/issues`, { expectedAccountVersion: selected.version, ...issue, evidenceIds: issue.evidenceId ? [issue.evidenceId] : [], evidenceId: undefined }, "Customer issue opened")}>Open issue</Button></div></details>}
          <div className="space-y-2">{accountIssues.map((item: Row) => <div key={item.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><p className="font-medium">{item.title}</p><div className="flex gap-1"><Badge variant={item.severity === "critical" ? "destructive" : "outline"}>{item.severity}</Badge>{badge(item.state)}</div></div><p className="mt-1 text-sm text-muted-foreground">{item.summary}</p>{item.state === "open" && canExecute && <Button className="mt-2" size="sm" variant="outline" onClick={() => setResolution((value) => ({ ...value, issueId: item.id }))}>Resolve with proof</Button>}</div>)}</div>
          {resolution.issueId && <div className="grid gap-2 rounded-lg bg-muted p-3">{evidenceSelect("Issue resolution Evidence", resolution.evidenceId, (evidenceId) => setResolution((v) => ({ ...v, evidenceId })))}<Textarea placeholder="Verified resolution and remaining risk" value={resolution.resolution} onChange={(e) => setResolution((v) => ({ ...v, resolution: e.target.value }))}/><Button disabled={!resolution.evidenceId || resolution.resolution.trim().length < 20} onClick={() => { const item = accountIssues.find((candidate: Row) => candidate.id === resolution.issueId); run(`${endpoint}/accounts/${selected.id}/issues/${item.id}/resolve`, { expectedAccountVersion: selected.version, expectedVersion: item.version, resolution: resolution.resolution, evidenceIds: [resolution.evidenceId] }, "Issue resolved") }}>Record resolution</Button></div>}
        </CardContent></Card>
      </div>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 className="h-5 w-5"/>Reports, consent, and delivery receipts</CardTitle><CardDescription>Freeze a health/outcome/issue snapshot, approve it, then reconcile an external provider receipt. EOS does not treat button clicks as delivery.</CardDescription></CardHeader><CardContent className="space-y-4"><details><summary className="cursor-pointer text-sm font-medium">Prepare evidence-backed report</summary><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><Input placeholder="Report key" value={report.reportKey} onChange={(e) => setReport((v) => ({ ...v, reportKey: e.target.value }))}/><Input placeholder="Report title" value={report.title} onChange={(e) => setReport((v) => ({ ...v, title: e.target.value }))}/><select aria-label="Proof consent" className={field} value={report.proofConsent} onChange={(e) => setReport((v) => ({ ...v, proofConsent: e.target.value }))}>{["internal_only", "customer_approved", "public_approved"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><Input type="date" value={report.periodStart} onChange={(e) => setReport((v) => ({ ...v, periodStart: e.target.value }))}/><Input type="date" value={report.periodEnd} onChange={(e) => setReport((v) => ({ ...v, periodEnd: e.target.value }))}/>{evidenceSelect("Report Evidence", report.evidenceId, (evidenceId) => setReport((v) => ({ ...v, evidenceId })))}{report.proofConsent !== "internal_only" && evidenceSelect("Proof consent Evidence", report.consentEvidenceId, (consentEvidenceId) => setReport((v) => ({ ...v, consentEvidenceId })))}<Textarea className="md:col-span-2 xl:col-span-3" placeholder="Executive summary limited to supported claims" value={report.executiveSummary} onChange={(e) => setReport((v) => ({ ...v, executiveSummary: e.target.value }))}/><Button className="w-fit" disabled={!canExecute || !report.evidenceId || report.executiveSummary.trim().length < 20 || (report.proofConsent !== "internal_only" && !report.consentEvidenceId)} onClick={() => run(`${endpoint}/accounts/${selected.id}/reports`, { expectedAccountVersion: selected.version, ...report, evidenceIds: [report.evidenceId], evidenceId: undefined }, "Immutable report snapshot prepared")}>Prepare report</Button></div></details>
        <div className="space-y-3">{accountReports.map((item: Row) => <div key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{item.title}</p><p className="text-xs text-muted-foreground">{item.periodStart}–{item.periodEnd} · {item.proofConsent.replaceAll("_", " ")}</p></div>{badge(item.state)}</div><p className="mt-2 text-sm">{item.executiveSummary}</p><code className="mt-2 block text-[10px] text-muted-foreground">{item.reportSha256}</code><div className="mt-3 flex flex-wrap gap-2">{item.state === "prepared" && canDecide && <Button size="sm" variant="outline" onClick={() => setApproval((value) => ({ ...value, reportId: item.id }))}>Approve report</Button>}{item.state === "approved" && canExecute && <Button size="sm" variant="outline" onClick={() => setDelivery((value) => ({ ...value, reportId: item.id }))}>Record provider receipt</Button>}</div></div>)}</div>
        {approval.reportId && <div className="grid gap-2 rounded-lg bg-muted p-3 md:grid-cols-2">{evidenceSelect("Report approval Evidence", approval.evidenceId, (evidenceId) => setApproval((v) => ({ ...v, evidenceId })))}<Textarea placeholder="Why this exact report is approved" value={approval.note} onChange={(e) => setApproval((v) => ({ ...v, note: e.target.value }))}/><Button disabled={!approval.evidenceId || approval.note.trim().length < 20} onClick={() => { const item = accountReports.find((candidate: Row) => candidate.id === approval.reportId); run(`${endpoint}/accounts/${selected.id}/reports/${item.id}/approve`, { expectedAccountVersion: selected.version, expectedVersion: item.version, approvalEvidenceIds: [approval.evidenceId], approvalNote: approval.note }, "Report approved") }}>Approve exact report</Button></div>}
        {delivery.reportId && <div className="grid gap-2 rounded-lg bg-muted p-3 md:grid-cols-2"><select aria-label="Delivery channel" className={field} value={delivery.channel} onChange={(e) => setDelivery((v) => ({ ...v, channel: e.target.value }))}>{["email", "portal", "crm", "manual"].map((value) => <option key={value}>{value}</option>)}</select><Input placeholder="Authorized recipient scope" value={delivery.recipientScope} onChange={(e) => setDelivery((v) => ({ ...v, recipientScope: e.target.value }))}/><Input placeholder="Provider message or delivery reference" value={delivery.externalReference} onChange={(e) => setDelivery((v) => ({ ...v, externalReference: e.target.value }))}/>{evidenceSelect("Provider delivery receipt Evidence", delivery.receiptEvidenceId, (receiptEvidenceId) => setDelivery((v) => ({ ...v, receiptEvidenceId })))}<Input type="datetime-local" value={delivery.deliveredAt} onChange={(e) => setDelivery((v) => ({ ...v, deliveredAt: e.target.value }))}/><Button disabled={!delivery.receiptEvidenceId || delivery.externalReference.trim().length < 3 || delivery.recipientScope.trim().length < 3} onClick={() => { const item = accountReports.find((candidate: Row) => candidate.id === delivery.reportId); run(`${endpoint}/accounts/${selected.id}/reports/${item.id}/delivery-receipts`, { expectedAccountVersion: selected.version, expectedVersion: item.version, ...delivery, reportId: undefined }, "External delivery receipt reconciled") }}>Record receipt, not send</Button></div>}
      </CardContent></Card>

      <Card><CardHeader><CardTitle>Renewal readiness decision</CardTitle><CardDescription>A current health review and operational outcome Evidence are required. This decision does not renew or terminate a contract.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-2"><select aria-label="Renewal intent" className={field} value={renewal.intent} onChange={(e) => setRenewal((v) => ({ ...v, intent: e.target.value }))}>{["renew", "renegotiate", "terminate", "allow_expiry", "defer"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select>{evidenceSelect("Renewal decision Evidence", renewal.evidenceId, (evidenceId) => setRenewal((v) => ({ ...v, evidenceId })))}<Input type="date" value={renewal.nextReviewAt} onChange={(e) => setRenewal((v) => ({ ...v, nextReviewAt: e.target.value }))}/><Textarea placeholder="Decision rationale, evidence limits, and contractual next step" value={renewal.rationale} onChange={(e) => setRenewal((v) => ({ ...v, rationale: e.target.value }))}/></div><Button disabled={!canDecide || !renewal.evidenceId || renewal.rationale.trim().length < 20} onClick={() => run(`${endpoint}/accounts/${selected.id}/renewal-decisions`, { expectedVersion: selected.version, intent: renewal.intent, evidenceIds: [renewal.evidenceId], rationale: renewal.rationale, nextReviewAt: renewal.nextReviewAt }, "Renewal readiness decided")}>Record decision</Button></CardContent></Card>

      <Card><CardHeader><CardTitle>Immutable customer-success history</CardTitle><CardDescription>Every projection change retains an actor, policy decision, evidence references, versions, and a chained hash.</CardDescription></CardHeader><CardContent><div className="space-y-2">{accountEvents.map((item: Row) => <div key={item.id} className="rounded-lg border p-3 text-xs"><div className="flex items-center justify-between gap-2"><span className="font-medium">{item.eventType.replaceAll("_", " ")}</span><span>account v{item.accountVersionBefore}→{item.accountVersionAfter}</span></div><code className="mt-1 block text-[10px] text-muted-foreground">{item.eventSha256}</code></div>)}</div></CardContent></Card>
    </>}
  </div>;
}
