import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, Beaker, CheckCircle2, GitBranch, Lightbulb, RefreshCw, RotateCcw, ShieldAlert } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

type Row = Record<string, any>;
type Props = { root: string; canExecute: boolean; canDecide: boolean; isFounder: boolean };
const field = "h-10 rounded-md border border-input bg-background px-3 text-sm";
const dateFromNow = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);
function scopedUrl(url: string) { if (typeof window === "undefined") return url; const seat = new URLSearchParams(window.location.search).get("seat"); if (!seat) return url; const scoped = new URL(url, window.location.origin); scoped.searchParams.set("seatId", seat); return `${scoped.pathname}${scoped.search}`; }
async function json<T>(method: "GET" | "POST", url: string, body?: unknown): Promise<T> { const response = await apiRequest(method, scopedUrl(url), body) as Response; return response.json() as Promise<T>; }
function badge(value: string) { const good = ["compatible", "met", "ship", "completed", "concluded"].includes(value); const bad = ["breaking", "not_met", "reject", "rolled_back", "stopped"].includes(value); return <Badge variant={(good ? "default" : bad ? "destructive" : "secondary") as any}>{value.replaceAll("_", " ")}</Badge>; }
function csv(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }

export function ProductEvolutionControlCenter({ root, canExecute, canDecide, isFounder }: Props) {
  const endpoint = `${root}/product-evolution`; const queryClient = useQueryClient(); const { toast } = useToast();
  const state = useQuery<Row>({ queryKey: [endpoint], queryFn: () => json("GET", endpoint) });
  const refresh = async () => queryClient.invalidateQueries({ queryKey: [endpoint] });
  const action = useMutation({
    mutationFn: (input: { url: string; body: unknown; success: string }) => json("POST", input.url, input.body),
    onSuccess: async (_value, input) => { await refresh(); toast({ title: input.success, description: "The governed projection and immutable evidence history were updated together." }); },
    onError: (error) => toast({ title: "Product-evolution action failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }),
  });
  const run = (url: string, body: unknown, success: string) => action.mutate({ url, body, success });
  const [offerId, setOfferId] = useState(""); const [proposalId, setProposalId] = useState("");
  const [feedback, setFeedback] = useState({ source: "customer", sourceReference: "", summary: "", observedAt: new Date().toISOString().slice(0, 16), evidenceId: "", classification: "confidential" });
  const [proposal, setProposal] = useState({ proposalKey: "", title: "", hypothesis: "", changeField: "promiseOutcome", changeValue: "", rollbackPlan: "", successMetric: "", guardrailMetric: "", feedbackSignalIds: [] as string[], ownerSeatId: "", classification: "confidential" });
  const [compatibility, setCompatibility] = useState({ outcome: "compatible", rationale: "", affectedWorkflows: "", affectedSegments: "", affectedContracts: "", migrationPlan: "", evidenceId: "" });
  const [experiment, setExperiment] = useState({ question: "", cohortScope: "", allocationPercent: 10, startsAt: dateFromNow(0), endsAt: dateFromNow(14), ownerSeatId: "", classification: "confidential" });
  const [transition, setTransition] = useState({ state: "running", rationale: "", evidenceId: "" });
  const [observation, setObservation] = useState({ metricKey: "", value: "", unit: "", windowStart: dateFromNow(-7), windowEnd: dateFromNow(0), sourceAuthority: "internal_observation", externalReference: "", evidenceId: "" });
  const [conclusion, setConclusion] = useState({ result: "met", conclusion: "", evidenceId: "" });
  const [release, setRelease] = useState({ decision: "ship", rationale: "", evidenceId: "" });
  const [rollout, setRollout] = useState({ allocationPercent: 5, rollbackThreshold: "", evidenceId: "" });
  const [advance, setAdvance] = useState({ allocationPercent: 20, externalReference: "", receiptEvidenceId: "", note: "" });
  const [rollback, setRollback] = useState({ rationale: "", evidenceId: "" });
  const [apply, setApply] = useState({ rationale: "", evidenceId: "" });

  const selectedOffer = state.data?.offers?.find((item: Row) => item.id === offerId);
  const selectedProposal = state.data?.proposals?.find((item: Row) => item.id === proposalId);
  const selectedExperiment = state.data?.experiments?.find((item: Row) => item.proposalId === proposalId);
  const offerSignals = useMemo(() => (state.data?.feedback || []).filter((item: Row) => item.offerId === offerId), [state.data?.feedback, offerId]);
  const proposalEvents = useMemo(() => (state.data?.events || []).filter((item: Row) => item.proposalId === proposalId), [state.data?.events, proposalId]);
  const observations = useMemo(() => (state.data?.observations || []).filter((item: Row) => item.proposalId === proposalId), [state.data?.observations, proposalId]);
  const evidence = state.data?.evidence || [];
  const evidenceSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose verified Evidence</option>{evidence.map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select>;
  const seatSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose accountable seat</option>{(state.data?.seats || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>;
  const nextStage = selectedProposal?.rolloutStage === "internal" ? "pilot" : selectedProposal?.rolloutStage === "pilot" ? "limited" : selectedProposal?.rolloutStage === "limited" ? "general" : null;
  const patchValue = proposal.changeField === "metricKeys" || proposal.changeField === "workflowKeys" ? csv(proposal.changeValue) : proposal.changeValue;

  if (state.isLoading) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Loading product-evolution control state…</CardContent></Card>;
  if (state.isError) return <Alert variant="destructive"><ShieldAlert className="h-4 w-4"/><AlertTitle>Product-evolution state unavailable</AlertTitle><AlertDescription>EOS will not infer feedback, experiment results, release authority, or rollout state while governed records are unavailable.</AlertDescription></Alert>;

  return <div className="space-y-6" id="product-evolution-control-center">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Offers", state.data?.counts?.offers], ["Signals", state.data?.counts?.signals], ["Open proposals", state.data?.counts?.openProposals], ["Running tests", state.data?.counts?.runningExperiments], ["Active rollouts", state.data?.counts?.activeRollouts], ["Ready to apply", state.data?.counts?.readyToApply]].map(([label, value]) => <Card key={String(label)}><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value || 0}</p></CardContent></Card>)}</div>
    <Alert><ShieldAlert className="h-4 w-4"/><AlertTitle>Draft, provider, and canonical-authority boundary</AlertTitle><AlertDescription>{state.data?.boundary}</AlertDescription></Alert>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb className="h-5 w-5"/>Offer learning inbox</CardTitle><CardDescription>Anchor every signal to the canonical offer and verified Evidence. Provider references identify source records; they do not become provider truth by assertion.</CardDescription></CardHeader><CardContent className="space-y-4">
      <div className="flex flex-col gap-2 md:flex-row"><select aria-label="Canonical offer" className={`${field} flex-1`} value={offerId} onChange={(event) => { setOfferId(event.target.value); setProposalId(""); }}><option value="">Choose canonical offer or program</option>{(state.data?.offers || []).map((item: Row) => <option key={item.id} value={item.id}>{item.name} · {item.state}</option>)}</select><Button variant="outline" onClick={() => refresh()} disabled={state.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${state.isFetching ? "animate-spin" : ""}`}/>Refresh</Button></div>
      {selectedOffer && <div className="rounded-xl border p-4"><div className="flex flex-wrap gap-2">{badge(selectedOffer.state)}<Badge variant="outline">{selectedOffer.offerType.replaceAll("_", " ")}</Badge></div><p className="mt-3 font-semibold">{selectedOffer.name}</p><p className="mt-1 text-sm text-muted-foreground">{selectedOffer.problemNeed} → {selectedOffer.promiseOutcome}</p></div>}
      {selectedOffer && canExecute && <details><summary className="cursor-pointer text-sm font-medium">Record feedback signal</summary><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><select aria-label="Feedback source" className={field} value={feedback.source} onChange={(e) => setFeedback((v) => ({ ...v, source: e.target.value }))}>{["customer", "sales", "delivery", "support", "operations", "analytics", "provider"].map((value) => <option key={value}>{value}</option>)}</select><Input placeholder="Source record reference" value={feedback.sourceReference} onChange={(e) => setFeedback((v) => ({ ...v, sourceReference: e.target.value }))}/><Input type="datetime-local" value={feedback.observedAt} onChange={(e) => setFeedback((v) => ({ ...v, observedAt: e.target.value }))}/>{evidenceSelect("Feedback Evidence", feedback.evidenceId, (evidenceId) => setFeedback((v) => ({ ...v, evidenceId })))}<Textarea className="md:col-span-2" placeholder="Observed signal, audience, and limits" value={feedback.summary} onChange={(e) => setFeedback((v) => ({ ...v, summary: e.target.value }))}/><Button className="w-fit" disabled={action.isPending || !feedback.evidenceId || feedback.summary.trim().length < 20 || feedback.sourceReference.trim().length < 3} onClick={() => run(`${endpoint}/feedback`, { ...feedback, offerId, observedAt: new Date(feedback.observedAt).toISOString(), evidenceIds: [feedback.evidenceId], evidenceId: undefined }, "Feedback signal recorded")}>Record signal</Button></div></details>}
      <div className="space-y-2">{offerSignals.map((item: Row) => <label key={item.id} className="flex cursor-pointer gap-3 rounded-lg border p-3"><input type="checkbox" checked={proposal.feedbackSignalIds.includes(item.id)} onChange={(e) => setProposal((v) => ({ ...v, feedbackSignalIds: e.target.checked ? [...v.feedbackSignalIds, item.id] : v.feedbackSignalIds.filter((id) => id !== item.id) }))}/><span><span className="font-medium">{item.source} · {item.sourceReference}</span><span className="mt-1 block text-sm text-muted-foreground">{item.summary}</span></span></label>)}</div>
    </CardContent></Card>

    {selectedOffer && <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitBranch className="h-5 w-5"/>Versioned change proposals</CardTitle><CardDescription>Freeze the current offer hash, propose only allowlisted fields, and keep templates/contracts separately governed through compatibility references.</CardDescription></CardHeader><CardContent className="space-y-4">
      {canExecute && <details><summary className="cursor-pointer text-sm font-medium">Draft proposal from selected offer</summary><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><Input placeholder="Proposal key" value={proposal.proposalKey} onChange={(e) => setProposal((v) => ({ ...v, proposalKey: e.target.value }))}/><Input placeholder="Proposal title" value={proposal.title} onChange={(e) => setProposal((v) => ({ ...v, title: e.target.value }))}/>{seatSelect("Proposal owner", proposal.ownerSeatId, (ownerSeatId) => setProposal((v) => ({ ...v, ownerSeatId })))}<select aria-label="Governed offer field" className={field} value={proposal.changeField} onChange={(e) => setProposal((v) => ({ ...v, changeField: e.target.value }))}>{["name", "problemNeed", "promiseOutcome", "scopeInclusions", "exclusionsConstraints", "deliveryModel", "pricingEconomicModel", "commercialTermsAuthority", "metricKeys", "workflowKeys"].map((value) => <option key={value} value={value}>{value.replace(/([A-Z])/g, " $1").toLowerCase()}</option>)}</select><Textarea className="md:col-span-2" placeholder={proposal.changeField.endsWith("Keys") ? "Comma-separated governed keys" : "Proposed replacement value"} value={proposal.changeValue} onChange={(e) => setProposal((v) => ({ ...v, changeValue: e.target.value }))}/><Textarea placeholder="Testable hypothesis" value={proposal.hypothesis} onChange={(e) => setProposal((v) => ({ ...v, hypothesis: e.target.value }))}/><Textarea placeholder="Rollback plan" value={proposal.rollbackPlan} onChange={(e) => setProposal((v) => ({ ...v, rollbackPlan: e.target.value }))}/><Input placeholder="Success metric and threshold" value={proposal.successMetric} onChange={(e) => setProposal((v) => ({ ...v, successMetric: e.target.value }))}/><Input placeholder="Guardrail metric and threshold" value={proposal.guardrailMetric} onChange={(e) => setProposal((v) => ({ ...v, guardrailMetric: e.target.value }))}/><Button className="w-fit" disabled={action.isPending || !proposal.ownerSeatId || proposal.hypothesis.trim().length < 20 || proposal.rollbackPlan.trim().length < 20 || proposal.changeValue.trim().length < 1} onClick={() => run(`${endpoint}/proposals`, { offerId, proposalKey: proposal.proposalKey, title: proposal.title, hypothesis: proposal.hypothesis, proposedPatch: { [proposal.changeField]: patchValue }, rollbackPlan: proposal.rollbackPlan, successMetric: proposal.successMetric, guardrailMetric: proposal.guardrailMetric, feedbackSignalIds: proposal.feedbackSignalIds, ownerSeatId: proposal.ownerSeatId, classification: proposal.classification }, "Versioned change proposal created")}>Create proposal</Button></div></details>}
      <select aria-label="Change proposal" className={`${field} w-full`} value={proposalId} onChange={(e) => setProposalId(e.target.value)}><option value="">Choose change proposal</option>{(state.data?.proposals || []).filter((item: Row) => item.offerId === offerId).map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.releaseDecision} · {item.rolloutState}</option>)}</select>
      {selectedProposal && <div className="rounded-xl border p-4"><div className="flex flex-wrap gap-2">{badge(selectedProposal.compatibilityOutcome)}{badge(selectedProposal.releaseDecision)}{badge(selectedProposal.rolloutState)}<Badge variant="outline">v{selectedProposal.version}</Badge>{selectedProposal.appliedAt && <Badge>canonical applied</Badge>}</div><p className="mt-3 font-semibold">{selectedProposal.title}</p><p className="mt-1 text-sm">{selectedProposal.hypothesis}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded-lg bg-muted p-3 text-xs"><p className="font-medium">Proposed patch</p><pre className="mt-1 whitespace-pre-wrap break-words">{JSON.stringify(selectedProposal.proposedPatch, null, 2)}</pre></div><div className="rounded-lg bg-muted p-3 text-xs"><p className="font-medium">Rollback</p><p className="mt-1">{selectedProposal.rollbackPlan}</p></div></div><code className="mt-2 block break-all text-[10px] text-muted-foreground">baseline {selectedProposal.baselineOfferSha256}</code></div>}
    </CardContent></Card>}

    {selectedProposal && <>
      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle>Compatibility gate</CardTitle><CardDescription>Assess workflows, audience segments, and contracts/templates before a test begins. Breaking changes require a migration plan.</CardDescription></CardHeader><CardContent className="space-y-3">{selectedProposal.compatibilityOutcome === "pending" && canDecide ? <div className="grid gap-2"><select aria-label="Compatibility outcome" className={field} value={compatibility.outcome} onChange={(e) => setCompatibility((v) => ({ ...v, outcome: e.target.value }))}>{["compatible", "breaking", "unknown"].map((value) => <option key={value}>{value}</option>)}</select><Input placeholder="Affected workflow keys, comma separated" value={compatibility.affectedWorkflows} onChange={(e) => setCompatibility((v) => ({ ...v, affectedWorkflows: e.target.value }))}/><Input placeholder="Affected audience segments, comma separated" value={compatibility.affectedSegments} onChange={(e) => setCompatibility((v) => ({ ...v, affectedSegments: e.target.value }))}/><Input placeholder="Affected contract/template references, comma separated" value={compatibility.affectedContracts} onChange={(e) => setCompatibility((v) => ({ ...v, affectedContracts: e.target.value }))}/><Textarea placeholder="Compatibility rationale" value={compatibility.rationale} onChange={(e) => setCompatibility((v) => ({ ...v, rationale: e.target.value }))}/>{compatibility.outcome === "breaking" && <Textarea placeholder="Migration and backout plan" value={compatibility.migrationPlan} onChange={(e) => setCompatibility((v) => ({ ...v, migrationPlan: e.target.value }))}/>} {evidenceSelect("Compatibility Evidence", compatibility.evidenceId, (evidenceId) => setCompatibility((v) => ({ ...v, evidenceId })))}<Button disabled={!compatibility.evidenceId || compatibility.rationale.trim().length < 20 || (compatibility.outcome === "breaking" && compatibility.migrationPlan.trim().length < 20)} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/compatibility-reviews`, { expectedVersion: selectedProposal.version, outcome: compatibility.outcome, rationale: compatibility.rationale, affectedWorkflows: csv(compatibility.affectedWorkflows), affectedSegments: csv(compatibility.affectedSegments), affectedContracts: csv(compatibility.affectedContracts), migrationPlan: compatibility.migrationPlan, evidenceIds: [compatibility.evidenceId] }, "Compatibility decision recorded")}>Record compatibility decision</Button></div> : <div className="rounded-lg bg-muted p-3 text-sm"><div className="flex gap-2">{badge(selectedProposal.compatibilityOutcome)}</div><p className="mt-2">{selectedProposal.compatibilityRationale || "Awaiting authorized review."}</p></div>}</CardContent></Card>

        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Beaker className="h-5 w-5"/>Bounded experiment</CardTitle><CardDescription>The proposal declares the metrics; the experiment defines cohort, allocation, timebox, observations, and conclusion.</CardDescription></CardHeader><CardContent className="space-y-3">{!selectedExperiment && canExecute && ["compatible", "breaking"].includes(selectedProposal.compatibilityOutcome) ? <div className="grid gap-2"><Textarea placeholder="Experiment question" value={experiment.question} onChange={(e) => setExperiment((v) => ({ ...v, question: e.target.value }))}/><Textarea placeholder="Cohort scope, exclusions, and consent constraints" value={experiment.cohortScope} onChange={(e) => setExperiment((v) => ({ ...v, cohortScope: e.target.value }))}/><div className="grid grid-cols-3 gap-2"><Input type="number" min={1} max={100} value={experiment.allocationPercent} onChange={(e) => setExperiment((v) => ({ ...v, allocationPercent: Number(e.target.value) }))}/><Input type="date" value={experiment.startsAt} onChange={(e) => setExperiment((v) => ({ ...v, startsAt: e.target.value }))}/><Input type="date" value={experiment.endsAt} onChange={(e) => setExperiment((v) => ({ ...v, endsAt: e.target.value }))}/></div>{seatSelect("Experiment owner", experiment.ownerSeatId, (ownerSeatId) => setExperiment((v) => ({ ...v, ownerSeatId })))}<Button disabled={!experiment.ownerSeatId || experiment.question.trim().length < 20 || experiment.cohortScope.trim().length < 10} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/experiments`, { expectedProposalVersion: selectedProposal.version, ...experiment }, "Bounded experiment created")}>Create experiment</Button></div> : selectedExperiment ? <div className="rounded-lg bg-muted p-3 text-sm"><div className="flex flex-wrap gap-2">{badge(selectedExperiment.state)}{badge(selectedExperiment.result)}<Badge variant="outline">v{selectedExperiment.version}</Badge></div><p className="mt-2 font-medium">{selectedExperiment.question}</p><p className="mt-1 text-muted-foreground">{selectedExperiment.cohortScope} · {selectedExperiment.allocationPercent}% · {selectedExperiment.startsAt}–{selectedExperiment.endsAt}</p></div> : <p className="text-sm text-muted-foreground">Complete compatibility review before defining an experiment.</p>}
          {selectedExperiment && ["planned", "running"].includes(selectedExperiment.state) && canExecute && <div className="grid gap-2 border-t pt-3"><select aria-label="Experiment transition" className={field} value={transition.state} onChange={(e) => setTransition((v) => ({ ...v, state: e.target.value }))}>{selectedExperiment.state === "planned" && <option value="running">running</option>}<option value="stopped">stopped</option></select><Textarea placeholder="Why this transition is authorized now" value={transition.rationale} onChange={(e) => setTransition((v) => ({ ...v, rationale: e.target.value }))}/>{evidenceSelect("Optional transition Evidence", transition.evidenceId, (evidenceId) => setTransition((v) => ({ ...v, evidenceId })))}<Button disabled={transition.rationale.trim().length < 20} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/experiments/${selectedExperiment.id}/transitions`, { expectedProposalVersion: selectedProposal.version, expectedVersion: selectedExperiment.version, state: transition.state, rationale: transition.rationale, evidenceIds: transition.evidenceId ? [transition.evidenceId] : [] }, `Experiment ${transition.state}`)}>Record transition</Button></div>}
        </CardContent></Card>
      </div>

      {selectedExperiment?.state === "running" && <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>Telemetry observations</CardTitle><CardDescription>Record actual observed values, their authority, Evidence, window, and external reference where provider-backed.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-2"><Input placeholder="Metric key" value={observation.metricKey} onChange={(e) => setObservation((v) => ({ ...v, metricKey: e.target.value }))}/><div className="grid grid-cols-2 gap-2"><Input placeholder="Value" value={observation.value} onChange={(e) => setObservation((v) => ({ ...v, value: e.target.value }))}/><Input placeholder="Unit" value={observation.unit} onChange={(e) => setObservation((v) => ({ ...v, unit: e.target.value }))}/></div><Input type="date" value={observation.windowStart} onChange={(e) => setObservation((v) => ({ ...v, windowStart: e.target.value }))}/><Input type="date" value={observation.windowEnd} onChange={(e) => setObservation((v) => ({ ...v, windowEnd: e.target.value }))}/><select aria-label="Observation authority" className={field} value={observation.sourceAuthority} onChange={(e) => setObservation((v) => ({ ...v, sourceAuthority: e.target.value }))}>{["internal_observation", "manual_attestation", "provider_receipt", "reconciled"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><Input placeholder="Provider reference when applicable" value={observation.externalReference} onChange={(e) => setObservation((v) => ({ ...v, externalReference: e.target.value }))}/>{evidenceSelect("Observation Evidence", observation.evidenceId, (evidenceId) => setObservation((v) => ({ ...v, evidenceId })))}<Button disabled={!canExecute || !observation.evidenceId || !observation.metricKey || !observation.value || !observation.unit || (["provider_receipt", "reconciled"].includes(observation.sourceAuthority) && observation.externalReference.trim().length < 3)} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/experiments/${selectedExperiment.id}/observations`, { expectedProposalVersion: selectedProposal.version, expectedExperimentVersion: selectedExperiment.version, ...observation, evidenceIds: [observation.evidenceId], evidenceId: undefined }, "Evidence-backed observation recorded")}>Record observation</Button></div><div className="space-y-2">{observations.map((item: Row) => <div key={item.id} className="rounded-lg border p-3 text-sm"><span className="font-medium">{item.metricKey}: {item.value} {item.unit}</span><span className="block text-xs text-muted-foreground">{item.windowStart}–{item.windowEnd} · {item.sourceAuthority.replaceAll("_", " ")}</span></div>)}</div></CardContent></Card>
        <Card><CardHeader><CardTitle>Experiment conclusion</CardTitle><CardDescription>Authorized judgment stays separate from raw observations and requires verified conclusion Evidence.</CardDescription></CardHeader><CardContent className="grid gap-2"><select aria-label="Experiment result" className={field} value={conclusion.result} onChange={(e) => setConclusion((v) => ({ ...v, result: e.target.value }))}>{["met", "not_met", "inconclusive"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><Textarea placeholder="Conclusion, evidence interpretation, and limitations" value={conclusion.conclusion} onChange={(e) => setConclusion((v) => ({ ...v, conclusion: e.target.value }))}/>{evidenceSelect("Conclusion Evidence", conclusion.evidenceId, (evidenceId) => setConclusion((v) => ({ ...v, evidenceId })))}<Button disabled={!canDecide || !observations.length || !conclusion.evidenceId || conclusion.conclusion.trim().length < 20} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/experiments/${selectedExperiment.id}/conclusions`, { expectedProposalVersion: selectedProposal.version, expectedVersion: selectedExperiment.version, result: conclusion.result, conclusion: conclusion.conclusion, evidenceIds: [conclusion.evidenceId] }, "Experiment conclusion decided")}>Conclude experiment</Button></CardContent></Card></div>}

      <Card><CardHeader><CardTitle>Release, staged rollout, and canonical apply</CardTitle><CardDescription>Ship is a decision, rollout is receipt-driven execution, and canonical apply is a final founder-controlled mutation after general availability.</CardDescription></CardHeader><CardContent className="space-y-4">
        {selectedProposal.releaseDecision === "pending" && canDecide && <div className="grid gap-2 rounded-xl border p-4 md:grid-cols-2"><select aria-label="Release decision" className={field} value={release.decision} onChange={(e) => setRelease((v) => ({ ...v, decision: e.target.value }))}>{["ship", "iterate", "reject"].map((value) => <option key={value}>{value}</option>)}</select>{evidenceSelect("Release-decision Evidence", release.evidenceId, (evidenceId) => setRelease((v) => ({ ...v, evidenceId })))}<Textarea className="md:col-span-2" placeholder="Decision rationale and evidence limits" value={release.rationale} onChange={(e) => setRelease((v) => ({ ...v, rationale: e.target.value }))}/><Button className="w-fit" disabled={!release.evidenceId || release.rationale.trim().length < 20} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/release-decisions`, { expectedVersion: selectedProposal.version, decision: release.decision, rationale: release.rationale, evidenceIds: [release.evidenceId] }, "Release decision recorded")}>Record release decision</Button></div>}
        {selectedProposal.releaseDecision === "ship" && selectedProposal.rolloutState === "not_started" && canDecide && <div className="grid gap-2 rounded-xl border p-4 md:grid-cols-2"><label className="space-y-1 text-xs text-muted-foreground">Internal allocation percent<Input type="number" min={1} max={100} value={rollout.allocationPercent} onChange={(e) => setRollout((v) => ({ ...v, allocationPercent: Number(e.target.value) }))}/></label>{evidenceSelect("Rollout authorization Evidence", rollout.evidenceId, (evidenceId) => setRollout((v) => ({ ...v, evidenceId })))}<Textarea className="md:col-span-2" placeholder="Observable rollback threshold" value={rollout.rollbackThreshold} onChange={(e) => setRollout((v) => ({ ...v, rollbackThreshold: e.target.value }))}/><Button className="w-fit" disabled={!rollout.evidenceId || rollout.rollbackThreshold.trim().length < 10} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/rollouts`, { expectedVersion: selectedProposal.version, initialStage: "internal", allocationPercent: rollout.allocationPercent, rollbackThreshold: rollout.rollbackThreshold, evidenceIds: [rollout.evidenceId] }, "Internal rollout started")}>Start internal rollout</Button></div>}
        {selectedProposal.rolloutState === "running" && nextStage && canDecide && <div className="grid gap-2 rounded-xl border p-4 md:grid-cols-2"><div><p className="text-sm font-medium">Advance {selectedProposal.rolloutStage} <ArrowRight className="mx-1 inline h-4 w-4"/> {nextStage}</p><p className="text-xs text-muted-foreground">Current allocation {selectedProposal.rolloutPercent}%</p></div><Input type="number" min={selectedProposal.rolloutPercent || 1} max={100} value={advance.allocationPercent} onChange={(e) => setAdvance((v) => ({ ...v, allocationPercent: Number(e.target.value) }))}/><Input placeholder="Deployment/provider receipt reference" value={advance.externalReference} onChange={(e) => setAdvance((v) => ({ ...v, externalReference: e.target.value }))}/>{evidenceSelect("Rollout receipt Evidence", advance.receiptEvidenceId, (receiptEvidenceId) => setAdvance((v) => ({ ...v, receiptEvidenceId })))}<Textarea className="md:col-span-2" placeholder="Observed stage result and guardrail status" value={advance.note} onChange={(e) => setAdvance((v) => ({ ...v, note: e.target.value }))}/><Button className="w-fit" disabled={!advance.receiptEvidenceId || advance.externalReference.trim().length < 3 || advance.note.trim().length < 20 || (nextStage === "general" && advance.allocationPercent !== 100)} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/rollout-advances`, { expectedVersion: selectedProposal.version, stage: nextStage, allocationPercent: advance.allocationPercent, externalReference: advance.externalReference, receiptEvidenceId: advance.receiptEvidenceId, note: advance.note }, nextStage === "general" ? "General rollout completed" : `Rollout advanced to ${nextStage}`)}>Record receipt and advance</Button></div>}
        {["running", "completed"].includes(selectedProposal.rolloutState) && !selectedProposal.appliedAt && canDecide && <details><summary className="cursor-pointer text-sm font-medium text-destructive">Rollback rollout</summary><div className="mt-3 grid gap-2 md:grid-cols-2">{evidenceSelect("Rollback Evidence", rollback.evidenceId, (evidenceId) => setRollback((v) => ({ ...v, evidenceId })))}<Textarea placeholder="Trigger, scope, and rollback rationale" value={rollback.rationale} onChange={(e) => setRollback((v) => ({ ...v, rationale: e.target.value }))}/><Button variant="destructive" className="w-fit" disabled={!rollback.evidenceId || rollback.rationale.trim().length < 20} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/rollbacks`, { expectedVersion: selectedProposal.version, rationale: rollback.rationale, evidenceIds: [rollback.evidenceId] }, "Rollout rolled back") }><RotateCcw className="mr-2 h-4 w-4"/>Execute recorded rollback</Button></div></details>}
        {selectedProposal.rolloutState === "completed" && !selectedProposal.appliedAt && <div className="grid gap-2 rounded-xl border border-primary/30 p-4 md:grid-cols-2"><div className="md:col-span-2"><p className="font-medium">Canonical apply gate</p><p className="text-sm text-muted-foreground">EOS will re-hash the current canonical offer and refuse stale proposals. Native contract/template records are never silently changed by this action.</p></div>{evidenceSelect("Canonical-apply Evidence", apply.evidenceId, (evidenceId) => setApply((v) => ({ ...v, evidenceId })))}<Textarea placeholder="Why the completed rollout should become canonical" value={apply.rationale} onChange={(e) => setApply((v) => ({ ...v, rationale: e.target.value }))}/><Button className="w-fit" disabled={!canDecide || !isFounder || !apply.evidenceId || apply.rationale.trim().length < 20} onClick={() => run(`${endpoint}/proposals/${selectedProposal.id}/apply`, { expectedVersion: selectedProposal.version, rationale: apply.rationale, evidenceIds: [apply.evidenceId] }, "Canonical offer updated") }><CheckCircle2 className="mr-2 h-4 w-4"/>Apply to canonical offer</Button>{!isFounder && <p className="self-center text-xs text-muted-foreground">Founder/owner authority is required for canonical apply.</p>}</div>}
      </CardContent></Card>

      <Card><CardHeader><CardTitle>Immutable evolution history</CardTitle><CardDescription>Each decision and projection transition retains versions, policy authority, Evidence references, and a chained event hash.</CardDescription></CardHeader><CardContent><div className="space-y-2">{proposalEvents.map((item: Row) => <div key={item.id} className="rounded-lg border p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{item.eventType.replaceAll("_", " ")}</span><span>v{item.versionBefore}→{item.versionAfter}</span></div><code className="mt-1 block break-all text-[10px] text-muted-foreground">{item.eventSha256}</code></div>)}</div></CardContent></Card>
    </>}
  </div>;
}
