import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, CheckCircle2, ClipboardCheck, Plus, RefreshCw, ShieldCheck, Target } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

type Row = Record<string, any>;
type Props = { root: string; canExecute: boolean; canDecide: boolean; canApprove: boolean };
const field = "h-10 rounded-md border border-input bg-background px-3 text-sm";
const poolLabels: Record<string, string> = { missed_calls: "Missed calls", open_estimates: "Open estimates", past_customers: "Past customers" };
const transitions: Record<string, Array<[string, string]>> = {
  draft: [["approve_scope", "Approve scope"]], intake: [["complete_intake", "Complete intake"]], baseline: [["record_baseline", "Record baseline"]],
  audit: [["complete_audit", "Complete audit"]], campaign_approval: [["approve_campaigns", "Approve campaigns"]], bounded_launch: [["verify_bounded_launch", "Verify bounded launch"]],
  operating: [["start_reporting", "Start reporting"], ["start_guarantee_review", "Guarantee review"], ["start_renewal_review", "Renewal review"]],
  reporting: [["continue_management", "Continue management"], ["start_guarantee_review", "Guarantee review"], ["start_renewal_review", "Renewal review"]],
  guarantee_review: [["continue_management", "Continue management"], ["start_renewal_review", "Renewal review"], ["close", "Close"]], renewal_review: [["close", "Close"]],
  paused: [["resume", "Resume"]], recovery_required: [["restore_safe_state", "Restore safe state"]],
};

function scopedUrl(url: string) {
  if (typeof window === "undefined") return url;
  const seat = new URLSearchParams(window.location.search).get("seat");
  if (!seat) return url;
  const scoped = new URL(url, window.location.origin); scoped.searchParams.set("seatId", seat); return `${scoped.pathname}${scoped.search}`;
}
async function json<T>(method: "GET" | "POST" | "PUT", url: string, body?: unknown): Promise<T> { const response = await apiRequest(method, scopedUrl(url), body) as Response; return response.json() as Promise<T>; }
function stateBadge(state: string) { const good = ["active", "approved", "tested", "qualified", "completed", "won", "closed", "operating", "reporting"].includes(state); const bad = ["blocked", "rejected", "lost", "recovery_required", "cancelled", "disputed"].includes(state); return <Badge variant={(bad ? "destructive" : good ? "default" : "secondary") as any}>{state.replaceAll("_", " ")}</Badge>; }
const today = () => new Date().toISOString().slice(0, 10);

export function RecoveryOperationsControlCenter({ root, canExecute, canDecide, canApprove }: Props) {
  const endpoint = `${root}/recovery-operations`; const queryClient = useQueryClient(); const { toast } = useToast();
  const query = useQuery<Row>({ queryKey: [endpoint], queryFn: () => json("GET", endpoint) });
  const [engagementId, setEngagementId] = useState("");
  const refresh = async () => queryClient.invalidateQueries({ queryKey: [endpoint] });
  const action = useMutation({
    mutationFn: (input: { method?: "POST" | "PUT"; url: string; body: unknown; success: string }) => json(input.method || "POST", input.url, input.body),
    onSuccess: async (_value, input) => { await refresh(); toast({ title: input.success, description: "Canonical state, Evidence links, policy decision, and immutable event receipt were refreshed." }); },
    onError: (error) => toast({ title: "Recovery operation blocked", description: error instanceof Error ? error.message : String(error), variant: "destructive" }),
  });
  const run = (url: string, body: unknown, success: string, method: "POST" | "PUT" = "POST") => action.mutate({ method, url, body, success });

  useEffect(() => { if (!engagementId && query.data?.engagements?.[0]?.id) setEngagementId(query.data.engagements[0].id); }, [query.data?.engagements, engagementId]);
  const selected = query.data?.engagements?.find((item: Row) => item.id === engagementId);
  const evidence = query.data?.evidence || [];
  const seats = query.data?.seats || [];
  const [create, setCreate] = useState({ mode: "client_zero", title: "Empyrean Recovery Client Zero", ownerSeatId: "", call2PacketId: "", objective: "Prove the Recovery offer on lawful Empyrean first-party follow-up while preserving consent, evidence, and attribution boundaries.", eligiblePoolKeys: ["missed_calls", "open_estimates", "past_customers"], sourceBoundary: "Use only real Empyrean first-party missed or unfinished follow-up, no-shows or ghosts, and dormant qualified prospects; never fabricate client or roofing records.", consentPolicy: "A human verifies contact rights, suppression status, channel consent, quiet hours, and approved copy before any external communication.", clientSideOwner: "Empyrean operator", guaranteeWindowStart: "", guaranteeWindowEnd: "", nextAction: "Approve Client Zero scope and Evidence boundary.", nextActionAt: today(), classification: "confidential" });
  const [evidenceDraft, setEvidenceDraft] = useState({ evidenceType: "operator_observation", title: "", sourceSystem: "EOS operator", sourceReference: "", supportedClaimSummary: "", verifierMethod: "Reviewed by the accountable human operator against the named source.", consentRights: "Internal operating Evidence only; no public proof or external send authority.", dataClassification: "confidential" });
  const [transition, setTransition] = useState({ evidenceId: "", note: "", blocker: "", nextAction: "Continue the next governed Recovery stage.", nextActionAt: today() });
  const [poolDrafts, setPoolDrafts] = useState<Record<string, Row>>({});
  const [campaign, setCampaign] = useState({ poolKey: "missed_calls", name: "", channel: "manual", integrationBindingId: "", messageVersionReference: "", consentBasis: "", quietHours: "No sends outside the approved local-time window.", cadence: "One approved touch followed by the documented cadence; stop immediately on reply or opt-out.", stopConditions: "Stop on reply, booking, payment, wrong party, opt-out, dispute, or operator containment.", optOutHandling: "Suppress immediately, retain the receipt, and prevent future campaign eligibility.", routingOwnerSeatId: "", escalationOwnerSeatId: "" });
  const [campaignDecision, setCampaignDecision] = useState<Record<string, { evidenceId: string; note: string }>>({});
  const [opportunity, setOpportunity] = useState({ poolKey: "missed_calls", externalReference: "", title: "", summary: "", ownerSeatId: "", estimatedValueMinor: 0, nextAction: "Perform the next approved follow-up step.", nextActionAt: today(), evidenceId: "" });
  const [opportunityProgress, setOpportunityProgress] = useState<Record<string, { state: string; actualValueMinor: number; attributionModel: string; nextAction: string; nextActionAt: string; note: string; evidenceId: string }>>({});
  const [customerSuccess, setCustomerSuccess] = useState({ accountId: "", evidenceId: "", note: "Link this paid Recovery engagement to the exact canonical Customer Success relationship." });

  useEffect(() => { if (seats[0]?.id) { setCreate((value) => ({ ...value, ownerSeatId: value.ownerSeatId || seats[0].id })); setCampaign((value) => ({ ...value, routingOwnerSeatId: value.routingOwnerSeatId || seats[0].id, escalationOwnerSeatId: value.escalationOwnerSeatId || seats[0].id })); setOpportunity((value) => ({ ...value, ownerSeatId: value.ownerSeatId || seats[0].id })); } }, [seats]);
  const eligibleCustomerSuccess = useMemo(() => (query.data?.customerSuccessAccounts || []).filter((item: Row) => selected && item.stakeholderId === selected.stakeholderId && item.relationshipId === selected.relationshipId), [query.data?.customerSuccessAccounts, selected]);
  const evidenceSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose verified Evidence</option>{evidence.map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.evidenceType}</option>)}</select>;
  const seatSelect = (label: string, value: string, onChange: (value: string) => void) => <select aria-label={label} className={field} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose accountable seat</option>{seats.map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>;

  if (query.isLoading) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Loading live Recovery operations…</CardContent></Card>;
  if (query.isError) return <Alert variant="destructive"><AlertTriangle className="h-4 w-4"/><AlertTitle>Live Recovery state unavailable</AlertTitle><AlertDescription>EOS will not infer delivery state while the governed operating record is unavailable.</AlertDescription></Alert>;

  return <div className="space-y-6" id="recovery-operations-control-center">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Active engagements", query.data?.counts?.active], ["Blocked", query.data?.counts?.blocked], ["Real opportunities", query.data?.counts?.opportunities], ["Qualified", query.data?.counts?.qualified]].map(([label, value]) => <Card key={String(label)}><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value || 0}</p></CardContent></Card>)}</div>
    <Alert><ShieldCheck className="h-4 w-4"/><AlertTitle>Live operating boundary</AlertTitle><AlertDescription>{query.data?.boundary}</AlertDescription></Alert>

    <Card><CardHeader><CardTitle>Start or resume Recovery delivery</CardTitle><CardDescription>Client Zero uses Empyrean's real first-party records. Paid-client delivery appears only after the governed close, signature, and active billing chain.</CardDescription></CardHeader><CardContent className="space-y-4">
      {canExecute && <details><summary className="cursor-pointer text-sm font-medium">Create engagement</summary><div className="mt-4 grid gap-3 md:grid-cols-2">
        <select className={field} value={create.mode} onChange={(event) => setCreate((value) => ({ ...value, mode: event.target.value, call2PacketId: "" }))}><option value="client_zero">Empyrean Client Zero</option><option value="paid_client">Paid client</option></select>
        {create.mode === "paid_client" ? <select className={field} value={create.call2PacketId} onChange={(event) => setCreate((value) => ({ ...value, call2PacketId: event.target.value }))}><option value="">Choose paid, signed handoff</option>{(query.data?.eligiblePaidHandoffs || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title}</option>)}</select> : seatSelect("Engagement owner", create.ownerSeatId, (ownerSeatId) => setCreate((value) => ({ ...value, ownerSeatId })))}
        {create.mode === "paid_client" && seatSelect("Engagement owner", create.ownerSeatId, (ownerSeatId) => setCreate((value) => ({ ...value, ownerSeatId })))}
        <Input placeholder="Engagement title" value={create.title} onChange={(event) => setCreate((value) => ({ ...value, title: event.target.value }))}/>
        <Textarea placeholder="Observable objective" value={create.objective} onChange={(event) => setCreate((value) => ({ ...value, objective: event.target.value }))}/><Textarea placeholder="Permitted source boundary" value={create.sourceBoundary} onChange={(event) => setCreate((value) => ({ ...value, sourceBoundary: event.target.value }))}/><Textarea placeholder="Consent and suppression policy" value={create.consentPolicy} onChange={(event) => setCreate((value) => ({ ...value, consentPolicy: event.target.value }))}/>
        <Input placeholder="Client-side owner" value={create.clientSideOwner} onChange={(event) => setCreate((value) => ({ ...value, clientSideOwner: event.target.value }))}/><Input placeholder="Next action" value={create.nextAction} onChange={(event) => setCreate((value) => ({ ...value, nextAction: event.target.value }))}/>
        <div className="md:col-span-2 flex flex-wrap gap-3">{Object.entries(poolLabels).map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={create.eligiblePoolKeys.includes(key)} onChange={(event) => setCreate((value) => ({ ...value, eligiblePoolKeys: event.target.checked ? [...value.eligiblePoolKeys, key] : value.eligiblePoolKeys.filter((item) => item !== key) }))}/>{label}</label>)}</div>
        <Button className="w-fit" disabled={action.isPending || !create.ownerSeatId || !create.eligiblePoolKeys.length || create.objective.length < 20 || (create.mode === "paid_client" && !create.call2PacketId)} onClick={() => run(`${endpoint}/engagements`, create, "Recovery engagement created")}><Plus className="mr-2 h-4 w-4"/>Create governed engagement</Button>
      </div></details>}
      <div className="flex flex-col gap-2 md:flex-row"><select className={`${field} flex-1`} value={engagementId} onChange={(event) => setEngagementId(event.target.value)}><option value="">Choose Recovery engagement</option>{(query.data?.engagements || []).map((item: Row) => <option key={item.id} value={item.id}>{item.title} · {item.state.replaceAll("_", " ")}</option>)}</select><Button variant="outline" onClick={() => refresh()} disabled={query.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`}/>Refresh</Button></div>
      {selected && <div className="rounded-xl border p-4"><div className="flex flex-wrap items-center gap-2">{stateBadge(selected.state)}<Badge variant="outline">{selected.mode.replaceAll("_", " ")}</Badge><Badge variant="outline">v{selected.version}</Badge><span className="ml-auto text-sm font-medium">{selected.progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${selected.progress}%` }}/></div><p className="mt-3 text-sm">{selected.objective}</p><p className="mt-2 text-xs text-muted-foreground">Next: {selected.nextAction} · EOS provider effects: {selected.externalEffectsExecuted ? "recorded" : "none recorded"}</p></div>}
    </CardContent></Card>

    {selected && <>
      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5"/>Evidence ledger</CardTitle><CardDescription>Operator observations are useful but remain distinct from independent provider receipts.</CardDescription></CardHeader><CardContent className="space-y-3">
          {canExecute && <><div className="grid gap-2 md:grid-cols-2"><select className={field} value={evidenceDraft.evidenceType} onChange={(event) => setEvidenceDraft((value) => ({ ...value, evidenceType: event.target.value }))}>{["operator_observation", "scope_approval", "consent_review", "baseline_snapshot", "data_quality_receipt", "campaign_approval", "postmortem"].map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><Input placeholder="Evidence title" value={evidenceDraft.title} onChange={(event) => setEvidenceDraft((value) => ({ ...value, title: event.target.value }))}/><Input placeholder="Source system" value={evidenceDraft.sourceSystem} onChange={(event) => setEvidenceDraft((value) => ({ ...value, sourceSystem: event.target.value }))}/><Input placeholder="Non-secret source reference" value={evidenceDraft.sourceReference} onChange={(event) => setEvidenceDraft((value) => ({ ...value, sourceReference: event.target.value }))}/><Textarea placeholder="Exact claim supported" value={evidenceDraft.supportedClaimSummary} onChange={(event) => setEvidenceDraft((value) => ({ ...value, supportedClaimSummary: event.target.value }))}/><Textarea placeholder="Verification method" value={evidenceDraft.verifierMethod} onChange={(event) => setEvidenceDraft((value) => ({ ...value, verifierMethod: event.target.value }))}/><Textarea className="md:col-span-2" placeholder="Consent and usage rights" value={evidenceDraft.consentRights} onChange={(event) => setEvidenceDraft((value) => ({ ...value, consentRights: event.target.value }))}/></div><p className="text-xs text-muted-foreground">External receipts must come from a signed provider ingress, customer portal, or the governed Evidence workflow; this form cannot mint them.</p><Button disabled={action.isPending || evidenceDraft.title.length < 5 || evidenceDraft.sourceReference.length < 3 || evidenceDraft.supportedClaimSummary.length < 20} onClick={() => run(`${endpoint}/engagements/${selected.id}/evidence`, evidenceDraft, "Evidence recorded")}><Plus className="mr-2 h-4 w-4"/>Record Evidence</Button></>}
          <div className="space-y-2">{selected.events.slice().reverse().slice(0, 8).map((item: Row) => <div key={item.id} className="rounded-lg bg-muted p-3 text-sm"><div className="flex justify-between gap-2"><span className="font-medium">{item.eventType.replaceAll("_", " ")}</span><span className="text-xs text-muted-foreground">#{item.sequence}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.fromState.replaceAll("_", " ")} → {item.toState.replaceAll("_", " ")} · {item.eventSha256.slice(0, 12)}</p></div>)}</div>
        </CardContent></Card>

        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5"/>Lifecycle control</CardTitle><CardDescription>Each advancement needs verified Evidence and passes stage-specific prerequisites.</CardDescription></CardHeader><CardContent className="space-y-3">
          {evidenceSelect("Lifecycle Evidence", transition.evidenceId, (evidenceId) => setTransition((value) => ({ ...value, evidenceId })))}<Textarea placeholder="Decision or execution rationale" value={transition.note} onChange={(event) => setTransition((value) => ({ ...value, note: event.target.value }))}/><Input placeholder="Accountable next action" value={transition.nextAction} onChange={(event) => setTransition((value) => ({ ...value, nextAction: event.target.value }))}/>
          <div className="flex flex-wrap gap-2">{(transitions[selected.state] || []).map(([key, label]) => <Button key={key} disabled={action.isPending || !transition.evidenceId || transition.note.length < 20 || (["approve_scope", "approve_campaigns", "start_renewal_review", "close"].includes(key) ? !canDecide : !canExecute)} onClick={() => run(`${endpoint}/engagements/${selected.id}/transitions`, { expectedVersion: selected.version, action: key, note: transition.note, evidenceIds: [transition.evidenceId], blocker: transition.blocker, nextAction: transition.nextAction, nextActionAt: transition.nextActionAt }, `${label} recorded`)}>{label}</Button>)}</div>
          {!(["closed", "cancelled", "draft", "paused", "recovery_required"].includes(selected.state)) && <div className="rounded-lg border border-destructive/30 p-3"><Input placeholder="Named blocker and containment condition" value={transition.blocker} onChange={(event) => setTransition((value) => ({ ...value, blocker: event.target.value }))}/><div className="mt-2 flex gap-2"><Button variant="outline" disabled={!canDecide || !transition.evidenceId || transition.note.length < 20} onClick={() => run(`${endpoint}/engagements/${selected.id}/transitions`, { expectedVersion: selected.version, action: "pause", note: transition.note, evidenceIds: [transition.evidenceId], nextAction: transition.nextAction }, "Engagement paused")}>Pause</Button><Button variant="destructive" disabled={!canExecute || !transition.evidenceId || transition.note.length < 20 || transition.blocker.length < 10} onClick={() => run(`${endpoint}/engagements/${selected.id}/transitions`, { expectedVersion: selected.version, action: "report_failure", note: transition.note, blocker: transition.blocker, evidenceIds: [transition.evidenceId], nextAction: transition.nextAction }, "Failure contained")}>Report failure</Button></div></div>}
          <div className="grid grid-cols-2 gap-2 text-xs">{Object.entries(selected.readiness || {}).map(([key, value]) => <div key={key} className="rounded-lg bg-muted p-2"><span className="text-muted-foreground">{key.replace(/([A-Z])/g, " $1")}</span><p className="font-semibold">{typeof value === "boolean" ? (value ? "Ready" : "Not ready") : String(value)}</p></div>)}</div>
        </CardContent></Card>
      </div>

      <Card><CardHeader><CardTitle>Three-pool baseline and audit</CardTitle><CardDescription>Counts reconcile raw, excluded, eligible, and activation-ready records. Every eligible pool requires Evidence.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-3">{selected.pools.map((pool: Row) => { const draft = poolDrafts[pool.id] || { state: pool.state, sourceSystemReference: pool.sourceSystemReference, rawCount: pool.rawCount, eligibleCount: pool.eligibleCount, excludedCount: pool.excludedCount, activationReadyCount: pool.activationReadyCount, exclusionSummary: pool.exclusionSummary, qualificationNote: pool.qualificationNote, evidenceId: pool.evidenceIds?.[0] || "" }; const set = (patch: Row) => setPoolDrafts((value) => ({ ...value, [pool.id]: { ...draft, ...patch } })); const eligible = selected.eligiblePoolKeys.includes(pool.poolKey); return <div key={pool.id} className={`rounded-xl border p-4 ${eligible ? "" : "opacity-60"}`}><div className="flex justify-between gap-2"><p className="font-semibold">{poolLabels[pool.poolKey]}</p>{stateBadge(pool.state)}</div>{eligible && canExecute && <div className="mt-3 grid gap-2"><select className={field} value={draft.state} onChange={(event) => set({ state: event.target.value })}>{["collecting", "qualified", "approved", "active", "paused", "completed", "blocked"].map((value) => <option key={value}>{value}</option>)}</select><Input placeholder="Source-system reference" value={draft.sourceSystemReference} onChange={(event) => set({ sourceSystemReference: event.target.value })}/><div className="grid grid-cols-2 gap-2">{[["rawCount", "Raw"], ["eligibleCount", "Eligible"], ["excludedCount", "Excluded"], ["activationReadyCount", "Ready"]].map(([key, label]) => <label key={key} className="text-xs text-muted-foreground">{label}<Input type="number" min={0} value={draft[key]} onChange={(event) => set({ [key]: Number(event.target.value) })}/></label>)}</div><Textarea placeholder="Exclusions and reason" value={draft.exclusionSummary} onChange={(event) => set({ exclusionSummary: event.target.value })}/><Textarea placeholder="Qualification observation and limits" value={draft.qualificationNote} onChange={(event) => set({ qualificationNote: event.target.value })}/>{evidenceSelect(`${poolLabels[pool.poolKey]} Evidence`, draft.evidenceId, (evidenceId) => set({ evidenceId }))}<Button disabled={!draft.evidenceId || draft.sourceSystemReference.length < 3 || draft.qualificationNote.length < 20} onClick={() => run(`${endpoint}/engagements/${selected.id}/pools/${pool.poolKey}`, { ...draft, expectedVersion: pool.version, evidenceIds: [draft.evidenceId], evidenceId: undefined }, `${poolLabels[pool.poolKey]} updated`, "PUT")}>Save pool audit</Button></div>}</div>; })}</CardContent></Card>

      <div className="grid gap-6 xl:grid-cols-2">
        <Card><CardHeader><CardTitle>Campaign approval and bounded launch</CardTitle><CardDescription>Configure copy, consent, cadence, ownership, stop rules, and an exact provider binding before activation.</CardDescription></CardHeader><CardContent className="space-y-4">
          {canExecute && <details><summary className="cursor-pointer text-sm font-medium">Configure campaign</summary><div className="mt-3 grid gap-2"><select className={field} value={campaign.poolKey} onChange={(event) => setCampaign((value) => ({ ...value, poolKey: event.target.value }))}>{selected.eligiblePoolKeys.map((key: string) => <option key={key} value={key}>{poolLabels[key]}</option>)}</select><Input placeholder="Campaign name" value={campaign.name} onChange={(event) => setCampaign((value) => ({ ...value, name: event.target.value }))}/><select className={field} value={campaign.channel} onChange={(event) => setCampaign((value) => ({ ...value, channel: event.target.value }))}>{["manual", "sms", "email", "phone", "mixed"].map((value) => <option key={value}>{value}</option>)}</select><select className={field} value={campaign.integrationBindingId} onChange={(event) => setCampaign((value) => ({ ...value, integrationBindingId: event.target.value }))}><option value="">No automated binding</option>{(query.data?.bindings || []).map((item: Row) => <option key={item.id} value={item.id}>{item.name} · {item.ready ? "ready" : "not ready"}</option>)}</select><Input placeholder="Approved message version reference" value={campaign.messageVersionReference} onChange={(event) => setCampaign((value) => ({ ...value, messageVersionReference: event.target.value }))}/><Textarea placeholder="Consent basis for this audience and channel" value={campaign.consentBasis} onChange={(event) => setCampaign((value) => ({ ...value, consentBasis: event.target.value }))}/><Textarea placeholder="Cadence" value={campaign.cadence} onChange={(event) => setCampaign((value) => ({ ...value, cadence: event.target.value }))}/><Textarea placeholder="Stop conditions" value={campaign.stopConditions} onChange={(event) => setCampaign((value) => ({ ...value, stopConditions: event.target.value }))}/>{seatSelect("Routing owner", campaign.routingOwnerSeatId, (routingOwnerSeatId) => setCampaign((value) => ({ ...value, routingOwnerSeatId })))}{seatSelect("Escalation owner", campaign.escalationOwnerSeatId, (escalationOwnerSeatId) => setCampaign((value) => ({ ...value, escalationOwnerSeatId })))}<Button disabled={!campaign.name || campaign.consentBasis.length < 20 || !campaign.routingOwnerSeatId || !campaign.escalationOwnerSeatId} onClick={() => run(`${endpoint}/engagements/${selected.id}/campaigns`, campaign, "Campaign control configured", "PUT")}>Save campaign draft</Button></div></details>}
          <div className="space-y-3">{selected.campaigns.map((item: Row) => { const decision = campaignDecision[item.id] || { evidenceId: "", note: "" }; const set = (patch: Row) => setCampaignDecision((value) => ({ ...value, [item.id]: { ...decision, ...patch } })); const available: Record<string, string[]> = { draft: ["submit"], awaiting_approval: ["approve", "reject"], approved: ["verify_test"], tested: ["activate"], active: ["pause", "complete"], paused: ["activate", "complete"] }; return <div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><p className="font-medium">{item.name}</p>{stateBadge(item.state)}</div><p className="mt-1 text-xs text-muted-foreground">{poolLabels[item.poolKey]} · {item.channel} · v{item.version}</p><div className="mt-3 grid gap-2">{evidenceSelect(`${item.name} decision Evidence`, decision.evidenceId, (evidenceId) => set({ evidenceId }))}<Textarea placeholder="Approval, test, activation, or containment rationale" value={decision.note} onChange={(event) => set({ note: event.target.value })}/><div className="flex flex-wrap gap-2">{(available[item.state] || []).map((key) => <Button key={key} size="sm" variant={key === "reject" || key === "pause" ? "outline" : "default"} disabled={!decision.evidenceId || decision.note.length < 20 || (["approve", "reject", "activate"].includes(key) ? !canApprove : ["pause", "complete"].includes(key) ? !canDecide : !canExecute)} onClick={() => run(`${endpoint}/engagements/${selected.id}/campaigns/${item.id}/decisions`, { expectedVersion: item.version, decision: key, note: decision.note, evidenceIds: [decision.evidenceId] }, `Campaign ${key.replaceAll("_", " ")} recorded`)}>{key.replaceAll("_", " ")}</Button>)}</div></div></div>; })}</div>
        </CardContent></Card>

        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5"/>Opportunity and attribution ledger</CardTitle><CardDescription>Store a one-way hash of the external record reference; retain Evidence for every material state and value claim.</CardDescription></CardHeader><CardContent className="space-y-4">
          {canExecute && ["bounded_launch", "operating", "reporting", "guarantee_review", "renewal_review"].includes(selected.state) && <details><summary className="cursor-pointer text-sm font-medium">Record real opportunity</summary><div className="mt-3 grid gap-2"><select className={field} value={opportunity.poolKey} onChange={(event) => setOpportunity((value) => ({ ...value, poolKey: event.target.value }))}>{selected.eligiblePoolKeys.map((key: string) => <option key={key} value={key}>{poolLabels[key]}</option>)}</select><Input placeholder="External record reference (hashed, not stored)" value={opportunity.externalReference} onChange={(event) => setOpportunity((value) => ({ ...value, externalReference: event.target.value }))}/><Input placeholder="Opportunity title" value={opportunity.title} onChange={(event) => setOpportunity((value) => ({ ...value, title: event.target.value }))}/><Textarea placeholder="Observed status and boundaries" value={opportunity.summary} onChange={(event) => setOpportunity((value) => ({ ...value, summary: event.target.value }))}/>{seatSelect("Opportunity owner", opportunity.ownerSeatId, (ownerSeatId) => setOpportunity((value) => ({ ...value, ownerSeatId })))}{evidenceSelect("Opportunity Evidence", opportunity.evidenceId, (evidenceId) => setOpportunity((value) => ({ ...value, evidenceId })))}<Input type="number" min={0} placeholder="Estimated value in cents" value={opportunity.estimatedValueMinor} onChange={(event) => setOpportunity((value) => ({ ...value, estimatedValueMinor: Number(event.target.value) }))}/><Button disabled={!opportunity.evidenceId || !opportunity.ownerSeatId || opportunity.summary.length < 20} onClick={() => run(`${endpoint}/engagements/${selected.id}/opportunities`, { ...opportunity, evidenceIds: [opportunity.evidenceId], evidenceId: undefined }, "Opportunity recorded")}>Record opportunity</Button></div></details>}
          <div className="space-y-3">{selected.opportunities.map((item: Row) => { const draft = opportunityProgress[item.id] || { state: item.state, actualValueMinor: item.actualValueMinor, attributionModel: item.attributionModel, nextAction: item.nextAction, nextActionAt: item.nextActionAt || today(), note: "", evidenceId: "" }; const set = (patch: Row) => setOpportunityProgress((value) => ({ ...value, [item.id]: { ...draft, ...patch } })); return <div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><p className="font-medium">{item.title}</p>{stateBadge(item.state)}</div><p className="mt-1 text-xs text-muted-foreground">{poolLabels[item.poolKey]} · ${(item.estimatedValueMinor / 100).toLocaleString()} estimated</p>{!(["won", "lost", "suppressed"].includes(item.state)) && <div className="mt-3 grid gap-2"><select className={field} value={draft.state} onChange={(event) => set({ state: event.target.value })}>{["identified", "contacted", "replied", "qualified", "routed", "booked", "won", "lost", "suppressed", "disputed"].map((value) => <option key={value}>{value}</option>)}</select><select className={field} value={draft.attributionModel} onChange={(event) => set({ attributionModel: event.target.value })}>{["unattributed", "assisted", "direct", "disputed"].map((value) => <option key={value}>{value}</option>)}</select><Input type="number" min={0} placeholder="Actual value in cents" value={draft.actualValueMinor} onChange={(event) => set({ actualValueMinor: Number(event.target.value) })}/>{evidenceSelect(`${item.title} progress Evidence`, draft.evidenceId, (evidenceId) => set({ evidenceId }))}<Textarea placeholder="Observed transition and attribution limits" value={draft.note} onChange={(event) => set({ note: event.target.value })}/><Button size="sm" disabled={!draft.evidenceId || draft.note.length < 20 || (["won", "lost", "suppressed"].includes(draft.state) ? !canDecide : !canExecute)} onClick={() => run(`${endpoint}/engagements/${selected.id}/opportunities/${item.id}/transitions`, { ...draft, expectedVersion: item.version, evidenceIds: [draft.evidenceId], evidenceId: undefined }, "Opportunity state recorded")}>Update opportunity</Button></div>}</div>; })}</div>
        </CardContent></Card>
      </div>

      {selected.mode === "paid_client" && <Card><CardHeader><CardTitle>Customer Success handoff</CardTitle><CardDescription>Link delivery to the exact customer relationship before renewal review; create that account in Module 7 if none is eligible.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><select className={field} value={customerSuccess.accountId} onChange={(event) => setCustomerSuccess((value) => ({ ...value, accountId: event.target.value }))}><option value="">Choose exact Customer Success account</option>{eligibleCustomerSuccess.map((item: Row) => <option key={item.id} value={item.id}>{item.id.slice(0, 8)} · {item.lifecycleState}</option>)}</select>{evidenceSelect("Customer Success link Evidence", customerSuccess.evidenceId, (evidenceId) => setCustomerSuccess((value) => ({ ...value, evidenceId })))}<Textarea className="md:col-span-2" value={customerSuccess.note} onChange={(event) => setCustomerSuccess((value) => ({ ...value, note: event.target.value }))}/><Button className="w-fit" disabled={!canDecide || !customerSuccess.accountId || !customerSuccess.evidenceId || customerSuccess.note.length < 20} onClick={() => run(`${endpoint}/engagements/${selected.id}/customer-success-link`, { expectedVersion: selected.version, customerSuccessAccountId: customerSuccess.accountId, evidenceIds: [customerSuccess.evidenceId], note: customerSuccess.note }, "Customer Success linked")}><CheckCircle2 className="mr-2 h-4 w-4"/>Link account</Button></CardContent></Card>}
    </>}
  </div>;
}
